### ISSUE TITLE
`StableInputNumber` requires long loading times

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1001]
Per @abhcs:

"The value is duplicated at two levels: inside InputNumber and in the wrapper. Thus, changing a value causes two renders instead of one. The reason for using the anti-pattern was because there is no straightforward way of accessing the value inside InputNumber."

**Comment by abhcs** [comment]
My analysis of slow load times in the last comment in #975 was incorrect. I assumed you were seeing sluggish behavior *while typing* -- this observation could be explained by my theory of state duplication. However, you referring to slow load times *after submitting the value* through PressEnter or Blur. The `submitValue` function is the same as before -- so you should see the sluggishness even for `InputField`. I have not had any trouble using `StableInputNumber` yet -- this issue can be closed.

**Comment by anth-volk** [comment]
Gotcha. Alright, I'll close this one, and I think this'll be something we'll have to address in a redesign of the calculator components. We definitely need to create a better design that limits the number of API calls and household creation calls where possible.
