### ISSUE TITLE
Alter domains so that junk country ID values don't merely get appended to the URL

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1002]
For example, if I visit "https://www.policyengine.org/api/", this merely displays home, and I can then go to the calculator and all the relevant information is merely appended after "api" instead of requiring a country ID. This should be fixed.

**Comment by dotslashbit** [comment]
I noticed not only about and donate but the homepage too has this issue.

https://github.com/PolicyEngine/policyengine-app/assets/46224156/a3e8f853-77ce-45d7-8151-787b57ec0a2c

**Comment by anth-volk** [comment]
This is no longer an issue. Fixed via #1803.
