### ISSUE TITLE
Clarify bar connectors in budget waterfall chart

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1005]
In [this config](https://policyengine.org/us/policy?focus=policyOutput.netIncome&household=38298&region=us&timePeriod=2023&baseline=2&reform=42382), I see:

<img width="760" alt="Screenshot 2023-12-21 at 7 13 55 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/fa632e80-633f-4883-bafd-dd6584f4e54a">

The benefit spending is an increase of $2.7 million but is displayed between `-80` and `-90` for some reason -- see y-axis guides.  The other two bars start at `0`.

**Comment by MaxGhenis** [comment]
This is intended add it's a waterfall chart

**Comment by abhcs** [comment]
Oh good to know. Imo, it is impossible to tell that this is a waterfall chart in this case because the connections between the bars are as thick as the middle bar itself.

**Comment by MaxGhenis** [comment]
That looks good! I updated the issue title and reopened it, could you file a PR?

**Comment by anth-volk** [comment]
Yeah, this is certainly a visual improvement, thanks @abhcs!
