### ISSUE TITLE
Correct title of the API explorer page

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1023]
At the moment, the title of the page at https://www.policyengine.org/us/api is `Api | PolicyEngine US`. Would be great to change this to `API | PolicyEngine US` to properly reflect the acronym.

**Comment by Ali-Aldawoodi** [comment]
Hello! Am I okay to work on this? Also this is my first contribution!

**Comment by anth-volk** [comment]
@Ali-Aldawoodi Definitely! We don't typically assign contributors, so please just create a fork of the main repo, then open a PR from it when finished.

**Comment by Ali-Aldawoodi** [comment]
Awesome will do!

**Comment by Ali-Aldawoodi** [comment]
I am currently trying to solve this however im finding it difficult because when I run it locally, the page title does not update. It stays the same regardless of page. So I cant test whether my solutions are working.

![image](https://github.com/PolicyEngine/policyengine-app/assets/124013342/a9adc018-227b-48a7-b61a-8e06a8dc78fb)

**Comment by anth-volk** [comment]
That is incredibly strange. I can confirm that for me, the titles are not functioning.

**Comment by Ali-Aldawoodi** [comment]
Yes strange indeed. I can simply change the page title, somthing like: document.title = 'API documentation'? If not, I am not too sure how else I can find solutions locally

**Comment by anth-volk** [comment]
Yeah, at the moment, that's what we'd typically do, though I'd place it inside of an effect hook, as `document` sits outside of React's `root`, and therefore should probably be managed as a side effect.

**Comment by Ali-Aldawoodi** [comment]
Awesome and no problem! Glad this was my first issue and that I could help.

**Comment by dotslashbit** [comment]
If this is solved, then please close this

**Comment by anth-volk** [comment]
Thanks @dotslashbit, looks like the PR didn't link properly. Closing.
