### ISSUE TITLE
Prevent highlighting of buttons

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1029]
At the moment, while clicking on a Button component, a user can highlight the text on top of it because the button doesn't prevent this. This should ideally function more like a standard button and prevent this behavior.

**Comment by MaxGhenis** [comment]
Can we start from scratch with an established button component? Even if it's not pretty I think we should focus on usability before adding flourish.

**Comment by anth-volk** [comment]
For sure. I'm chatting with Nikhil about creating a broader "brand guide," and as part of that, we should put on paper that we're committing to a particular component, and then revamp from there.

**Comment by dotslashbit** [comment]
@anth-volk Any update on this?

**Comment by anth-volk** [comment]
@dotslashbit That brand guide is currently sitting with Nikhil in draft stage. That said, I feel confident enough that we should redesign the buttons using Ant Design in a way that:

1. Ensures they're buttons under the hood
2. Ensures the buttons can be sized with variable units (like % and vh/vw)
3. Applies any effect instantly, as opposed to with a delay

If you'd be willing, it'd be great if we could move over to #950 and implement this.

**Comment by dotslashbit** [comment]
@anth-volk Yes, I would love to work on that, if there's some design or any specific kind of button or any kind of information you want to give, then please mention the details in that issue. I'll be taking that, thanks

**Comment by anth-volk** [comment]
This was fixed thanks to changes from @dotslashbit a while back. Closing.
