### ISSUE TITLE
Remove the i logo from the reform calculator output interstitial

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1030]
Appears we missed this one in a previous issue.

**Comment by dotslashbit** [comment]
This was already closed right https://github.com/PolicyEngine/policyengine-app/issues/916

**Comment by anth-volk** [comment]
It was for the household calculator, but for policy reforms, it persists:

<img width="1440" alt="Screen Shot 2023-12-27 at 12 39 28 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/84f66746-e1e7-4ca3-ab3b-f1788aad186b">

**Comment by dotslashbit** [comment]
Ok, I will work on this

**Comment by anth-volk** [comment]
Thanks so much!

**Comment by SanjayNithin2002** [comment]
Worked on this.  Replaced info icon with success icon upon generating results. 
https://github.com/SanjayNithin2002/policyengine-app

**Comment by anth-volk** [comment]
Hey @SanjayNithin2002, to contribute in the future, please open a pull request from your fork that references this issue.

**Comment by SanjayNithin2002** [comment]
@anth-volk Thanks for sharing!
