### ISSUE TITLE
Once I choose a calculator I cannot go back using the browser's back button

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1035]
Once I choose a [calculator](https://policyengine.org/us/calculator), I cannot go back using the browser's back button (or Alt + LeftArrow). I have checked this on Safari and Chrome browsers.

**Comment by dotslashbit** [comment]
@abhcs I'm able to go back with browsers back button on firefox and safari

**Comment by anth-volk** [comment]
Whereas, weirdly enough, I'm not with Firefox

**Comment by abhcs** [comment]
3/3 for me, can't go back on any of these. Also checked incognito/private modes.

**Comment by dotslashbit** [comment]
@abhcs My bad, I thought you are talking about that calculator link at top right.
You are right, its not going back
