### ISSUE TITLE
Hide cliff analytics

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1036]
Until we fix https://github.com/PolicyEngine/policyengine-us/issues/3538

**Comment by anth-volk** [comment]
Would this be merely the Cliff Impacts page, or the display of the cliff highlighting on the relevant charts, as well?

**Comment by MaxGhenis** [comment]
Just cliff impacts microsim page. But @nikhilwoodruff is working on https://github.com/PolicyEngine/policyengine-us/issues/3538 right now, let's hold off in case he can fix it tonight.

**Comment by anth-volk** [comment]
Sounds good, will do

**Comment by MaxGhenis** [comment]
@nikhilwoodruff fixed https://github.com/PolicyEngine/policyengine-us/issues/3538

But I'm still not confident in the results, and 2022 is broken - see https://github.com/PolicyEngine/policyengine-us/discussions/3544

Let's hide it.

**Comment by anth-volk** [comment]
Apologies, I should've gotten to this today but didn't check on my notifications. If this is still desired, I should be able to do this at some point tomorrow.

**Comment by anth-volk** [comment]
Apologies, didn't get the update that this should be done. I'll get on it today and will open a PR for review.

**Comment by anth-volk** [comment]
Correction, this will likely wait until tomorrow, as I'll be prioritizing #1087 instead.

**Comment by MaxGhenis** [comment]
Not fixed https://www.loom.com/share/986eb17086da49d19fa40abba4444f6a

**Comment by anth-volk** [comment]
Very strange; looking into it

**Comment by anth-volk** [comment]
So the code works for me locally. Turns out the deployment never ran properly. Reason?

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Your app may not have more than 210 versions. Please delete one of the existing versions before trying to create a new version.
```

With approval, I can go in and delete, say, the last 150 versions?

**Comment by MaxGhenis** [comment]
End them.

**Comment by anth-volk** [comment]
150 versions deleted, re-running deploy

**Comment by anth-volk** [comment]
We are now deployed, and I just checked and it is running properly when selecting "Make the CTC fully refundable" as a policy. Closing.
