### ISSUE TITLE
Change `benefits` to `increases the net income of` in intra-decile chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1037]
These would be more neutral/objective, and match the language in other decile plots

**Comment by abhcs** [comment]
Please clarify which text you are referring to here (which element of which chart).

**Comment by anth-volk** [comment]
This should be the decile charts in the policy calculator, but feel free to correct me if I'm wrong, Max

**Comment by abhcs** [comment]
That was my guess but I don't see the text `better off` in charts currently.

**Comment by anth-volk** [comment]
I'm not seeing it, either, but my wifi is crawling today, so I'm having difficulty loading the cliff impacts page. This could also be on the new labor supply page, but I haven't actually found `{better, worse} off` in the code at all. Perhaps Max can shed some light into it later.

**Comment by MaxGhenis** [comment]
Sorry, meant `benefit` -> `increase the net income of` like other decile charts

<img width="712" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/5bc81db8-37a5-4d68-82b8-def63bad2422">

https://policyengine.org/us/policy?focus=policyOutput.intraDecileImpact&reform=14&region=us&timePeriod=2024&baseline=2
