### ISSUE TITLE
Pages on the navbar do not have unique titles

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1040]
For at least any pages created post-redesign (About, Research, Donate), the pages themselves have no distinct page title, instead merely displaying "PolicyEngine" on the browser tab.

**Comment by dotslashbit** [comment]
Can't we use an effect to handle document title at initial render

**Comment by anth-volk** [comment]
@dotslashbit When you say "initial render," are you referring to within the page's component itself, or the broader PolicyEngine component? If it's the first, yes, we should be able to do so, it looks like it may have been overlooked when these were built out.

**Comment by dotslashbit** [comment]
Yes, I'm talking about rendering the page's component itself and not the entire PolicyEngine component
