### ISSUE TITLE
Use React-Helmet to manage the document head

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1041]
Instead of manually declaring things like `document.title`, we should probably switch to using `react-helmet` for this purpose. I have to wonder if it wouldn't also help with things like SEO?

**Comment by dotslashbit** [comment]
@anth-volk As we are already using helmet, can we refactor the codebase to use helmet instead of using document.title.
Please let me know what you think about this? I'm interested to work on this

**Comment by anth-volk** [comment]
@dotslashbit Definitely, would love for you to do so
