### ISSUE TITLE
Text on Income Inequality Impact page is incorrect

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1050]
The text at the bottom in this image contains what appears to be a code separator that is rendering as text:

<img width="1440" alt="Screen Shot 2023-12-28 at 12 21 13 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/b24bfdd0-9bc5-4a49-9790-235a565dc13e">

**Comment by gautamjuyal** [comment]
Can you point out the exactly which part is it? Also, I would like to work on the issue.

**Comment by anth-volk** [comment]
We'd love your contribution! To contribute, please fork this repo, then open a PR from it to this one.

And it's the `/` in the text beginning with "The chart above"

**Comment by gautamjuyal** [comment]
I just checked the jsx file for the page, and found the `\` is a part of the description text itself and not the code. 
![Screenshot (363)](https://github.com/PolicyEngine/policyengine-app/assets/75676784/06fb6b43-f01e-4609-a5c5-345d75ec0409)

**Comment by anth-volk** [comment]
Precisely, this is a typo

**Comment by cullantd** [comment]
Hi @anth-volk, I submitted [this PR](https://github.com/PolicyEngine/policyengine-app/pull/1055) in response to the issue you raised.

**Comment by MaxGhenis** [comment]
Thanks @cullantd! Closing as you fixed this in #1055. Please link the PR to the issue next time: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

For future reference, maintainers including @anth-volk and myself watch the repo, so no need to comment to grab our attention or mention the PRs (linking suffices). Appreciate your contributions!
