### ISSUE TITLE
Policy calculator right-hand sidebar now defaults to 2024 for simulations

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1052]
Is this intentional?

<img width="1440" alt="Screen Shot 2023-12-28 at 1 01 14 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/3fbc18a0-0a58-4bf5-903e-169ae90a23df">

**Comment by MaxGhenis** [comment]
Not sure but I think we can leave it for these final days
