### ISSUE TITLE
Configure linter properly for react and fix errors in current code

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1080]
eslint is not configured properly for react. Consider [this example](https://react.dev/learn/lifecycle-of-reactive-effects#react-verifies-that-you-specified-every-reactive-value-as-a-dependency) from react docs that a linter should be able to detect. When I add this example to our src directory, it is unable to detect the error.

On configuring eslint properly, as recommended [here](https://react.dev/learn/editor-setup#linting), I get 50 errors and 36 warnings in the src directory. A portion of the errors is shown below:

<img width="730" alt="Screenshot 2023-12-31 at 11 34 33 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/4cf21747-c19e-4fdb-b895-09ae579c0d81">

This means that we are not complying with the minimum recommendations from react on how to use hooks and other features. We should
- fix these errors, and
- configure eslint properly

**Comment by dotslashbit** [comment]
@abhcs Is there a possibility that I can also work on this or only the core team will work on this?

**Comment by MaxGhenis** [comment]
@dotslashbit in general feel free to work on issues that don't have assignees or PRs linked. In this case, @abhcs has already started working on a solution in https://github.com/PolicyEngine/policyengine-app/pull/1081 (you can see linked PRs on the right)
