### ISSUE TITLE
Update default UK microsim year to 2024

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1084]
<img width="474" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/5b26562d-73d6-45c0-9b3d-10301fd43f07">

https://policyengine.org/uk/policy?focus=gov

**Comment by MaxGhenis** [comment]
This is from `TimePeriodSelector` which AFAICT gets time periods from metadata in the country package. For instance it's sorted differently between the US and UK.

@nikhilwoodruff does this come from here? https://github.com/PolicyEngine/policyengine-uk/blob/d7141ad4c7e30e97e0d13bf4b7d4b306d87381a0/policyengine_uk/data/datasets/frs/enhanced_frs.py#L113-L114

**Comment by nikhilwoodruff** [comment]
It's actually the first year defined in the country metadata

**Comment by anth-volk** [comment]
As a heads-up, I’ll be tackling this today after some edits on the policy calculator impact breakdown page (#35).
