### ISSUE TITLE
Policy calculator fails to run properly

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1087]
There's a breaking bug on the front end. When I created a policy reform by raising IRS income tax bracket 5 from its current value to 70%, then pressed the button to calculate the budgetary impact of the change, I received a white screen. The console outputs a series of logs. The logs, as well as the bug itself, is visible in the Loom video [here](https://www.loom.com/share/847daa8b323146d4adc5549d98fad9e0). When running the app in debug, I receive the following console outputs:

```
Uncaught TypeError: Intl.Segmenter is not a constructor
    stringWidth index.js:25
    wordLengths index.js:22
    wordLengths index.js:22
    exec index.js:112
    wrapAnsi index.js:216
    wrapAnsi index.js:216
    absoluteChangeMessage ImpactChart.jsx:97
    hoverMessage BudgetaryImpact.jsx:31
    customdata BudgetaryImpact.jsx:69
    ImpactPlot BudgetaryImpact.jsx:69
    React 12
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
index.js:25
```

```
The above error occurred in the <ImpactPlot> component:

ImpactPlot@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:7663:7
div
MemoizedChildren@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:1703:7
HoverCard@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:1611:7
Screenshottable@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:3471:7
div
_c
ImpactChart@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:9517:7
div
div
./src/layout/ResultsPanel.jsx/_c<@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:3345:73
LowLevelDisplay@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:8915:7
DisplayImpact@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:8827:7
FetchAndDisplayImpact@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:9238:108
PolicyOutput@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:10700:7
div
div
ThreeColumnPage@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:3727:7
PolicyPage@http://localhost:3000/static/js/src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.chunk.js:5086:7
Suspense
RenderedRoute@http://localhost:3000/static/js/bundle.js:344211:7
Routes@http://localhost:3000/static/js/bundle.js:344831:7
PolicyEngine@http://localhost:3000/static/js/bundle.js:11882:22
Router@http://localhost:3000/static/js/bundle.js:344773:7
BrowserRouter@http://localhost:3000/static/js/bundle.js:342822:7

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. policy:13024:25
```

**Comment by MaxGhenis** [comment]
Huh, those steps work for me: https://www.loom.com/share/870512e32cb742f78efa6fb3cc2bae76

Does this link work for you? https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=43398&region=us&timePeriod=2024&baseline=2

**Comment by anth-volk** [comment]
Weirdly enough, yes, the link works on mobile for me. I’ll check on desktop when I’m back at it.

**Comment by anth-volk** [comment]
That said, the link does not work on desktop for me.

**Comment by anth-volk** [comment]
Okay, figured out the issue: the `wrap-ansi` package utilized in all policy calculator output charts employs a built-in browser object called `Intl.Segmenter()` to determine word length. However, this is not supported in Firefox, which is why I could pull the page using mobile (Safari) but not on my desktop, where I use Firefox. Considering that the application currently fails for an entire segment of browser users, I think the best course of action is to replace `wrap-ansi` with something more universally supported.

**Comment by abhcs** [comment]
`Intl.Segmenter` is supported on Firefox prerelease. [wordwrap](https://www.npmjs.com/package/wordwrapjs) is a potential replacement. There may be better packages around. I chose `wrap-ansi` because it was already there in node, and because the solution worked on the browsers I use frequently.

**Comment by anth-volk** [comment]
PR #1094 is to replace `wrap-ansi` with `wordwrapjs`, the package you linked above. I completely understand your choice of packages there, but since the majority of Firefox users probably aren't on a pre-release version (even I only use it for testing purposes sometimes), I think it's best to at least switch packages temporarily, until it's standard in Firefox.

**Comment by abhcs** [comment]
https://policyengine.org/us/policy?focus=policyOutput.intraDecileImpact&reform=43398&region=us&timePeriod=2024&baseline=2

Bug is alive on firefox because `wrap-ansi` is not replaced everywhere. Fix in progress.

**Comment by anth-volk** [comment]
Thanks @abhcs, I clearly missed some uses of the package in my haste last night.
