### ISSUE TITLE
Separate region from dataset for selecting the Enhanced CPS

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1088]
Currently we use the CPS for the US, states, DC, and NYC microsims. We also offer the enhanced CPS for US only. It's listed as another region. I'm not sure how we might ultimately want to represent this on the backend, but we should be able to abstract that away with some frontend changes that avoid enhanced CPS showing up like a region, e.g. a dataset drop-down that then limits the user to the US region if they select enhanced CPS. Let's also describe it as experimental.

<img width="1400" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/83f540c7-28ee-4fe5-b910-424356d3fea6">

**Comment by anth-volk** [comment]
I'll work up something on this over the next few days
