### ISSUE TITLE
Move labor supply chart to the bottom

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1089]

**Comment by dotslashbit** [comment]
Just for clarification:
<img width="1710" alt="Screenshot 2024-01-04 at 9 08 58 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/d6c19d9e-53c6-4cd9-aca5-62d39f5e9800">
You want the Labor supply impact link to be below the analysis link?
