### ISSUE TITLE
Describe labor supply chart as experimental

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1090]

**Comment by dotslashbit** [comment]
Clarifying question: 
1. You want to display a text that expresses that labor supply chart is experimental or something else?
2. Where do you want to put that text?
<img width="1710" alt="Screenshot 2024-01-05 at 12 10 19 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/39c0322a-c04a-4a76-8dff-3ead2dab1d5c">

**Comment by MaxGhenis** [comment]
In the left panel with the link, `Labor supply (experimental)`

Also `Analysis (experimental)` while in there
