### ISSUE TITLE
Clarify that deciles are based on baseline net income

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1091]
We currently say this below decile charts, e.g.: https://policyengine.org/us/policy?reform=43155&focus=policyOutput.decileRelativeImpact&region=enhanced_us&timePeriod=2024&baseline=2

>Households are sorted into ten equally-populated groups according to their equivalised household net income.

Let's add `baseline` before equivalised.

**Comment by abhcs** [comment]
1. In the `Absolute impact by wealth decile` chart, the description says:

> ...are sorted into ten equally-populated groups according to their baseline equivalised household net income.

Should this say `net wealth`?

2. In the `Outcomes by wealth decile chart` the description is longer:

> ...are sorted into ten equally-populated groups according to their baseline equivalised household net wealth (including property and corporate holdings).

Should all wealth charts end with this longer phrase?

3. Do you want baseline before equivalised for wealth charts?

Suggestion: Given that the descriptions for all of these charts are so similar, I can't help but think that all of these charts should be displayed on the same page with more guidance for the user on how to interpret the charts.

**Comment by MaxGhenis** [comment]
1. yes
2. yes but we can remove "(including property and corporate holdings)"
3. yes
4. we can remove this sentence from all charts, including e.g. poverty charts saying "The chart above shows the relative change in the deep poverty rate for each sex." (if we use that space for anything we should state less obvious things like that we use the Supplemental Poverty Measure, deep poverty = below half the threshold, etc.)

agree on having one page, the user could select options like relative/absolute income/wealth, also providing more flexibility to break down by other characteristics in the future

**Comment by abhcs** [comment]
On point 4, if you can construct better descriptions for the charts that define jargon or point to your blog pages or Wikipedia pages, I am happy to add those descriptions.

**Comment by MaxGhenis** [comment]
US poverty:
>PolicyEngine reports the impact to the [Supplemental Poverty Measure](https://www.census.gov/topics/income-poverty/supplemental-poverty-measure.html).

UK poverty:
>PolicyEngine reports the impact to absolute poverty before housing costs.

Deep poverty (additional sentence for US and UK):
>Deep poverty is population share with resources below half the poverty line.

Inequality:
>PolicyEngine reports income inequality based on the distribution of net income, after taxes and transfers.
