### ISSUE TITLE
Buttons without words on them should not allow highlighting

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1109]
For example, the arrow buttons on `BottomCarousel` (the component at the bottom of the screen when you calculate a household) allows the user to highlight the arrows themselves; this shouldn't be the case.

**Comment by anth-volk** [comment]
A video of the issue is available [here](https://www.loom.com/share/74b796b399d741978a73e4ba10a38059?sid=01c57e7d-daca-46ba-bca2-ec42f3030fda). It's the way that I can physically highlight an arrow on the button itself - ideally, that wouldn't be possible.

**Comment by dotslashbit** [comment]
Ok, got it, I'll take a look and open another PR

**Comment by dotslashbit** [comment]
@anth-volk So, you want that sliding hover effect and just want to remove the blue highlighting that your mouse is doing right?

**Comment by dotslashbit** [comment]
@anth-volk I noticed that buttons that contain text also getting the blue highlight, should I work on that to remove it or we should keep it that way.
Generally, we can't highlight the text on any buttons, that's why I thought I should ask you first before creating a issue on this

**Comment by anth-volk** [comment]
Good point, could you open a new issue for it?
