### ISSUE TITLE
The .vscode folder is an unnecessary restriction on developers

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1118]
It contains the setting "search.useIgnoreFiles": true which ensures that search ignores the files that git ignores.

However, I want to save many other settings in my workspace, e.g.,

~~~js
"search.useIgnoreFiles": true,
"prettier.configPath": ".prettierrc.json",
"prettier.ignorePath": ".prettierignore",
"prettier.requireConfig": true,
"prettier.useEditorConfig": false,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
~~~

This is not possible at the moment because we are all sharing the vscode folder. I have to save these settings at the user level in vscode, which is not ideal. Please see the discussion on [StackOverflow](https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control) on this topic.

Proposed solution: Delete the .vscode folder giving developers control over their workspace.

**Comment by gautamjuyal** [comment]
I propose we should also add `.vscode` folder in`.gitignore` file, that way we can prevent the folder getting pushed to the repo in future.

**Comment by dotslashbit** [comment]
I think, generally we keep .vscode in .gitignore right?

**Comment by gautamjuyal** [comment]
I think so too. Can I work on the issue?

**Comment by anth-volk** [comment]
I am shocked that we overlooked adding this to .gitignore. Sure, @gautamjuyal, we'd love your contribution on this!
