### ISSUE TITLE
Household questionnaire doesn't ask for head age when multiple members

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1129]
See this video: first scenario works (single no kids), all others drop the head when asking for age

https://www.loom.com/share/b0051eea508b4c5296e0cd4c09779fc3

**Comment by anth-volk** [comment]
Will prioritize today

**Comment by abhcs** [comment]
Broke in https://github.com/PolicyEngine/policyengine-app/commit/66d4eb05a145fa8240ced88579f1c0e3b02b5e03. I can fix it.

**Comment by anth-volk** [comment]
Go figure, wouldn't have expected linting updates to do it. Sure, @abhcs, you'll definitely be more knowledgeable about the root cause. If you can't finish during your day today, please let me know, and I'll pick up where you leave off, as this is high-priority.

**Comment by abhcs** [comment]
I can easily fix it by ignoring the error on the line (like we do for many `useEffects`) but I will take a little time to figure out why my previous solution didn't work.

**Comment by anth-volk** [comment]
Okay, so long as you can re-enable, then sure, please feel free to dig into the weirdness that is `useEffect`. When you're finished, if you could request Max's review, as I'm sure he's eager to push as soon as possible.

**Comment by anth-volk** [comment]
As an update, since today’s presentation’s over, feel free to request my review instead
