### ISSUE TITLE
Geography variables in household variable editor don't work

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1131]
In any [household](https://policyengine.org/us/household?focus=householdOutput.netIncome&household=38497), click on `Geography` to see blank tabs:

<img width="711" alt="Screenshot 2024-01-08 at 5 05 24 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/d06f14f9-6dee-4e81-8397-42d604bdc829">

Now, click on `state_fips` on the left pane to see PolicyEngine crash.

Expected: Tabs should contain text and variable editor should not crash.

**Comment by anth-volk** [comment]
As a note, there is definitely another issue somewhere that mirrors this one; unsure if it's open or closed

**Comment by abhcs** [comment]
#607 but the problem is still there.

**Comment by anth-volk** [comment]
Wow, unsure why that was closed

**Comment by anth-volk** [comment]
Looking at the prior issue, it appears that the fix lies within `policyengine-us`. Would you be willing to open an issue there and comment here for future reference?

**Comment by abhcs** [comment]
Closing due to completion of #3569.

<img width="1240" alt="Screenshot 2024-02-10 at 2 15 55 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/3ee35698-4c0f-48b0-92b4-a72ef12dfe67">
