### ISSUE TITLE
`addVariable` does not add the default state CA to the household

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1132]
Issue #1057 was closed through PR #1061 by adding using `variable.defaultValue` in the `HouseholdVariableEntityInput` component. However, this fix seems redundant because `addVariable` is responsible for adding variables (including `state_name`) with default values to all entities. `addVariable` ignores the default value for `state_name` because on [line 353](https://github.com/PolicyEngine/policyengine-app/blob/d6181d2676f995fe6e9c20d2c6a83195afd2a4e2/src/pages/household/input/VariableEditor.jsx#L353) it finds that `state_name` is *not* an input variable and uses the default value null.

Why is `state_name` not an input variable? Is the notion of input and non-input variables important? The fix for #1057 should be revisited with these questions in mind.

**Comment by anth-volk** [comment]
@nikhilwoodruff Do we know why `state_name` isn't an input variable? I'm as surprised as Abhishek.
