### ISSUE TITLE
`VariableEditor` infinitely re-renders

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1133]
Probably effect of #1081. If adding a line to console log right before component return, the fact that the component re-renders infinitely is visible.

**Comment by abhcs** [comment]
#1130 did not work properly. Add `console.log` inside the effect to check. I will need to check the condition again.

**Comment by abhcs** [comment]
The condition should be `possibleEntities.length !==
      Object.keys(householdInput[entityPlural]).length`. `Object.keys` is missing in #1130.

**Comment by anth-volk** [comment]
Shoot, I was just about to link my own PR that did the same thing. Well, yours is certainly approved.

**Comment by abhcs** [comment]
Hopefully, third time's the charm on this use of `useEffect` :)
