### ISSUE TITLE
Simulations with the Enhanced CPS in 2021 never complete

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1153]
I'm guessing this is because we only have a release for the 2023 Enhanced CPS, which is based on the 2022 CPS. 2024 works.

Example: https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=44066&region=enhanced_us&timePeriod=2021&baseline=2

**Comment by anth-volk** [comment]
Will fix as a part of #1150 moving forward
