### ISSUE TITLE
Hide featured story from adjacent list of stories

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1158]
We're repeating the main highlight

<img width="1107" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/597cab48-a381-4e12-8597-992775388dc3">

**Comment by abhcs** [comment]
Reopening since I reverted the fix in #1288. Please note that the next fix must be tested on desktop, tablet, and mobile platforms to avoid errors such as #1286.
