### ISSUE TITLE
Don't show an error message when selecting outputs without a reform specified

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#116]
In this case we can just say something like `Define a policy to see outputs`
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/6076111/209755804-40b908a5-9099-4d8e-b144-46df2a023da3.png">

**Comment by Felix-Cadiz** [comment]
I think this ticket has been fixed already been fixed:

<img width="1301" alt="Screen Shot 2023-03-03 at 8 04 42 AM" src="https://user-images.githubusercontent.com/88756231/222772552-f0fbe123-aca0-48ac-9206-b4c0887f223a.png">
