### ISSUE TITLE
No share image for Wyden-Smith blog post

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1164]
For any of the social networks

https://policyengine.org/us/research/wyden-smith-ctc

https://socialsharepreview.com/?url=https://policyengine.org/us/research/wyden-smith-ctc

**Comment by anth-volk** [comment]
@dotslashbit Would you be willing to prioritize this issue? If not, no problem.

**Comment by dotslashbit** [comment]
Sure I'll look into it

**Comment by dotslashbit** [comment]
I tried to solve this issue but everything looks good to me but the issue still persists, I checked the social share url for this post and some past posts and all of them looks consistent, the Post.jsx file has no issues, the Desktop sharelink onClick prop is working fine too.

**Comment by anth-volk** [comment]
Thanks @dotslashbit, that's a shame to hear. I think I have a longer-term solution for this; opening a PR.
