### ISSUE TITLE
Every time a user creates a new policy name, at least 2 policies are created

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1165]
In the policy calculator, if you try creating a unique policy, then changing its name, it won't be readily apparent, but at least two policies will be created and sent to the back end. For example, I created US policy 44150 with the name "Test Policy" and an increased IRS tax bracket 4 percentage value of 49.2%. Policies 44151, 44152, 44153, and 44154 all contain the exact same information. This is likely driven by some sort of poorly synced effect on the front end that's repeatedly creating all of these.

**Comment by dotslashbit** [comment]
@anth-volk Whenever you can, please share a video walk through on how to create a reform as I couldn't figure that out, thanks

**Comment by anth-volk** [comment]
@dotslashbit [Here](https://www.loom.com/share/288cf278b7974f0ba2e239e96fd1a307?sid=d55c5908-d5b7-46b7-a78b-7549409cf82f)'s a video demonstrating it. It is very unintuitive, I must admit.

**Comment by dotslashbit** [comment]
@anth-volk How can I check while resolving this issue that my solution is working or not? Do I have to run the backend too? If yes, then please guide me on how to do that. I have figured out how to run the API and its running, but couldn't figure out if I need that API to check my solution or not

**Comment by anth-volk** [comment]
Currently, our test front end actually emits to our live back end - probably not the best, I know. That said, it makes testing quite easy, as you can just query the live back end to see what records have been created and if they match. They're typically sequential, as well. If you have more questions about the back end, feel free to ask.

**Comment by anth-volk** [comment]
It appears writing "this does not yet fix [issue]" closes the issue haha. Reopening.

**Comment by anth-volk** [comment]
After the API improvements, this now only occurs when a user first creates a custom name, meaning it probably originates from an error within an effect hook or a series of chained async policy calls within the app.

**Comment by anth-volk** [comment]
The remaining cause of this problem is now almost certainly the right-hand sidebar input field. If a user creates a new name, whether it's the first new name or the third, if they press the Enter key to confirm the name, two records are created, whereas if they click off (causing a blur event to occur), only one is created, the intended behavior. 

My assumption would be that pressing Enter causes both an Enter keydown event and a separate blur event, causing nearly simultaneous API calls. Recent API improvements, which were aimed at preventing this situation by checking if a record with the label already exists and merely passing a 200 in that case, fail because the nearly simultaneous blur and keydown events enqueue two record creation calls so close together that the first one hasn't completed by the time the second one starts.
