### ISSUE TITLE
When a user edits policy parameters then names the policy, multiple policies are created

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1166]
This is related to #1165 and #972. Per @patrickhanl, it would appear that whenever a user edits policy parameters for a policy they've created, then names the policy, multiple corresponding back-end policies are created. Ideally this should not occur.

**Comment by MaxGhenis** [comment]
This is about policies not households right?

**Comment by anth-volk** [comment]
Now corrected
