### ISSUE TITLE
When a user edits a named policy to create a new name, the app breaks

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1167]
For example, after creating a policy, I input a name, then clicked off, saving said name. Afterward, I attempted to edit the name, clicked off again, and when I tried to return to the home page, the application threw a runtime error about "t" not being a function and displayed nothing, even when attempting to reload the page.

**Comment by dotslashbit** [comment]
can you please share a video of this

**Comment by anth-volk** [comment]
I might not be able to until late tonight or tomorrow, but sure, it is a weird bug

**Comment by dotslashbit** [comment]
No rush, but whenever you can, please share a video as it would help me a lot, thanks

**Comment by anth-volk** [comment]
This actually might only be in debug mode. It appears that when I do the same on the production app, the app simply does nothing, meaning the name is never changed.

Honestly, the entire naming structure might just need refactoring/rewriting to make the whole thing more logical, if that's the root of the problem.

Here's a video of the behavior: https://www.loom.com/share/0c7de4b80ec44935b888b05c3eec3724?sid=7e6d4fb3-75e6-41c2-8330-1bdf40385c1d

**Comment by anth-volk** [comment]
This may be the same as #1202; if we don't see this again, probably should close

**Comment by anth-volk** [comment]
Still have not seen this reappear. Appears to have been fixed by #1328. Closing.
