### ISSUE TITLE
Multiple Warnings on BlogPage Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.

### ISSUE THREAD

**Issue by dotslashbit** [PolicyEngine/policyengine-app#1168]
<img width="1710" alt="Screenshot 2024-01-12 at 8 15 35 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/41672dc8-e919-4348-a2b0-30df716417e0">

**Comment by dotslashbit** [comment]
I would like to solve these issues, please just confirm that I'm not the only one getting these warnings

**Comment by anth-volk** [comment]
I'm actually not getting these messages at the moment. Could you try again to confirm that you're still getting them?

**Comment by dotslashbit** [comment]
yes, I'm still getting those errors

https://github.com/PolicyEngine/policyengine-app/assets/46224156/56d29ab8-ea52-4fe0-bad2-b321aebad392

**Comment by anth-volk** [comment]
Okay, I do see that now. Yes, please feel free to tackle this one @dotslashbit.
