### ISSUE TITLE
Buttons that contain text getting Blue Highlight

### ISSUE THREAD

**Issue by dotslashbit** [PolicyEngine/policyengine-app#1184]
If you drag your mouse on the text of any button, you'll see the blue highlight

**Comment by dotslashbit** [comment]
@anth-volk please confirm this and I would love to work on this as I have previously solved #1109

**Comment by anth-volk** [comment]
Definitely an issue, would love your contributions on this. That said, can you add an `aria-label` equal to the display text, as well, if one doesn’t already exist? Until we redo these as actual semantic `button`s, that should at least help a bit with accessibility. It’s a bit of an expansion of the purview of this issue.

**Comment by anth-volk** [comment]
It may be overkill, but why not, you know?

**Comment by dotslashbit** [comment]
ok sure, will do that
