### ISSUE TITLE
`Labor supply impact (experimental)` is positioned after `Reproduce in Python` and `Analysis` in policy reform calculator output pages

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1203]
@MaxGhenis Is this intended behavior? It seems strange to have `Reproduce in Python` and `Analysis` positioned before the labor supply impact outputs

**Comment by dotslashbit** [comment]
#1089 In this issue Max asked to do this and I did that PR

**Comment by anth-volk** [comment]
Huh, I stand corrected. Thanks @dotslashbit, closing.

**Comment by MaxGhenis** [comment]
I asked to move labor supply to the bottom (it was previously at the top), but taking a step back Anthony you're right. Let's make these the last items:
* Labor supply impact (experimental)
* AI summary (experimental) [rename Analysis]
* Reproduce in Python

**Comment by anth-volk** [comment]
@dotslashbit Do you want to take this on at all? If not, I'm happy to, but I'll leave it open to you first since you raised the first comment.

**Comment by dotslashbit** [comment]
I'll take it
