### ISSUE TITLE
Allow calculating 2025 taxes in the US household app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1208]
This is relevant to the CTC reform conversation

**Comment by anth-volk** [comment]
Is this as simple as adding 2025 as an option within the metadata? Or is there a need for anything special on the API and/or app packages? Happy to help, but also happy to leave it to Pavel or someone else who is already working on the US package if there's nothing needed elsewhere.

**Comment by anth-volk** [comment]
Working on this currently. Successfully completing will first require solving API [#1097](https://github.com/PolicyEngine/policyengine-api/issues/1097).

**Comment by anth-volk** [comment]
Based on the Loom video [here](https://www.loom.com/share/9f64dd1b71484a13afcfcaf52f6e5067?sid=5328c658-4b1f-4523-8e04-7744cb66af53), I think that this is complete to the point of working as well as the app did previously. However, I'd also be happy to change the titles of the output pages (e.g., `Your net income is $X` -> `Your net income would be $X`) within this issue, then open a PR.

**Comment by MaxGhenis** [comment]
Confirmed this works!

Looks like you already made some progress on the tenses but for some edge cases we might want some new issues 🥴 

<img width="758" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/e9848769-eec7-4e12-b86f-7f7e42c027df">

https://policyengine.org/us/household?focus=household.income.person.employment_income_last_year.employment_income_last_year&reform=44823&region=us&timePeriod=2025&baseline=2&household=40241

**Comment by anth-volk** [comment]
Oh, we're not shooting for the Back to the Future theme in the app?

**Comment by MaxGhenis** [comment]
(Seriously though I wouldn't invest much in the last-year variables. We want to leverage the panel nature of policyengine-core to do that in the future)
