### ISSUE TITLE
Parameters default to adjusted value in separate previously adjusted parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1212]
Steps to reproduce:
1. Adjust a parameter
2. Navigate directly to another numeric parameter

Expected behavior: New parameter shows the current value

Observed behavior: New parameter shows the value the previous parameter was adjusted to

Navigating to a parameter "folder" resets this, preventing the issue

https://www.loom.com/share/b7c2d723084647a69d634f00453e1ba8

**Comment by anth-volk** [comment]
To tack onto this, the right sidebar also doesn't switch to displaying the current parameter, which seems like the preferred behavior?

**Comment by anth-volk** [comment]
I'll open the sidebar switching to the current parameter as a separate issue, actually
