### ISSUE TITLE
`VariableEditor` shouldn't autofocus all inputs

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1234]
At present, the `VariableEditor` component applies the `autofocus` prop to all individual input fields  - for a married couple with five dependents, this means 7. As each is rendered, it pulls the focus from the prior to itself, causing the `onBlur` handler to fire, enqueuing an API call for families that are being edited, meaning as many as 6 POST requests to the household endpoint occur for large families. This should be disabled, and instead, only the head of household's input should be focused on.

**Comment by abhcs** [comment]
Related to #1171 which says that autofocus should not be used at all.
