### ISSUE TITLE
Parameter history chart bug with multiple changes across periods

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1238]
For example for the Wyden-Smith CTC reform: https://policyengine.org/us/policy?reform=44823&focus=gov.irs.credits.ctc.refundable.individual_max&region=us&timePeriod=2024&baseline=2

<img width="844" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/747609e1-d3c7-4967-b30b-abb310421cad">

**Comment by anth-volk** [comment]
That is incredible

**Comment by abhcs** [comment]
I can take a look at this since I have modified the history function before.
