### ISSUE TITLE
Place `Current law` before `Reform` in policy parameter legend

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1241]
Would be more natural imo

![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/238cf883-ddd7-44ef-aedb-80a9b64333cc)

**Comment by MaxGhenis** [comment]
I was initially thinking just words, but it's a good point. If we put the reform line on top, the gray won't be visible though. Instead how about making Current law solid gray, and Reform dashed blue?

**Comment by abhcs** [comment]
> If we put the reform line on top, the gray won't be visible though

That is the problem I have introduced in #1252 inadvertently. I will fix the PR to only modify the order of the legends. The lines will look like they do on the website right now.

**Comment by anth-volk** [comment]
I have to wonder if making reform dashed might take away from the "umph" of the chart, if that makes sense. I'm glad we're addressing this, though, as #1252 does place the reform line on top.

Otherwise, is there a way to merely move the tag and not change the order of the lines? And is that too...finicky?

**Comment by abhcs** [comment]
> is there a way to merely move the tag and not change the order of the lines?

yes, legend order can be specified separately. I will add that change to the PR.

**Comment by MaxGhenis** [comment]
Filed https://github.com/PolicyEngine/policyengine-app/issues/1262 for changing the chart dashing / order. I think dashing better conveys the hypothetical nature of the reform, but open to keeping as is depending on how it looks.
