### ISSUE TITLE
State year in chart titles

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1243]
All charts omit the year from the title, e.g. [this](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=46315&region=enhanced_us&timePeriod=2025&baseline=2)
<img width="1415" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/48411536-acdd-4758-a95f-7b47dd6407f1">

The labor supply one says "this year", regardless of the year
<img width="1389" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/df60fe4c-5692-4eb4-b825-ec87e705faba">

Let's add `in {year}` to the end of each chart title

**Comment by anth-volk** [comment]
To confirm, is this still the desired behavior?

**Comment by MaxGhenis** [comment]
This issue remains outstanding, yes

**Comment by czhou578** [comment]
Can I be assigned to this issue?
