### ISSUE TITLE
Within the calculator portions of the app, links are often displayed as standard text

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1246]
For example, on the `Reproduce in Python` page shown in the image below, the text "Python notebook" is actually a link, but it's not displayed as such. This should definitely be obvious, and my theory would be that we should either use the browser's standard highlighting (which isn't far off from our color scheme, anyway) or define a clear theme to handle this.

<img width="695" alt="Screen Shot 2024-01-22 at 2 31 35 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/21ad8b4c-6912-4787-9b71-e083389bfd38">

**Comment by anth-volk** [comment]
@dotslashbit There isn't a specific design at the moment. Preliminarily, can you default to using the style we use in our blog articles, but remove the hover effect and add an underline to it? And if the fonts aren't the same, of course, please use the one we use by default in the calculator.

**Comment by abhcs** [comment]
Probably due to:

https://github.com/PolicyEngine/policyengine-app/blob/918030a1f5a2add45840f5a31fd9af3c5671eebb/src/style/App.css#L22

**Comment by anth-volk** [comment]
Certainly a strange choice...
