### ISSUE TITLE
There's no confirmation/success message after clicking `COPY` on `Reproduce in Python`

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1247]
On the `Reproduce in Python` page of the policy calculator, there's no message indicating that you've successfully copied the text to the clipboard, making it feel as if the button has done nothing. Some sort of message should be displayed here so as to improve the UX.

**Comment by MaxGhenis** [comment]
I like the ChatGPT UX for copying code, can we adopt that?

https://www.loom.com/share/c665ddf13ba349ca848b0300f0a63069
