### ISSUE TITLE
Copy Button still exists At the Bottom of the reproduce python code block

### ISSUE THREAD

**Issue by dotslashbit** [PolicyEngine/policyengine-app#1254]
https://github.com/PolicyEngine/policyengine-app/assets/46224156/8cb2642a-d4eb-4b5b-9d1f-626ff6e57e95

I have recently worked on adding a copy button on the top right corner of the codeblock and its working for both household and policy and after that I removed the copy button from `PolicyReproducibility.jsx` file. But this only removed the button from `policy` page and not in the household page.

**Comment by dotslashbit** [comment]
I would love to work on it, but please explain does the text placement in the end "Run the code below into a Python notebook to reproduce the microsimulation results." is correct?

**Comment by MaxGhenis** [comment]
I think we should remove the notebook note. Let's keep it clean and potentially move toward https://github.com/PolicyEngine/policyengine-app/issues/263

**Comment by MaxGhenis** [comment]
Actually saw the notebook prepopulates some helpful info so we can keep it. Just remove `microsimulation` from the household snippet (or both household and microsim if easier) and change `into` to `to`.
