### ISSUE TITLE
Add vertical space between paragraphs

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1255]
For example these bleed together (new paragraph starts at `From 2023`). From https://policyengine.org/us/research/wyden-smith-ctc

<img width="778" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/353532fd-5575-41e1-ae0b-e1e017386409">

**Comment by Sanchitbajaj02** [comment]
Hi @MaxGhenis 
> these bleed together

What do you mean by bleed? Are you referring that there not enough spacing between the paragraphs?
