### ISSUE TITLE
Feature request: yearly parameters should have yearly inputs instead of single date-driven ones

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1261]
As I use the parameter editor, I'm struck by how many of the parameters we're editing take place over an entire fiscal year, but require the user to input data for individual dates. Furthermore, the individual date input is incredibly finicky due to the inherent challenge of what to do with the interval between Dec. 31st of given year X and Jan. 1st of given year X+1. Moving forward, I think it'd be great to have an input where the user chooses a year or series of years for these yearly parameters to occur over, removing the Dec. 31st/Jan. 1st guesswork, removing possible misinterpretation of the data (what if I decide to input May 1st, even though that's not a "valid" input from a legislative standpoint?), and just making it far easier to select years (no need to click 3-4 times to select start and end dates). Furthermore, we could limit the selectable years to the years the variable is calculated over.

**Comment by MaxGhenis** [comment]
Just saw this - see my https://github.com/PolicyEngine/policyengine-app/pull/1252#issuecomment-1906489037 for some background here

I think we'd need to add metadata to parameters to make this work. In particular, US tax parameters operate over calendar years, so if we flag those as such we can replace the date picker with a year picker. Other parameters generally require more flexibility.

**Comment by anth-volk** [comment]
Just left a response in #1252, as well. As long as we do something to obscure away the fact that yearly policies often end at the exact last moment of their respective years, then new policies begin at the exact first moment of their respective years, I think it'd be beneficial

**Comment by MaxGhenis** [comment]
Agreed. And I think in ~95% of cases, users don't specify an end date and just want a change indefinitely. So starting with "from the beginning of the current year moving forward" at least for US tax parameters (currently the most used parameter type) and hiding the rest behind an expandable menu would simplify considerably.

**Comment by anth-volk** [comment]
I worked up three rough ideas as to how this could be implemented. These are non-functional and lacking some polish, but I think they help to illustrate the general UX considerations we could highlight.

The first is the least invasive: simply keep the default date as 2024-01-01, then have the end date box say something like "Forever" (though I imagine there's a better wording here). While this would likely be easy to implement, it does little to address some of the challenges a user trying to input particular dates might face.
<img width="1440" alt="Screen Shot 2024-02-06 at 5 40 21 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/6bf29c6e-1f04-403d-8f3e-3d4e8f8ea370">

The second is my least favorite of the three, but it creates two radio buttons: one that is the default option most users would likely use, and the second that contains our current selector for more advanced input. On the default option, the year would change depending on the year the user has selected to simulate over. This also doesn't do too much to improve the experience for a user trying to input particular dates, but also just doesn't...look quite right, in my opinion.
https://github.com/PolicyEngine/policyengine-app/assets/14987227/56338aff-fee2-4872-98f1-6e0807ef86d3

The third is a hybrid, whereby we convert our current date pickers into year selectors. The starting year would default to the year the user selected to simulate over, while the end would default to, again, something like "Forever", and we would merely interpolate the latest date possible based on the variable. That said, we'd enable the possibility of selecting advanced dates with a dropdown, which is currently labeled as "Advanced" in the video below, but could even just be a downward carat button. I also didn't include it here, but this implementation would also probably include some sort of text indicating that the dates are fully inclusive, from Jan. 1 of start year to Dec. 31 of end year, perhaps by putting a label on top with something like "From start of:" and "to end of:" or something like that.
https://github.com/PolicyEngine/policyengine-app/assets/14987227/8129d41c-48e9-4920-9514-bd7459e305e5

These are just aimed at starting the conversation so we can finalize a design before implementation. Curious to hear everyone's thoughts.

**Comment by MaxGhenis** [comment]
Can we use this as an opportunity to center the parameter value? The date range is secondary to this, so we can instead draw the user to the value.

How about the big text box, and then `from 2024 on` either to the right or below, clickable to pull up a modal to set the start and end date?

**Comment by anth-volk** [comment]
If I'm understanding you correctly, the big text box refers to the value input; if so, definitely, will get to mocking that up

**Comment by anth-volk** [comment]
Here's what I have for a look so far - when hovered, the date portion becomes a visible button. I'm still working on wiring up a dropdown box with a date input editor, but I'm torn as to what this should look like, as I still think it'd be ideal if we had a system whereby a user could either select a series of full years, or activate a more advanced version where they input the actual date.

<img width="1440" alt="Screen Shot 2024-02-12 at 11 24 22 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/8c867cf2-8f85-4e8b-9472-3798acebb746">

**Comment by MaxGhenis** [comment]
All parameters currently apply their final value indefinitely to my knowledge, so this should be possible or maybe require a (simple I'm guessing) API update if not.

**Comment by anth-volk** [comment]
Looks like parameters do apply their final value indefinitely, but reforms are written as a series of [start, end] pairs that are pretty tightly coupled to the `IntervalMap` class, and tossing this (other than trashing a fine piece of engineering) would require rethinking how policy reforms are defined and stored. I'll have a think as to how to approach this problem.

This could be as simple as just having the default time selection option be "for 2024" instead of "for 2024 onward," and the user could add other years if desiring a longer reform, but since we calculate reforms over a year anyway, I envision no functionality loss

**Comment by anth-volk** [comment]
Talked with Nikhil about this, and it appears that policy modifications are not applied into perpetuity, and feels that our default should be 5 years on them. I could see either doing that or defaulting to applying it just over whatever year the user has selected in the right-hand sidebar to simulate over, since each of these options seems to me to produce the most logical UX.

**Comment by MaxGhenis** [comment]
Not a big deal but I'm surprised we can't apply reforms in perpetuity, given parameter files themselves apply the final value in perpetuity. @nikhilwoodruff can you say more? Should we file an issue to core for this?

If we do restrict it, we should do it at least 10 years out, as that's the US budget window.

**Comment by anth-volk** [comment]
I'm surprised that it wouldn't make more sense to merely extend the reform over the year being calculated - after all, a reform with a provision that runs from 2024 through 2028, inclusive, estimated over the year 2024, works out to the same result as one with a provision that's only live for 2024.

If we do want fixed windows longer than one year, one way to do this might be to have the default display indicate "from 2024 for X years," and this could default to a 10-year range (2024-2033) on the US app, but a 5-year range (2024-28) on the UK app, as I understand that the UK uses 5-year planning windows.

**Comment by nikhilwoodruff** [comment]
I think we should default always to fixed year time periods IMO

**Comment by MaxGhenis** [comment]
Why Nikhil? Most laws define parameters indefinitely, we should be able to capture them.

**Comment by nikhilwoodruff** [comment]
From a UI point of view everything is really closely tied to explicitly time-bound reform components. Adding 'infinity' in several places is doable but seems like it'd be really clunky without proper thought

**Comment by MaxGhenis** [comment]
What other than the date picker do we tie to time-bound reform components?

I'd suggest we replace the date picker with a simple `2024 on: [value]` and then a [Collapse](https://ant.design/components/collapse) for the advanced feature of setting the specific beginning and end date. This aligns with the standard user journey of changing the value from the current year indefinitely (at least on the US side this is by far the most common), and strips away the clutter of lesser-used details.

**Comment by anth-volk** [comment]
I agree. That's roughly what's mocked up on the last image in this conversation, albeit using a [Popover](https://ant.design/components/popover), as the Collapse component typically takes up 100% of the width of its container; even so, anyway it'd be done is more of an implementation detail than anything, I think.

That said, the application's implementation of reforms is tightly coupled to (start, end) date pairs. These are stored as a string in our data objects, delineated similarly to the below example:
````
2014-01-01.2014-12-31: value
````
The challenge is that the entire system assumes this format, and while it could be ripped out and replaced, it would require an overhaul of some of the more fundamental portions of the API and app.

To me, that leaves any of the following solutions, each with downsides:
* Overhaul the system: the most comprehensive, but the most potential for breaking something in the process, including existing user reforms, if not done carefully enough
* Set this component to some fixed period by default (1 year; 5 years for UK and 10 years for US; something else): the quickest, but also arbitrary and potentially strange for users not familiar with government budget estimate cycles
* Use some arbitrary year (e.g., 2100), and set that as a default end point for policy reforms, but show the user that they run "onward"; compromises, but if a user actually does set the endpoint to 2100, it could create visual oddities, plus it's a bit of a challenge to work with using plotly, as plotly tries to actually graph the thing to 2100, so it'd require a workaround

**Comment by MaxGhenis** [comment]
I see. Let's discuss the merit of overhauling in a separate issue. Not having knowledge of the inner workings, it seems advantageous for the API to mirror the country packages in not requiring an end date.

In the meantime can we go with the third option of a distant year, and separately limit the parameter graph to 10 years out?

**Comment by anth-volk** [comment]
Definitely, will try it out, likely next week due to this being a second-tier priority

**Comment by anth-volk** [comment]
As an update, I have made progress on this, but have faced quite a few challenges. I'm hoping to have a working prototype this week in order to elicit cosmetic feedback, then write tests later this week and open a full PR.
