### ISSUE TITLE
Change dashing and order of current law / reform parameter lines

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1262]
| Attribute | Current | Requested |
| - | - | - |
| Current law line| Dashed | Solid |
| Reform line | Solid | Dashed |
| Top line | Current law | Reform |

<img width="883" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/127e684e-794f-4a1b-a481-78fa138e616c">

**Comment by anth-volk** [comment]
@abhcs Considering the relevance to #1252, would you mind also incorporating this and sharing an image within #1252 of how this ends up looking? Could also be done separately if you view it as too much within one PR.

**Comment by anth-volk** [comment]
From running Abhishek's code in #1252, this is what the editor ends up looking like. What are your thoughts @MaxGhenis? 

<img width="659" alt="Screen Shot 2024-01-24 at 3 23 32 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/81580007-aebb-40aa-83a5-9508d4f1633b">

**Comment by MaxGhenis** [comment]
Thanks, I think this better captures how the reform hypothetically follows the baseline policy.

**Comment by anth-volk** [comment]
Sounds good!
