### ISSUE TITLE
The input field in the policy calculator is inaccessible

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1275]
Take [this example](https://policyengine.org/us/policy?focus=gov.irs.income.bracket.rates.2). Type `13` in the field and press enter. The graph updates correctly, but the input field erroneously deletes the text to show a placeholder text `13%` instead. To edit the value to `13.5`, you must type `13.5` instead of appending `.5` to an existing `13`.

**Comment by anth-volk** [comment]
Note - this is related to #967, but a result of changes made in #1217
