### ISSUE TITLE
When a policy parameter is defined, its end date jumps forward a day

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1277]
I believe this was introduced in #1239? As a result of using an inclusive end date, the date setting within the policy parameter editor ends up being set forward one day, which is updated in the app. If you don't manually return the date, as you edit the parameter, it continues to move forward by one day.

**Comment by abhcs** [comment]
Is this issue fixed in #1252?

**Comment by anth-volk** [comment]
I'll be sure to test that when I look into the changes on #1252 later today.

**Comment by anth-volk** [comment]
Fixed in #1252. Closing.
