### ISSUE TITLE
API playground is blank

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1289]
https://policyengine.org/us/api

<img width="1140" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/4c410c56-9ab2-4009-98d6-fc77e90027da">

**Comment by MaxGhenis** [comment]
This happens when it goes to sleep: https://policyengine-policyengine-api-demo-app-xy5rgn.streamlit.app/

I just woke it. Is there a way to check if it's awake and point users to wake it back up?

**Comment by anth-volk** [comment]
Unfortunately, this was the reason we opened #1229, which @abhcs had hypothesized could be fixed with #1237, but it looks like it cannot. We'll have to dig more into the documentation to get a more permanent fix.

**Comment by abhcs** [comment]
Please don't wake up the app the next time it goes to sleep -- that's when we can try an alternate fix.

In #1237, I used the URL

`https://policyengine-policyengine-api-demo-app-xy5rgn.streamlit.app/~/+/?embed=true&embed_options=light_theme&mode=${countryId}`

but streamlit [recommends](https://docs.streamlit.io/streamlit-community-cloud/share-your-app/embed-your-app):

`https://policyengine-policyengine-api-demo-app-xy5rgn.streamlit.app/?embed=true&embed_options=light_theme&mode=${countryId}`

Unfortunately, on using the recommended URL, I get a footer:

<img width="1189" alt="Screenshot 2024-01-29 at 7 11 37 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/50a32cec-f4da-44ca-9688-0a97ca6243ab">

This is why I used the URL with the `+/~` segment in #1237. This is the last URL fix that I want to try on a sleeping page.

**Comment by anth-volk** [comment]
I'm happy to work on this, I just need Streamlit access to do so
