### ISSUE TITLE
In `InputField`, enter events sometimes fire twice

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1292]
In the `InputField` component, an `Enter` event fires twice, with my guess as to why being that they also emit a `blur` event when the input item becomes unfocused. This is most important for the `PolicyNamer` component on the policy editor's right-hand sidebar, where it calls two POST requests to create or update a household.

**Comment by abhcs** [comment]
Have you tried not passing an `onBlur`? For instance, I don't pass it in `ParameterEditor`.

**Comment by anth-volk** [comment]
Apologies, I conflated one issue I noticed with another. This is actually `InputField`, not `StableInputNumber` (I do keep misnaming that, don't I?), I'll update the logged issue.

**Comment by abhcs** [comment]
In `InputField` you force-blur on enter here:

https://github.com/PolicyEngine/policyengine-app/blob/6ed3c3f21760420c389b75f6c0fb807644b67369/src/controls/InputField.jsx#L54

I would scrap this component in favor of ant-design's [`Input`](https://4x.ant.design/components/input/).
