### ISSUE TITLE
Data disclaimer obscures x axis labels on decile and cliff charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#130]
These are both fully scrolled down

https://beta.policyengine.org/us/policy?focus=policyOutput.cliffImpact&household=1706&region=us&timePeriod=2022&baseline=2&reform=7

<img width="673" alt="image" src="https://user-images.githubusercontent.com/6076111/210110640-594b4377-063b-437f-ae1a-6657490701a9.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/6076111/210110727-811024ae-5bf5-498f-98e8-6f59dcd3f4ef.png">

**Comment by abhcs** [comment]
This seems to be fixed now:

<img width="854" alt="Screenshot 2023-12-07 at 9 28 08 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/90780168-8a8d-4de6-9ddf-3f9b1a556082">
