### ISSUE TITLE
Enable changing parameters after 2026

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1317]
Currently the date picker only allows dates through 2026-12-31:
<img width="869" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/d9040a82-cbfc-4ed5-94a4-7d89278d1350">

While this doesn't affect any current estimates, since we don't model anything beyond 2025 (household or society), we should display the limitations of the model separately from the policy reforms. Some users may want to create reforms that extend beyond 2025, and we can show how the policy parameter trend would change as a result.

It also means that many previously created reforms can not be fully amended, as we used to set the default date range to 2023-28. For example, you can't fully remove the baby bonus from the [AFA](https://policyengine.org/us/policy?focus=gov.contrib.congress.delauro.american_family_act.baby_bonus&reform=47052&region=us&timePeriod=2024&baseline=2); 2027-28 always remain.
<img width="1401" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/0b316bf2-95de-482a-b110-d585ce9b5053">

**Comment by abhcs** [comment]
So, should we allow indefinite modification into the future, or increase the bound from 2026 to 2028?

**Comment by MaxGhenis** [comment]
I think indefinite is fine. The date picker doesn't make it especially easy to go far into the future.
