### ISSUE TITLE
Update year to 2023

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#132]
Also year is specified manually in several places. Can we consolidate that code?

**Comment by MaxGhenis** [comment]
Still here
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6076111/210890127-04845dcd-58b2-4f71-93e1-049d8f97411d.png">

**Comment by nikhilwoodruff** [comment]
Now fixed (still there as an option, just no longer the default)
