### ISSUE TITLE
Policy calculator's `Reproduce in Python` code no longer works

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1333]
When running the code that I had previously used to successfully verify the changes in #1249 and #1278, the code fails in a Colab notebook with the following message:

```
---------------------------------------------------------------------------

[/usr/local/lib/python3.10/dist-packages/policyengine_core/simulations/simulation.py](https://localhost:8080/#) in _cast_formula_result(self, value, variable)
    900 
    901         if value.dtype != variable.dtype:
--> 902             return value.astype(variable.dtype)
    903 
    904         return value

ValueError: could not convert string to float: 'income_tax_refundable_credits'
```

The entire notebook is available [here](https://colab.research.google.com/drive/1ENdQTtp15nqaad2iLZ4oD3Mow0vBy24Y?usp=sharing); the relevant panel is the third one.

**Comment by anth-volk** [comment]
This is definitely driven by `policyengine-us` v. 0.648.0 specifically, as prior versions up to 0.647.1 work in the testing Colab notebook available [here](https://colab.research.google.com/drive/1ENdQTtp15nqaad2iLZ4oD3Mow0vBy24Y#scrollTo=c4aAfZJl_iGI).

**Comment by anth-volk** [comment]
`policyengine-us` v.0.648.0 introduces changes that disallow the use of `adds` or `subtracts` values in parameters that possess a formula. There has been discussion around reverting and redoing this change (see pe-us [#3851](https://github.com/PolicyEngine/policyengine-us/issues/3851)), as it introduces issues in the US app.

**Comment by MaxGhenis** [comment]
It works for me with the latest packages and autogenerated code for making the CTC fully refundable: https://colab.research.google.com/drive/1lZ5s1ObRIjVt_k3iDfW_c_2EB33Q3Spo

**Comment by anth-volk** [comment]
Shoot, you're right, if I run and pin all the packages at their newest versions, I can run our test code.

Should we open a separate issue asking users to specify package version or something? I could see this being an issue if someone previously installed packages to run code locally, say, 4 months ago, and now they run this code and run into the same error.

More generally, should we have a more thorough walkthrough as to how to run this code for users who aren't the most familiar with Python?

**Comment by anth-volk** [comment]
Closing, as the code does work, so long as the version is updated.
