### ISSUE TITLE
Buggy formatting for two EITC policy parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1336]
Three EITC parameters display buggily:
* [Maximum investment income](https://policyengine.org/us/policy?reform=2&focus=gov.irs.credits.eitc.phase_out.max_investment_income)
* [Phase-out start joint filer bonus (no children)](https://policyengine.org/us/policy?reform=2&focus=gov.irs.credits.eitc.phase_out.joint_bonus%5B0%5D.amount)
* [Phase-out start joint filer bonus (with children)](https://policyengine.org/us/policy?reform=2&focus=gov.irs.credits.eitc.phase_out.joint_bonus%5B1%5D.amount)

Example:
<img width="889" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/e3b80941-55fd-4180-b8ff-a8d9a80b755e">

Here are the issues:
1. Number entry box is divided by $1,000, or $10,000 for maximum investment income, and rounded
2. Time period goes from 1969 to 2099 instead of normal 2012-2030
3. A reform line is shown even though no reform is provided (matching baseline)

I don't see anything unusual in the parameter files themselves that would cause this issue:
* https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/irs/credits/eitc/phase_out/max_investment_income.yaml
* https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/irs/credits/eitc/phase_out/joint_bonus.yaml

I also haven't seen it in other parameters yet, having spot-checked a few.

**Comment by MaxGhenis** [comment]
This bug affects functionality as well as appearance: adjusting the joint bonus parameter causes a failure on the household calculation. See [this video](https://www.loom.com/share/2b8b9e366c614246880e6899d6c74902) and [this link](https://policyengine.org/us/household?focus=householdOutput.netIncome&reform=47731&region=us&timePeriod=2024&baseline=2&household=38803).

**Comment by abhcs** [comment]
For maximum investment income, I see the following parameter values on the front end:

```
0 ["2013-01-01", 3300] (2)
1 ["2014-01-01", 3350] (2)
2 ["2015-01-01", 3400] (2)
3 ["2017-01-01", 3450] (2)
4 ["2018-01-01", 3500] (2)
5 ["2019-01-01", 3600] (2)
6 ["2020-01-01", 3650] (2)
7 ["2021-01-01", 10000] (2)
8 ["2022-01-01", 10300] (2)
9 ["2023-01-01", 11000] (2)
10 ["2024-01-01", 11600] (2)
11 ["1", "0"] (2)
```

Entry `11` is not expected and is causing problems.

**Comment by abhcs** [comment]
For phase-out start joint filer bonus (no children), I see more unexpected entries (19 -- 27) in the front end:

```
[Log] Array (19) (src_layout_MobileCalculatorPage_jsx-src_pages_PolicyPage_jsx.6b25e652060baa2ebff4.hot-update.js, line 69)
0 ["2002-01-01", 1000] (2)
1 ["2005-01-01", 2000] (2)
2 ["2008-01-01", 3000] (2)
3 ["2009-01-01", 5000] (2)
4 ["2010-01-01", 5010] (2)
5 ["2011-01-01", 5080] (2)
6 ["2012-01-01", 5210] (2)
7 ["2013-01-01", 5340] (2)
8 ["2014-01-01", 5430] (2)
9 ["2015-01-01", 5520] (2)
10 ["2016-01-01", 5550] (2)
11 ["2017-01-01", 5590] (2)
12 ["2018-01-01", 5680] (2)
13 ["2019-01-01", 5800] (2)
14 ["2020-01-01", 5890] (2)
15 ["2021-01-01", 5940] (2)
16 ["2022-01-01", 6130] (2)
17 ["2023-01-01", 6560] (2)
18 ["2024-01-01", 6920] (2)
19 ["1", "0"] (2)
20 ["1", "1"] (2)
21 ["1", "2"] (2)
22 ["1", "3"] (2)
23 ["1", "4"] (2)
24 ["1", "5"] (2)
25 ["1", "6"] (2)
26 ["1", "7"] (2)
27 ["1", "8"] (2)

```

**Comment by abhcs** [comment]
For phase-out start joint filer bonus (with children), I see

```
0 ["2002-01-01", 1000] (2)
1 ["2005-01-01", 2000] (2)
2 ["2008-01-01", 3000] (2)
3 ["2009-01-01", 5000] (2)
4 ["2010-01-01", 5010] (2)
5 ["2011-01-01", 5080] (2)
6 ["2012-01-01", 5210] (2)
7 ["2013-01-01", 5340] (2)
8 ["2014-01-01", 5430] (2)
9 ["2015-01-01", 5520] (2)
10 ["2016-01-01", 5550] (2)
11 ["2017-01-01", 5590] (2)
12 ["2018-01-01", 5690] (2)
13 ["2019-01-01", 5790] (2)
14 ["2020-01-01", 5890] (2)
15 ["2021-01-01", 5950] (2)
16 ["2022-01-01", 6130] (2)
17 ["2023-01-01", 6570] (2)
18 ["2024-01-01", 6920] (2)
19 ["1", "0"] (2)
20 ["1", "1"] (2)
21 ["1", "2"] (2)
22 ["1", "3"] (2)
23 ["1", "4"] (2)
24 ["1", "5"] (2)
25 ["1", "6"] (2)
26 ["1", "7"] (2)
27 ["1", "8"] (2)
```

Once these extra values are removed (I don't know the source yet, but perhaps pe-api?), the editor should function normally.

**Comment by abhcs** [comment]
Nope, it's a front-end bug. Will submit a fix shortly.
