### ISSUE TITLE
Enhanced CPS simulations flip % change for bottom decile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1338]
I'm guessing this is because the bottom decile has negative aggregate baseline income. We need to separate the negatives. 

https://policyengine.org/us/policy?reform=46315&focus=policyOutput.decileRelativeImpact&region=enhanced_us&timePeriod=2024&baseline=2

![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/b6f5d7c4-b077-4e64-9ea3-c7608788eb91)

**Comment by anth-volk** [comment]
I'll look into this today, though may not finish until Monday

**Comment by anth-volk** [comment]
I dug into this, considering its priority, but I don't see any good "handle" with which to attack this on the front end. I think it'd be preferable to instead work on this on the API, ensuring that calculation in these situations occurs properly; furthermore, I think that's where the fix would be best positioned, as the front end should merely be responsible for displaying anything sent to it

**Comment by MaxGhenis** [comment]
Yeah I think we start with https://github.com/PolicyEngine/policyengine-us/issues/3855 then adjust the front end to exclude the -1 decile.

**Comment by MaxGhenis** [comment]
We addressed this with changes to the country and api packages.

<img width="887" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/a42df326-305e-4b53-bfe7-f706ca91c00e">

https://policyengine.org/us/policy?reform=46315&focus=policyOutput.decileRelativeImpact&region=enhanced_us&timePeriod=2024&baseline=2

**Comment by anth-volk** [comment]
In hindsight, should we have any note on methodology somewhere on these decile pages to make it clear that we're removing these cases?

**Comment by MaxGhenis** [comment]
@anth-volk yes - filed https://github.com/PolicyEngine/policyengine-app/issues/1372
