### ISSUE TITLE
TS tests not enabled in jest script

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1351]
We have not enabled TS tests within our Jest call, meaning that the TS tests added in #1341 just never run.

**Comment by abhcs** [comment]
Ts test files are compiled to js, and they are running. I have deliberately disabled ts in jest. I could enable them using babel but I did not because of the [caveats](https://babeljs.io/docs/babel-plugin-transform-typescript#caveats).

**Comment by anth-volk** [comment]
Okay, so long as they are in fact running, I'll close this out
