### ISSUE TITLE
Rounding in numerical input fields is superficial and not reflected in the value passed to the back end

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1357]
## Steps

1. Go to [this example](https://policyengine.org/us/policy?focus=gov.dol.minimum_wage&region=us&timePeriod=2024&baseline=2).
2. Change the wage to `7.251` and press Enter.

## Observation

1. The value in the field jumps back to `7.25`.
2. The reform `7.25` -> `7.251` is created and the url changes.
3. The value `7.251` is seen in the graph below.

## Expected

Both views (the input field and the graph) should be consistent with the model. Since we force rounding in the input field, the reform should not be created.

A similar workflow is described [here](
https://github.com/PolicyEngine/policyengine-app/issues/1354).

**Comment by anth-volk** [comment]
Just to be clear, #1356 doesn't do anything toward this issue, correct?

**Comment by abhcs** [comment]
Yes, #1356 doesn't solve this issue but it solves the problematic use case described in #1354. I need some time to fix this issue properly.

**Comment by anth-volk** [comment]
Okay, just wanted to confirm
