### ISSUE TITLE
Domestic energy consumption header is left-aligned

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#14]
Other variables are fine from what I can tell, and navigating away and back still shows it left
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/6076111/204102050-50c433ca-ea87-4a34-9ee1-aa4c26c486d2.png">

**Comment by nikhilwoodruff** [comment]
It's not actually I think, it just wraps awkwardly
