### ISSUE TITLE
Should we remove "Include earning variation" from the household calculator Reproduce in Python page?

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1405]
I'm kind of curious what its original purpose was and if it's a holdover from a previous version

**Comment by MaxGhenis** [comment]
It adds axes such that results show many different values corresponding to earnings levels. It helps reproduce the "Varying your earnings" chart but distracts otherwise, when the user just wants one result. So I think it's worthwhile.
