### ISSUE TITLE
API returns different result than the one displayed on the API page

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1412]
For the example input, the `snap` computed by the API is `2833.5`. On running the same example locally, I get

```js
{
    "message": null,
    "result": {
        "people": {
            "child": {
                "age": {
                    "2024": 5
                }
            },
            "parent": {
                "age": {
                    "2024": 30
                },
                "employment_income": {
                    "2024": 20000
                }
            }
        },
        "spm_units": {
            "spm_unit": {
                "members": [
                    "parent",
                    "child"
                ],
                "snap": {
                    "2024": 2334.0
                }
            }
        }
    },
    "status": "ok"
}
```

## Expected

The outputs should be consistent.

**Comment by MaxGhenis** [comment]
While we're fixing this let's also specify the state_code since it affects the amount

**Comment by anth-volk** [comment]
When running this in a Colab setup, I receive the same 2334.0

**Comment by anth-volk** [comment]
@abhcs Yeah, I'm only confirming that I reproduced what you saw, as I was worried there was some underlying bug in the API or in our API call. Turns out the reason this occurs is because the response is hard-coded into the page - there's no API call at all, hence the confusingly different value.

**Comment by anth-volk** [comment]
@abhcs I can take this bug, as well as a couple others on the API page, if you would rather work on something else, as I think some visual fixes are also in order. That said, since you identified them first, I'm happy to step aside if you'd prefer to work on them.

**Comment by abhcs** [comment]
Please go ahead! (I usually just assign myself the issue when I want to work on it immediately.)
