### ISSUE TITLE
For some household charts, the legend is drawn over the plot.

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#1437]
In [this example](https://policyengine.org/us/household?focus=householdOutput.earnings&household=41940&region=us&timePeriod=2024&baseline=2&reform=48789), the legend collides with the plot:

<img width="760" alt="Screenshot 2024-03-03 at 11 46 11 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/a7ca3be7-5d44-4a1e-94f6-9b45833948de">

**Comment by MaxGhenis** [comment]
I'd suggest we condense the legend to just Baseline (gray line) and Reform (blue line). We don't need the dots in the legend, nor the name of the variable which is already shown in the y axis title and the drop-down.

**Comment by abhcs** [comment]
The y-axis titles for the absolute and relative change plots cut out:

<img width="760" alt="Screenshot 2024-03-03 at 12 12 00 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/e33338e4-808f-4317-99ee-ab2b5d973263">

Should we also change these axis titles to `Absolute Change (unit, when available)` and `Relative change (%)`?
