### ISSUE TITLE
Axis tick lines (at least on household relative change numbers) round, creating strange outputs

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1445]
For instance, in the chart below (accessible at https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37636&region=uk&timePeriod=2023&baseline=1&household=32608), certain tick values are the result of rounding off values ending in 0.5

<img width="579" alt="Screen Shot 2024-03-04 at 9 05 58 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/00fe6a4b-d336-46a8-a764-08036bff3b6d">

**Comment by abhcs** [comment]
Duplicate of #1442? Both seem to be about rounding issues on ticks when the range is small.

**Comment by anth-volk** [comment]
I couldn't tell from #1442 if it was a rounding issue or if it was driven by something else, since all of the ticks are -60, but you're probably right, closing as duplicate.

**Comment by abhcs** [comment]
I will make sure to test the fix on this input as well, thanks.

**Comment by anth-volk** [comment]
Thanks so much
