### ISSUE TITLE
"Relative change" chart for household does not provide padding or standard text below the chart

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1446]
If visiting https://policyengine.org/uk/household?focus=householdOutput.earnings&reform=37636&region=uk&timePeriod=2023&baseline=1&household=32608, the "Baseline and reform" and "Absolute change" options will provide a block of text and some padding below, but the "Relative change" will not, cutting off the bottom of the chart

**Comment by abhcs** [comment]
The bottom of the chart does not cut out for me. Can you please provide an image or more details?

**Comment by anth-volk** [comment]
Here's how the page looks for me when scrolled all the way down on the "Absolute change" section:

<img width="1440" alt="Screen Shot 2024-03-04 at 9 30 55 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/b83c9ce5-2148-4310-874d-728416740c08">

And here's how it is on the "Relative change" section:

<img width="1440" alt="Screen Shot 2024-03-04 at 9 31 00 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/fd2744ea-8ab3-492e-b218-53e597828a11">

Since I'm one of the world's 3 Firefox users, I've also just confirmed that this occurs for me on Chrome, as well.

**Comment by abhcs** [comment]
I see the issue now too. It isn't browser-specific but it depends on the order of operations. For instance, if you choose the order Absolute -> B&R -> Relative, the text should show up for Relative. The order sensitivity is similar to #1443, but this is a distinct issue.

**Comment by anth-volk** [comment]
That is certainly unexpected behavior
