### ISSUE TITLE
Add utility function in Jest setup that fetches US and UK metadata

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1450]
This is used in various places in the tests, so it would be great to have just one fetch at the start, before all tests

**Comment by czhou578** [comment]
What do you mean by "start"?

**Comment by czhou578** [comment]
@anth-volk, just to confirm, I'm seeing some test files that are fetching the metadata not in a ```beforeAll``` clause, but within the ```test``` clause, as shown in the image. Do you want me to leave that as it is?
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/49240e08-ef35-4fd4-a47d-b44ea43bd52a)

**Comment by anth-volk** [comment]
Shoot, actually, could you change that? That's not what this issue refers to, but it would be good to fix that, as well.

**Comment by anth-volk** [comment]
Out of curiosity, though, have you determined a way to fetch before all test files? Ideally, this would function in some sort of separate setup file, before the tests, the describe blocks, etc.

**Comment by czhou578** [comment]
Ok. I guess I can change that. I believe I have found a way to run that fetch metadata function before all the test suites. I'm using the ```setupFilesAfterEnv``` property in the ```jest.config.js``` to run a new file I created that has the fetching logic included. I'll open a PR for you soon so you can check.
