### ISSUE TITLE
Twitter feed in footer shows old posts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1462]
We've posted a lot since this...https://twitter.com/ThePolicyEngine
<img width="406" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/ff4ee4e4-ef27-4128-952f-4f63ba83f182">

**Comment by anth-volk** [comment]
It may be time to switch back to the standard component.

The downside of that component is the potential that a user without an account or one who isn't logged in is potentially confused by the Twitter embedded `iframe`'s default behavior, which is to say that a user hasn't posted anything yet. That said, better that than an outdated feed.
