### ISSUE TITLE
Notebook posts don't create preview images

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1464]
https://twitter.com/PolicyEngineUK/status/1765846270504018351

<img width="734" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/bb7285ba-a513-4422-993f-c9782d3a013c">

and https://twitter.com/PolicyEngineUK/status/1765348012119789802

<img width="749" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/4ef5cf54-974b-4b3d-bf20-b25d93d62346">

**Comment by anth-volk** [comment]
The issue is actually even more extensive - when sharing on Facebook, neither notebook nor standard posts share images, but notebook posts also have no description or name, just defaulting to "PolicyEngine" for both
