### ISSUE TITLE
Bring mobile modals to desktop

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#147]
The modals showing modeled policies for households and data/static info for reforms provide useful info, and #146 will make them a better waiting room than what we show today. Let's bring them to desktop.

**Comment by anth-volk** [comment]
I get the sense that we've implemented this, but is there any additional information you'd want included in the existing modals (other than the fact that we don't model US sales & property tax, as opened in another issue)?

**Comment by MaxGhenis** [comment]
I don't think so - and any additional info would come from the country packages. Closing.
