### ISSUE TITLE
Mobile users without geolocation enabled default to `policyengine.org/undefined`, not `/us`

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1471]
This makes the calculator unusable

**Comment by dotslashbit** [comment]
<img width="1384" alt="Screenshot 2024-03-22 at 20 33 42" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/9529ea92-0b83-486d-83e1-07cb1582e8cf">
I tried opening /undefined and it opened without getting redirected to /us. Is this related to this.

**Comment by anth-volk** [comment]
This is related, but not the same. 

In theory, the way `react-router-dom` is implemented in this package is that if the app is unable to determine a user's location or if it's not in a certain set of locations, they're automatically redirected to `/us`. The problem in this issue is that, for some reason, on mobile, the value of `undefined` is just passed through and becomes `/undefined`, instead of directing the app to redirect to `/us`.

Separately, the app has an issue where you can type in any garbage value - `/undefined` works, but so does `/dworkin` - and the app will load without a country code, displaying only a subset of the homepage articles and (sometimes) breaking if the user tries to access a calculator.

This GitHub issue is only focused on the first problem, whereas #1002 focuses on the second.
