### ISSUE TITLE
Remove `(enhanced CPS)` from chart titles

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1474]
Let's move this to the footnote instead with the PolicyEngine version number
<img width="976" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/9d0aebb8-6e25-4841-98a4-c8533de9cebc">

**Comment by MaxGhenis** [comment]
We can continue not displaying the region in titles for US results

**Comment by anth-volk** [comment]
I've added the footnote and removed the tag, as displayed in the video below. However, before opening a PR, I want to make sure of the following:
* Is the text in the footnote the proper text?
* Is the font size of the footnote correct?


https://github.com/PolicyEngine/policyengine-app/assets/14987227/9b38d312-75d6-4619-98e3-1ad1ffbf1711

**Comment by MaxGhenis** [comment]
Could we add it as a second sentence to the existing footnote (decile description in this case)?

**Comment by anth-volk** [comment]
If you mean as part of the legend, below are screenshots of the two charts featured in the screen recording (ignoring where the logo crowds over the text, which can be adjusted). If you mean as part of the x axis data values, I'm a bit less sure, but probably also doable.

<img width="683" alt="Screen Shot 2024-03-28 at 8 23 24 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/9cfed027-82ef-4667-bc23-627076457070">

<img width="686" alt="Screen Shot 2024-03-28 at 8 27 06 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/98e6c956-4d4b-4fb6-8eb1-c1b4c967ccec">

**Comment by MaxGhenis** [comment]
Neither - the text in the footer specifying the package version

**Comment by anth-volk** [comment]
Perfect, that'll actually be far easier
