### ISSUE TITLE
PolicyEngine logo cut off from cliff chart when title is multi-line

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#150]
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/6076111/211246312-12d3ed9e-2f5a-4767-aba5-81cee18304cd.png">

Not cut off when title is one line:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/6076111/211246757-12152b7b-e153-436b-aff2-8d09947e5a98.png">

**Comment by anth-volk** [comment]
No longer the case post-redesign. Closing.
