### ISSUE TITLE
Remove junk code from `HomeLanding.jsx`

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1501]
The commented code should just be removed

**Comment by daemon-reconfig** [comment]
is this issue closed?

**Comment by MaxGhenis** [comment]
Yes the commented code has been removed (no commented code here https://github.com/PolicyEngine/policyengine-app/blob/master/src/redesign/components/HomeLanding.jsx)

**Comment by MaxGhenis** [comment]
The curly braces prevent linking @czhou578 fyi
>Fixes {https://github.com/PolicyEngine/policyengine-app/issues/1501}

**Comment by czhou578** [comment]
Got it. I don't think the issues I've worked on since have had this problem.
