### ISSUE TITLE
Remove 2021 option in microsim

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1512]
The 2022 CPS is the default dataset, so 2021 impacts never complete in the web app: https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&timePeriod=2021&region=us&baseline=2&reform=51188

It also crashes in Python: https://colab.research.google.com/drive/1Z3TklNpPv_cMBB0PbA7j_0XIlcD-SWNx?usp=sharing

We no longer need this.

**Comment by anth-volk** [comment]
The list defining which years to include is actually in the API. To confirm before doing so, do we have any API users who rely upon 2021 calculations? If not, I think we should close this and open a corresponding issue on the API repo, where it'd be as simple as removing one line.

**Comment by MaxGhenis** [comment]
No we don't (it wouldn't work)

**Comment by anth-volk** [comment]
Closing and opening a relevant issue in the API

**Comment by anth-volk** [comment]
Opened as API [#1364](https://github.com/PolicyEngine/policyengine-api/issues/1364).
