### ISSUE TITLE
Show most recent featured posts on homepage

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1515]
Currently we only show the most recent featured post. We show many other posts, but only non-featured ones. To see other featured posts (right now, that'd include the TRAFWA CTC and ECPS posts, which are most important for readers to see), you have click the small squares in the featured section.

I'd lean toward removing the square things within the Featured box and just showing allocating the non-most-recent featured posts to the other parts of the homepage.

<img width="640" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/584a1596-8fd9-4d2d-bcbc-741c1355816c">

**Comment by lilychen0505** [comment]
Hi Max,

I attempted to address the issue you mentioned. Before proceeding, you referred to "allocating the non-most-recent featured posts to other parts of the homepage." Does this mean we should rearrange the posts? If so, what should be the logic behind their reordering?

**Comment by MaxGhenis** [comment]
Could we discuss this at tomorrow's app dev meeting?

**Comment by lilychen0505** [comment]
Sure, talk to you then :)

**Comment by nikhilwoodruff** [comment]
Per discussion I think we need three things for `allPosts` (on desktop and tablet) (the list of posts to display in the smaller right hand side boxes):

1.  We should not exclude featured posts.
2. We should exclude the first featured post.
3. We should order the posts by featured status first, then recency.

**Comment by MaxGhenis** [comment]
Can we remove the carousel too? Seemed like this was modeled after an earlier version of JRF's site, but now they and all other think tanks I've seen just show all posts.

**Comment by anth-volk** [comment]
I had also advocated for the carousel's removal. That said, doing so might require more planning as to what to replace it with, unless we'll just have a large spot for the first featured article. If more planning is required, it might be better to wait to remove it and place that into a separate issue?
