### ISSUE TITLE
Background color of Ant Design `Switch` components should be changed from Ant Design's default blue to our blue

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1531]
For example, in this situation:

<img width="713" alt="Screen Shot 2024-04-01 at 9 11 37 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/cd30ab1b-da27-40a5-a68f-7d175a661f14">

The slider should use the dark blue that we use throughout. Not sure how this would work without looking through the documentation, but it should be relatively straightforward?

**Comment by czhou578** [comment]
I can try to take this issue.

**Comment by anth-volk** [comment]
If possible, it'd be great to have you on this. I'll look into `BiPanel.jsx` later today, as I'm not too familiar with how it's currently utilized.

**Comment by anth-volk** [comment]
To be clear, the background color we're shooting for is labeled "BLUE" in the old style files and "BLUE_PRIMARY" in the new. Harmonizing these two files is something I desperately want to do, but in the meantime, feel free to use either.

**Comment by anth-volk** [comment]
We'll need to do the things mentioned in #1584 first and migrate to Ant Design v5 before fixing this issue.

**Comment by anth-volk** [comment]
Closing in light of #1670.
