### ISSUE TITLE
Square off Ant Design `Switch` elements

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1532]
Would look something like this (manipulated just through the console debugger):

<img width="322" alt="Screen Shot 2024-04-01 at 9 14 22 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/d2ea9544-5d82-4f35-9c70-3f5617241e32">

If this is possible, it likely wouldn't be through any Ant Design custom prop or something, but rather passed through as a `style` parameter. That said, if it isn't possible, it's not that big a deal.

**Comment by daemon-reconfig** [comment]
Can you explain the issue please

**Comment by anth-volk** [comment]
At the moment, our Ant Design `Switch` elements always have rounded edges on the button and on the background part. They look like the ones you can find on their documentation page at https://4x.ant.design/components/switch/#header. We're hoping to have them squared, instead, like the image above.

**Comment by daemon-reconfig** [comment]
Can I work on it?

**Comment by anth-volk** [comment]
This is related to #1531.

**Comment by anth-volk** [comment]
Sure, I'll assign you. Just a couple things - 

1. This might not be possible within Ant Design's components. If that's the case, that's alright, once we upgrade to version 5 (open as issue #1479, but requires a lot of stuff beforehand), I believe we can pass a ConfigProvider (open as #1181) to simplify all this.
2. If possible, it'd be great if you could write a custom `Switch` component that builds in the styling, then replace the existing switches with it. You can look to the `Button` component to see how that might work. If you can't, we can also talk through how to do so.

**Comment by daemon-reconfig** [comment]
we can talk on this on friday if that’s fine with you

**Comment by anth-volk** [comment]
Fixed by #1670.

**Comment by daemon-reconfig** [comment]
it’s alright
