### ISSUE TITLE
Center Twitter feed on mobile

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1533]
I believe it's currently left-aligned, though would be great if it could be checked by someone whose feed actually displays

**Comment by MaxGhenis** [comment]
Looks OK to me

<img width="1186" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/42704f46-b5a2-45fc-a95d-636a21127ffc">

**Comment by anth-volk** [comment]
On mobile breakpoints, though, it's left-aligned, and since the width is fixed (custom data tag won't accept custom widths), it looks awkward

**Comment by anth-volk** [comment]
Closing in light of #1539
