### ISSUE TITLE
Link `good first issue`-tagged issues to the README

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1543]
Should allow for new contributors to get going very quickly; that said, I have no idea if this is technically feasible within GitHub.

**Comment by anth-volk** [comment]
Out of curiosity, would that be run as part of a GitHub Action, or require building something into the codebase itself? If it's an action, I'd think either daily or weekly makes sense; if it's part of something else, I'd be curious to see what sort of costs it would impose.

That said, definitely, once we collectively decide on an implementation, we'd love your contribution to it!

**Comment by MaxGhenis** [comment]
How high should we prioritize this given we can just link to https://github.com/PolicyEngine/policyengine-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 ?

**Comment by czhou578** [comment]
Now that I think about it, maybe linking it would be easier, since it's not guaranteed that a new contributor would find the 5 most recent "good first issue" issues easy or interesting to work on. What do you think @anth-volk ?

**Comment by anth-volk** [comment]
Oh, wow, that link is super easy. I'll convert this to an issue to just add that link to the README.

**Comment by anth-volk** [comment]
In hindsight, there's probably no need for this.
