### ISSUE TITLE
AI summary failing

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1550]
Tried multiple times on the US and UK, the `GENERATING` just keeps spinning.

Might have to do with OpenAI switching to prepaid credits.

**Comment by anth-volk** [comment]
This appears to have been solved with API [#1513](https://github.com/PolicyEngine/policyengine-api/pull/1513). This very likely wasn't caused by prepaid credit issues and instead by syntax issues in the `get_analysis` endpoint.
