### ISSUE TITLE
Not all authors are displayed properly on Research page's authors filter tab 

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1554]
This is visible in the video below. When trying to filter by author, the last author to appear in the list is Donglai Xu, but there are about five authors below that one, and when a user scrolls all the way to the very bottom of the page, they can see them, but otherwise, it's impossible to apply filters with these authors.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/24f6e956-42fa-43ea-8455-b90d4ee8db78

**Comment by YashrajKupekar17** [comment]
I would like to solve this issue.

**Comment by anth-volk** [comment]
@YashrajKupekar17 I believe @NishantSatere is in progress on this. If he confirms he's not, I'd be happy to pass it over to you. In the meantime, I'll assign him to make clear to others the status of this.

**Comment by NishantSatere** [comment]
@anth-volk  i am on it, i am opening the PR now

**Comment by daemon-reconfig** [comment]
is this issue still being worked on?

**Comment by anth-volk** [comment]
It looks like no. @daemon-reconfig, I'll assign you to it. There's some discussion around Nishant's previous work on this in the thread for #1585 that might also clarify what we're looking for. Basically, at any height, the authors filter tab should show all authors.

**Comment by daemon-reconfig** [comment]
sure I will try my best to complete it asap

**Comment by daemon-reconfig** [comment]
An update on this. I have tried fixing the height of the filter side and it works fine but I didn’t like it from a design perspective. so what I think we can add is something similar if it calculates the left height and adjusts it according to it.

**Comment by anth-volk** [comment]
Is there any way using just CSS properties to restrict the height of the opened menu to, basically, the bottom of the page (minus some padding and the other display properties), then make the interior of that a scroll container? I believe there's a native way within Ant Design to restrict the menu so that only one part opens at a time, as well, which could be a good way of doing things.

**Comment by daemon-reconfig** [comment]
I will show what I did in a few minutes

**Comment by daemon-reconfig** [comment]
can we close this?

**Comment by anth-volk** [comment]
No, if you go to the Research page and try expanding the authors, they are still hidden
