### ISSUE TITLE
Refactor `BlogPost.jsx` such that the markdown formatting component is a separate component in a separate file

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1560]
This should not be done until #1548 is complete. Currently, `BlogPost.jsx` contains various components utilized in formatting and displaying a blog post, but one component (I'm forgetting the name) essentially just formats relevant markdown data using a React markdown package. However, this component is also used by `Analysis.jsx` to format its data, and it's not inconceivable that future work might require formatting markdown that isn't a blog post. As such, this should be separated out into a separate file and any blog post-specific features should be redone, if any are present, to allow the component to be as flexible as possible.

**Comment by czhou578** [comment]
@anth-volk I think the component you are talking about is called ```BlogContent.jsx```. Do you want to simply put this component into a separate file and import it into ```BlogPost.jsx```? 
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/9b4cda54-de20-4105-95d7-bbbbe65ca572)

**Comment by anth-volk** [comment]
I think so, and if you could rename it to something like "MarkdownFormatter," maybe? I think that probably makes the most sense.

**Comment by czhou578** [comment]
Ok, then I'll take this issue.

**Comment by anth-volk** [comment]
Perfect! Looking forward to your help with this, @czhou578.
