### ISSUE TITLE
Make navbar more consistent across breakpoints and with similar sites

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1564]
Currently, I think there are three major drawbacks with the navbar:

1. Its height is 90px (very large) on desktop/tablet, but only 50px on mobile
2. While it's mainly written against flexbox, liberal use of margins makes maintenance difficult
3. It can really only fit a few options as written

Its height is particularly significant, since most sites place theirs between 60px and 80px, and its large size is what necessitated setting a custom value on mobile. I think this should all be changed as follows:

1. Navbar height for all breakpoints should be set to 64px; Pieter Heyman has a good explanation of why [here](https://blog.prototypr.io/a-quest-for-the-ideal-navbar-height-4d3898a41f2), but this is also what Material Design uses for its header bars
2. The component should better organize items by using a nested flexbox approach, as opposed to manual margin settings
3. Text height should be dropped to 16px

I will likely need to do these as part of #1561, as merely adding it to the existing bar produces a part that is extremely cluttered and forces poorly-sized wrapping on the large feature button that we utilize

**Comment by daemon-reconfig** [comment]
Can I also take on this issue?

**Comment by anth-volk** [comment]
@daemon-reconfig Unfortunately, this is currently in the works as part of #1583 (feel free to clone that if you want to check out what it looks like at the moment)
