### ISSUE TITLE
Don't round percentages in parameter history hovercards

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1565]
For example, it shows 4.6% as 5% here: https://policyengine.org/us/policy?focus=gov.states.nc.tax.income.rate&household=43203&region=us&timePeriod=2024&baseline=2

<img width="684" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/0f1141b0-80b7-45ad-bf9a-258e00cd88c4">

**Comment by NishantSatere** [comment]
assign me

**Comment by anth-volk** [comment]
Reopening in light of #1635.
