### ISSUE TITLE
Add Martin Holmer to About page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1575]

**Comment by anth-volk** [comment]
Should he be in a separate section from myself and Pavel, considering his background and experience? And if so, is there a specific title desired for it?

**Comment by MaxGhenis** [comment]
Same section - let's also add `(consultant)` to all

@martinholmer how's this for your bio (taken from your [website](https://martinholmer.github.io))? Could you share a headshot?

>MARTIN HOLMER is an economist at PolicyEngine (consultant). He focuses on our state income tax models and validation architecture, and has contributed other models such as the premium tax credit. Previously, he was the lead developer for the Policy Simulation Library's Tax-Calculator federal income tax microsimulation model, and he has built microsimulation models around the world for organizations including the World Bank. Martin has a Ph.D. in economics from MIT.

**Comment by martinholmer** [comment]
@MaxGhenis suggested:
> ... for organizations including the World Bank.

How about this:
```
... for organizations including the World Bank and the US Social Security Administration.
```

**Comment by daemon-reconfig** [comment]
Can I take on this issue?

**Comment by MaxGhenis** [comment]
Sure please open a PR and use this headshot https://github.com/ospc-org/ospc-org.github.io/blob/master/images/holmer.png

**Comment by daemon-reconfig** [comment]
I am unable to find the page that comes when we click on About 
I found an AboutPage but it was not similar to what was visible.

**Comment by daemon-reconfig** [comment]
sure will do so

**Comment by MaxGhenis** [comment]
yes

**Comment by daemon-reconfig** [comment]
can’t open another pr unless i still have one open will do so on Monday when @anth-volk comes

**Comment by MaxGhenis** [comment]
please file a new pr from a branch

we recommend this workflow: https://code.visualstudio.com/blogs/2020/05/06/github-issues-integration#_working-on-issues

**Comment by daemon-reconfig** [comment]
should I use any branch?

**Comment by MaxGhenis** [comment]
i'd suggest following the above workflow which creates a branch named after your username and the issue number

**Comment by daemon-reconfig** [comment]
I am unable to create a branch

**Comment by anth-volk** [comment]
Can you give more detail as to what error message you receive, what you're seeing as you're trying, etc.?

**Comment by daemon-reconfig** [comment]
I don’t think so i have the power to create a branch i guess but i will check for it once again

**Comment by anth-volk** [comment]
Ideally, you should create a branch on your fork, which you own. Then, open a pull request from that fork against `policyengine-app`'s `master` branch, as shown in the workflow Max shared. I can also give a more detailed overview of the command line flow, if preferred.

**Comment by MaxGhenis** [comment]
Please describe specifically what you're doing. If you're applying the guidance above, you may be getting an error assigning yourself to the issue (not creating the branch) because we haven't yet assigned you triage access to the repo.

**Comment by daemon-reconfig** [comment]
sure I will try once again
