### ISSUE TITLE
Typo in intradecile chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#158]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/6076111/211970596-700ddfb0-24aa-4f77-956a-a525e2913e4f.png">

**Comment by MaxGhenis** [comment]
Different text now but typo remains
<img width="894" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/df4221f5-b5ec-4ef2-8368-f854a7ccbc9b">

**Comment by abhcs** [comment]
This issue was fixed in commit f48d068, as far as I can tell.
