### ISSUE TITLE
Multiple posts not loading

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1586]
Blank screen

https://policyengine.org/us/research/trafwa-ctc

**Comment by MaxGhenis** [comment]
Also the ECPS post https://policyengine.org/us/research/enhanced-cps-beta

**Comment by anth-volk** [comment]
Looks like we have two different image folders that were used by the two different posts management files, one being `posts.json` and one being `Posts.jsx`. A recent merged PR got rid of `Posts.jsx` and moved the functionality from it elsewhere, but interestingly, the two image folders (in rare cases, such as this one) have two different file extensions.

**Comment by anth-volk** [comment]
Or, in the case of the enhanced CPS file, there just is no image in the second folder
