### ISSUE TITLE
More safely handle conditional `require` statements in blog post

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1589]
Currently, in the `BlogPost.jsx` component, we use a conditional `require` to load blog images. However, the conditional only checks if a blog image is specified, not if it's present. I'm not sure if this is technically feasible, but it'd be great to ensure that a failing `require` statement returns some sort of empty "broken file" block, akin to what standard JS-free HTML image loading would do, as opposed to killing the entire app.

**Comment by czhou578** [comment]
I can try taking this issue. If I return a broken placeholder image like this, would that be acceptable?

![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/88609742-5fee-46c7-8eb7-4f82014eb322)
