### ISSUE TITLE
Add "Canada" to the `locationLabels` within `postTransformers.js`

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1590]
This should mirror the other labels within that object, such as US, where a `us` key corresponds to the country's full name. Here, `ca` should correspond with `"Canada"`.

**Comment by JoaquinFioriti** [comment]
Can i take this issue?

**Comment by anth-volk** [comment]
Please feel free!

**Comment by JoaquinFioriti** [comment]
Thx! I think i am not allowed to push
![Screenshot 2024-04-11 182356](https://github.com/PolicyEngine/policyengine-app/assets/70446526/5119aaaa-675b-4b36-838b-7b224910c08a)

**Comment by anth-volk** [comment]
Typically we ask contributors to push to a fork, then open a PR off of a fork against the original, to ensure code stability and security.
