### ISSUE TITLE
Ensure that API page displays properly on smaller breakpoints

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1593]
<img width="800" alt="Screen Shot 2024-04-12 at 5 57 18 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/4c101c19-5c98-4092-a55d-e32cd50e5104">

Referring to the above photo, the gutters that the rest of the page has should be maintained, and the left code block should be placed above the right, with some gap or padding between the two.

**Comment by masterismail** [comment]
![Screenshot from 2024-04-18 02-11-07](https://github.com/PolicyEngine/policyengine-app/assets/111173270/d87f5a30-1101-47c0-9772-4395975b6dcf)

like this ?

**Comment by anth-volk** [comment]
@masterismail Our application currently uses three breakpoints, which are returned as a string value with the `useDisplayCategory()` hook - `mobile`, `tablet`, and `desktop`. What you have above is roughly what we're looking for, but only on `mobile`. If you minimize your browser width below 768px, you'll see what we have currently, and basically we're looking for the layout you have there, but with the same left and right padding that's present throughout the mobile page.

**Comment by masterismail** [comment]
[Screencast from 18-04-24 07:56:31 PM IST.webm](https://github.com/PolicyEngine/policyengine-app/assets/111173270/9a18c47d-5a18-4b71-9f41-86e3fe7a118c)

I have maintained a padding for both the code blocks and the content above. Will commit the code once you are satisfied with the UX.

**Comment by anth-volk** [comment]
Thanks for your work on this. I just had a chance to explore this a bit more. Could you do the following, as well:

* On `mobile`, make sure that the padding on the code blocks and content above matches the "PolicyEngine API Documentation" block above it - we'll deal with the one under it in a separate issue
* On `tablet`, make sure the code blocks line up one on top of the other - my apologies, didn't realize it should be on that, too
* On `tablet` and `desktop`, make sure the padding is the same as the "PolicyEngine API Documentation" block above.

Thanks again for all of this.

**Comment by Alperadoss** [comment]
it seems like this issue is not solved. I can work on it quickly if it's ok?

**Comment by anth-volk** [comment]
@Alperadoss I believe this is actually fixed now, but would you be willing to work on https://github.com/PolicyEngine/policyengine-app/issues/1975 instead? Hopefully this is also a relatively easy fix.
