### ISSUE TITLE
Add a `1.` before the first item in the terms of service

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1595]
<img width="1304" alt="Screen Shot 2024-04-12 at 7 02 43 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/25b11a57-8a1d-4f0b-9862-285e50d367f8">

This is from the Terms of Service page. The first item under "Introduction" should have a `1.` in front of it.

**Comment by daemon-reconfig** [comment]
<img width="1271" alt="Screenshot 2024-04-13 at 10 55 42 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/69844188/e9ef94db-4ba8-4d0a-87b9-e961b31f60a5">
is this it?

**Comment by anth-volk** [comment]
@daemon-reconfig Yes, but this was already taken on by @shaunakwagh above, who opened #1598 to fix.

**Comment by daemon-reconfig** [comment]
okay!

**Comment by anth-volk** [comment]
Fixed with #1598.
