### ISSUE TITLE
PolicyEngine logo cut off on cliff chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#160]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/6076111/212006099-d29c6398-e58c-46b4-8a24-67b3780173ad.png">

https://policyengine.org/us/policy?focus=policyOutput.cliffImpact&reform=101&region=us&timePeriod=2023&baseline=2

**Comment by anth-volk** [comment]
No longer present post-redesign. Closing.
