### ISSUE TITLE
Drop-down and entry boxes became poorly formatted

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1609]
I think this was today, likely due to #1597. Maybe removing `import "antd/dist/antd.min.css";` from `src/index.js`? It's affecting the household and policy pages in several places.

![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/552d5a52-9f04-43f2-aa5d-50702f771a1b)

**Comment by anth-volk** [comment]
My apologies, I should've caught this in review by running `make install` again before running.
