### ISSUE TITLE
Fix UK spring launch post

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1617]
White-screening for some reason

**Comment by anth-volk** [comment]
Did you add the newest article’s image to the `/src/images/posts` folder? That is now the new source of truth for those images (in line with `posts.json` also not being in the `redesign` folder), but I only quickly solved the issue that arose a few days ago with US articles not displaying images, so I’ve yet to delete the `/redesign/images/` folder, which is open in an issue (I forget which number at the moment) but will be removed.
