### ISSUE TITLE
More safely handle conditional require statements for blog article images on homepage, main Research page

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1629]
Related to #1589, it would be great to do what @czhou578 is doing in #1628 for both the homepage and the main Research page.

**Comment by anth-volk** [comment]
@czhou578 Would you also be willing to take this issue? This is targeted at the Research page and homepage.

**Comment by czhou578** [comment]
Sure. I can take this issue.

**Comment by czhou578** [comment]
@anth-volk, do you want me to do checks on these images as well?
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/53f5d28c-f991-4b31-98d0-edffd8104e17)
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/28daf282-5b49-46ad-8eab-a445b728ca40)

**Comment by anth-volk** [comment]
Sure, please do so.
