### ISSUE TITLE
All parameter graphs have percentage y axis formats

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1631]
I've checked a range of them and confirmed they're labeled with currency in the country package. example:

<img width="685" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/d5df522c-105e-4e59-8366-b18c721a8b3d">

https://policyengine.org/us/policy?reform=2&focus=gov.irs.dependent.ineligible_age.non_student

I'm guessing #1622 caused this. @masterismail could you take a look?

**Comment by masterismail** [comment]
yes,  https://github.com/PolicyEngine/policyengine-app/pull/1622 was indeed causing this issue, I apologize for the oversight, and have now resolved it with [this fix](https://github.com/PolicyEngine/policyengine-app/pull/1632)

**Comment by anth-volk** [comment]
My apologies as well, I should've tested more thoroughly before approving #1622.

**Comment by anth-volk** [comment]
If you have a LinkedIn and you share a link to it, I could connect with you there and invite you to the Slack. However, one of PolicyEngine's pillars is openness (it is half of "open-source", after all), so feel free to write your question here! There are no dumb questions, and we work with developers of all experience levels, so no question is too "amateur".

**Comment by anth-volk** [comment]
Why don't we do this? Prior to the changes you made in #1622, the code worked properly. Could you go back to how the code was then, then essentially re-fix #1565, but making sure the y-axis is formatted properly? I think it's probably easier to go in that direction than to rebuild what worked before.

**Comment by MaxGhenis** [comment]
Yes let's just revert the breaking PR for now if it's not clear how to address the rounding issue

**Comment by masterismail** [comment]
[these changes](https://github.com/PolicyEngine/policyengine-app/commit/1d59ebff0a36e9fc0b0768d2d4b15ceb229ad05a) work for a few parameters. But dosen't really work well with $.

ps : I am on the policyengine slack would dm there.

**Comment by anth-volk** [comment]
The reversion PR is open now; just letting tests finish before merging.

@masterismail Apologies to have to revert, but considering the impact of the issue upon the UX, it's necessary in this case. Would you be willing to pick up where you left off on #1565?

**Comment by anth-volk** [comment]
@masterismail We could even set up a time to pair program, if necessary, later this week, or if you have any questions about how Plotly is used in this component, you can feel free to ask here

**Comment by anth-volk** [comment]
Closing in light of #1635.

**Comment by masterismail** [comment]
> @masterismail We could even set up a time to pair program, if necessary, later this week, or if you have any questions about how Plotly is used in this component, you can feel free to ask here

sure @anth-volk looking forward to pair program. I can explore more into Policy Engine and this issue in particular.
