### ISSUE TITLE
Use reform name in tab name

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#164]
The tab name has the reform number, not the name

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/6076111/212439585-a5d9af2e-1e55-4397-bea9-6eb5d29f4d0c.png">

https://policyengine.org/us/household?focus=householdOutput.mtr&reform=270&region=md&timePeriod=2023&baseline=2&household=225

**Comment by DeepthiSRao** [comment]
@MaxGhenis I can work on this.

**Comment by dotslashbit** [comment]
Please close this as I can see the tab title now shows the reform name
