### ISSUE TITLE
App white-screens

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1647]
On the latest version. I suspect we're missing Auth0 environment variables.

**Comment by MaxGhenis** [comment]
I'm not seeing this, can you give an example?

**Comment by anth-volk** [comment]
I believe this was solved earlier today, though @nikhilwoodruff would need to confirm

**Comment by anth-volk** [comment]
Confirmed by Nikhil that this is closed, having been fixed by #1648.
