### ISSUE TITLE
Add `Enter` and `Esc` button event listeners to username change component on UserProfilePage

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1656]
At the moment, you must click either the checkbox to save a new username or the X to exit, you can't use Enter or Esc. This should change.

**Comment by czhou578** [comment]
How do I get to the UserProfilePage?

**Comment by anth-volk** [comment]
You'll have to update your master branch from upstream. However, there is a major issue at present - due to some .env variables created by those commits, your fork will fail to run anything. That's something we're trying to fix at the moment, so it'd be best if you could hold off on attempts to fix the user auth side (and on updating master) until we can fix that.

**Comment by czhou578** [comment]
Ok! Thanks for letting me know. I can take this issue once that's done.

**Comment by anth-volk** [comment]
Perfect, we'd love to have your contribution on it. Apologies for the issue, we hadn't anticipated it beforehand.

**Comment by anth-volk** [comment]
@czhou578 We should have the contribution issue fixed by tomorrow or Thursday at the latest. I'm going to preemptively assign you to this, but feel free to let me know if you change your mind later in the week.

**Comment by anth-volk** [comment]
Hey @czhou578, with the merging of #1664, you should be able to contribute now by running `git pull upstream master`, assuming you have an upstream connection.

**Comment by czhou578** [comment]
Thank you for the update!
