### ISSUE TITLE
Household calculator's region selection page blanks out the Enter button

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1660]
For some reason, it looks like this:

<img width="1440" alt="Screen Shot 2024-04-29 at 9 23 48 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/73d223b5-9ec5-4943-b64c-a42760e13231">

Though it is an Ant Design button with proper hover effects and it does say "Enter" on it, meaning that the impact appears to be entirely visual.

**Comment by czhou578** [comment]
Hmm, this is what I currently see. I have not updated my master branch on my fork yet. Could it be something related to the .env variables??
![image](https://github.com/PolicyEngine/policyengine-app/assets/42430035/4bb90450-1d29-48d4-95a4-21eae4c6bd1c)

**Comment by anth-volk** [comment]
I think I may have found it, actually. I don't understand what changed, but it appears that we somewhere deleted a color and that some code that was used to disable the button was long deprecated, so both have been fixed in #1662.

Sorry to have not waited for your response, @czhou578, but considering the importance of the fix, I considered it best just to blaze forward. Thanks again for checking in on it.
