### ISSUE TITLE
Remove deprecated `CodeBlock` code and properly reference files

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1678]
At present, `CodeBlock` maintains a deprecated block, while using a less-than-ideal system of importing, then re-exporting, the block used in the API documentation pages. We should clean up this file by doing the following:

1. Moving the API's `CodeBlock` to `CodeBlock.jsx`
2. Getting rid of the old block
3. Re-importing the block into the API documentation page
4. Ensuring that we don't use the old block anywhere
5. The old block depends on a package called "Highlight"; if we don't use that, either, we should uninstall it from the app

**Comment by anmolchhabra21** [comment]
![image](https://github.com/PolicyEngine/policyengine-app/assets/93809908/6780b334-01af-445c-9cc6-00ceaa790671)
I have implemented the changes, updated the imports and removed the `prism-react-renderer` dependency; it was not used/referenced anywhere in the code, and the website was working fine.
