### ISSUE TITLE
Move the "Run the code below" line from the Reproduce in Python pages so that it sits above the code editor

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1690]
<img width="1440" alt="Screen Shot 2024-05-02 at 6 44 43 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/12e1f169-1ffb-4225-98ff-5e94881167bf">

**Comment by psankhe28** [comment]
I've made the required changes and created the PR https://github.com/PolicyEngine/policyengine-app/pull/1706
Please have a look at it

**Comment by anth-volk** [comment]
Thanks @psankhe28, I'll be sure to check them out today.

**Comment by psankhe28** [comment]
Please close this issue @anth-volk as the required changes are done.
Thanks!

**Comment by anth-volk** [comment]
Thanks, fixed by #1690.
