### ISSUE TITLE
Rename "Collapsable" to "Collapsible"

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1693]
I don't think "collapsable" is a word in any English dialect, but if it is, feel free to correct me in this thread.

**Comment by NilanchalaPanda** [comment]
Hey @anth-volk , yes you are correct. The right spelling will be "Collapsible" and not "Collapsable".

**Comment by psankhe28** [comment]
I've made the required changes and created the PR https://github.com/PolicyEngine/policyengine-app/pull/1705
Please have a look at it
