### ISSUE TITLE
Re-add text specifying the API version, indicating that enhanced CPS is experimental

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1694]
This was previously on the `BottomCarousel` component, with a conditional switch displaying the enhanced CPS beta warning message. @nikhilwoodruff I imagine it'd be good to re-add this, but where makes sense in your opinion? Or should it be dropped altogether?

**Comment by MaxGhenis** [comment]
beta not experimental

**Comment by MaxGhenis** [comment]
Let's prioritize this as it would be helpful for a current debugging exercise, and to help our users understand when results might change. I think somewhere at the bottom of the charts makes sense.

**Comment by MaxGhenis** [comment]
For posterity, in the meantime users can view the package version in the AI prompt.

[Example](https://policyengine.org/us/policy?reform=55182&focus=policyOutput.analysis&region=enhanced_us&timePeriod=2024&baseline=2):
<img width="1901" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/742e222a-d577-4450-af06-c7841b792e49">
