### ISSUE TITLE
Remove the junk code within the `submitToMailchimp` function

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1696]
I'm not sure which file it's in at the moment, but there's a large piece of commented code that executes a JSON-P request to Mailchimp. That's present elsewhere and should be removed.

**Comment by anth-volk** [comment]
Thanks @Suvid-Singhal, we really appreciate your contribution. I was out Friday, so didn't have the chance to look it over then, but will review today.

**Comment by Suvid-Singhal** [comment]
Hi @anth-volk,
Could you please review the PR?
All checks are passing now.
Thanks

**Comment by anth-volk** [comment]
Hi @Suvid-Singhal, we want to say that we do appreciate your contributions. That said, we can't always immediately review due to high-priority bugs, improvements, etc. I will try to review today, but even if I can't, don't worry, your PR will be gotten to.

**Comment by Suvid-Singhal** [comment]
Apologies for the hurry.
