### ISSUE TITLE
SignupModal's header font is incorrect

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1699]
This is likely due to the fact that `App.css` only defines the font for h1 through h4 headers, and that modal uses h6. We should either change it to something like h4 or alter `App.css` to define the same font for all headers.

**Comment by rhwd** [comment]
I made a PR for this issue, I would be pleased if you could review it. 
https://github.com/PolicyEngine/policyengine-app/pull/1700
