### ISSUE TITLE
AI prompt doesn't load

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1703]
Example - this shows even when the microsim completes

https://policyengine.org/uk/policy?focus=policyOutput.analysis&reform=3177&region=uk&timePeriod=2024&baseline=1

<img width="1470" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/29560696-c732-48f3-aaff-f9bb054f1bb0">

**Comment by czhou578** [comment]
@anth-volk It seems like in ```Analysis.jsx```, we are not using the openai package at all. I can make the prompt show but the data is hard coded. How is the openai api supposed to be used with regards to this component?

**Comment by anth-volk** [comment]
@czhou578 Thanks for bringing this up. We're actually going to switch over to using a competitor, Claude (per [this discussion](https://github.com/PolicyEngine/policyengine-app/discussions/1551)), so could you hold off until then? We were looking to have Claude implemented by Friday, as it's a high-priority fix, and if you'd like to take that on (or do part and have assistance), you could do so once we have a subscription, which should be by 5PM Eastern US today, and open an issue. Are you interested at all?

**Comment by czhou578** [comment]
Sure. I'll do a part with assistance then. Thanks for letting me know!

**Comment by MaxGhenis** [comment]
I think the prompt can be fixed independently of the Claude switch

**Comment by anth-volk** [comment]
@czhou578 In that case, let me look into it.

**Comment by anth-volk** [comment]
I now better understand the issue at hand here. The prompt itself is hard-coded, which is correct. The API itself is what interacts with OpenAI, so in the code, where you find the API call to `/analysis`, this generates the output. The problem identified in this issue is that the prompt itself isn't output into the `CodeEditor` block.

**Comment by czhou578** [comment]
Makes sense. I'll just make it so that the hard coded prompt shows up in the ```CodeBlock.jsx``` component.
