### ISSUE TITLE
Show API status dashboard from API page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1710]
I think we used to have a URL like https://policyengine.org/us/api-status that embedded https://policyengine.betteruptime.com/ but I don't see it now. Let's embed it directly in https://policyengine.org/us/api

**Comment by czhou578** [comment]
@MaxGhenis, how exactly do you want the embedding to look like? Is there an existing example somewhere on the web app that demonstrates this?

**Comment by MaxGhenis** [comment]
Iframe would be fine, I think @nikhilwoodruff did something like that before

**Comment by anth-volk** [comment]
We actually have a full page that enables this (`src/pages/StatusPage.jsx`), it just wasn't roped into the `react-router` tree. I think getting this going again would be as simple as adding it back in, making sure imports still work properly, and there you go. I had actually intended on working on this myself, but had to do some higher-priority work, so it'd be great to have your contribution here, @czhou578, if you'd be willing.

**Comment by czhou578** [comment]
Ok! I'll take this issue on.
