### ISSUE TITLE
Use PolicyEngine Core Reform.from_dict in policy reproducibility blocks

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1712]
This is a much cleaner syntax that we should switch to.

**Comment by anth-volk** [comment]
Out of curiosity, do we document this code anywhere? If not, would you mind writing out how to do so? I'm not familiar with it myself, and I don't think many of our other contributors are.

**Comment by nikhilwoodruff** [comment]
Sure- I'll add to the Core documentation but it follows the same syntax as the policy JSON objects:

```python
Reform.from_dict({
    "gov.tax.rate": {
        "year:2020:1": 0.2,
        "2024-01-01.2025-01-01": 0.35 // Alternative input
})
