### ISSUE TITLE
The author selection in the Web App does not seem to work

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1726]
I don't think it is actually filtering the articles by author:

https://github.com/PolicyEngine/policyengine-app/assets/110687043/72e67fec-6b38-404d-85f7-e5601d1754c3

**Comment by PavelMakarchuk** [comment]
I actually think that it applies to all of the possible filers

**Comment by anth-volk** [comment]
@psankhe28 Just curious if you were looking to take anything on? This would involve debugging the filter function utilized on the Research page. If not, feel free to let me know and I'll pass it on to someone else.

**Comment by federicopoi** [comment]
Hi! I am new to open source and I want to try figure this issue out if that's okay.

**Comment by anth-volk** [comment]
@federicopoi Thanks for your interest in the project! Please do, we'd love your input. The thread for #1750, at the bottom, includes my own thoughts from earlier in the year as to what's going on here, but suffice it to say that there's probably a few interlocking errors in this code.

**Comment by federicopoi** [comment]
Sounds good! I'm still looking into it. I'll let you know when I have updates or questions. Thank you!

**Comment by samr874** [comment]
@anth-volk @federicopoi @PavelMakarchuk @robgorman @nschonni  what is the status of the contribution is it still active?

**Comment by anth-volk** [comment]
@samr874: This is still active, @federicopoi is still working on it, as he only took on the issue a couple days ago

**Comment by anth-volk** [comment]
Thanks so much @federicopoi! I'll review this later today.
