### ISSUE TITLE
Upgrade to node v22

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1746]
Interestingly, `eslint-plugin-jest` only supports node v18 or v20, not 19

**Comment by MaxGhenis** [comment]
We might consider skipping to Node 22, which is active and will become the long-term support version on October 29: https://github.com/nodejs/release#release-schedule

**Comment by anth-volk** [comment]
If skipping straight to v22 is too much hassle, we could always revert this issue to be about upgrading to v20.
