### ISSUE TITLE
Refactor `Analysis.jsx` so that the prompt sits in its own file

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1751]
This would allow easier editing, easier conditional implementation of various different prompts (if we go that way), etc. Note: This should be done after Friday, May 10.

**Comment by anmolchhabra21** [comment]
I have refactored the Analysis.jsx part to keep the different prompts in a single file named `PromptContent.jsx`, and now the Analysis.jsx has an import to this file, with the rendering logic and frontend. It was working fine on my local:
![image](https://github.com/PolicyEngine/policyengine-app/assets/93809908/4b967a41-4047-4ca3-8166-249a8a4381ac)

But I found out there were some terms like `{{povertyImpact}}` and `{{inequalityImpact}}` in the contents. To check, I headed to the live website https://policyengine.org/us/research/gpt-analysis, and there also was the same, 
Have we kept it intentionally? I was just not sure if we wanted to change it. Please let me know if we need to update that part, and then I can include that in my PR. Here is its related image in the live website:
![image](https://github.com/PolicyEngine/policyengine-app/assets/93809908/eb80ee9e-46f1-4d98-b005-255f1f5643ea)

**Comment by MaxGhenis** [comment]
Yes it's intentional. We replace them with charts.

**Comment by anth-volk** [comment]
Yeah, echoing Max, you can keep those exactly as they are.
