### ISSUE TITLE
Reform stacking

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1755]
For example, to model a reform with CBO labor supply responses, you either have to enter each elasticity, or use the shortcut parameter to flip them all on. It'd be cleaner to be able to "stack" the `CBO Labor Supply Responses` reform atop the current reform. This would also better support attaching alternative labor supply response assumption sets.

As another example, suppose you want to add Romney's Family Security Act to a carbon dividend.

We'll have to check for "merge conflicts" here.

**Comment by anth-volk** [comment]
Could you go a bit more in-depth on what you mean by "stacking" and how this might work within the app itself? Like, do you envision a particular toggle added somewhere? Or a broader functionality that requires more planning from a UX perspective?

**Comment by MaxGhenis** [comment]
Currently if you already have a reform selected/defined, selecting a new policy overwrites the existing one.

<img width="454" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/d2d3c7cf-d525-46c4-acbd-d01089913c32">

Suppose a user instead wants to add a policy atop what they've defined. Could add a Stack policy button in this flow:
<img width="460" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/bb52fc44-b99f-4dc4-8f93-39e0e2404cec">

**Comment by anth-volk** [comment]
Ah, I see, this applies specifically to use cases where a user selects a pre-defined, named policy, then wants to add another pre-defined, named policy to it.

**Comment by anth-volk** [comment]
Created a mockup for a potential implementation of this. Note that the plus button below would either be disabled or not displayed if the user's currently on `Current law`.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/d42c2dd8-7ff4-42ff-9bd0-ecbf688c2303

**Comment by MaxGhenis** [comment]
great!
