### ISSUE TITLE
Buttons in household calculator are sized improperly

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1757]
The video below demonstrates how the calculator is currently functioning. Ideally, the first three buttons (which are almost certainly imported from `/src/controls/Button.jsx`) should have a set width that matches the one inside `src/pages/household/input/VariableEditor.jsx`. These buttons are made to by default sit at 100% width, and so it's likely as simple as copying and pasting the set width value from `VariableEditor` into the three relevant pages with the incorrectly sized button.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/1c4bd9ca-c707-4b24-ac61-1eaf414bfc89

**Comment by psankhe28** [comment]
Do we prefer 100% width button or the smaller ones?

**Comment by anth-volk** [comment]
The smaller ones
