### ISSUE TITLE
Fix decile LSR subtitle

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1791]
Both relative and average charts say:
>This chart shows the estimated relative change in earnings (as a percentage of market income) for each disposable income decile, and split by the substitution and income effects.

I'd suggest a few changes:
1. Change to percentage of earnings (is this what the data actually is? this would indicate relative changes more accurately than market income)
2. Remove the relative part from the average one since it's dollars
3. Relabel Average to Absolute
4. Move it below the chart (I'd suggest we do this with all chart descriptions that don't add additional numbers)

**Comment by anth-volk** [comment]
I don't see any relative part on the average one. Am I missing something?
<img width="1438" alt="Screen Shot 2024-05-24 at 3 12 50 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/779e9794-5d01-4e4f-b4db-cabc389473d2">

**Comment by MaxGhenis** [comment]
>as a percentage of market income

then shows $ not % values
