### ISSUE TITLE
Fix LSR decile data labels

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1792]
Relative ones should round like the y axis does
<img width="876" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/59416558-97c4-42bc-b83f-e5ff33018af9">

Absolute should be in dollars not %
<img width="871" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/14332c76-1929-4a5b-ac23-6079fc6a9299">

**Comment by anth-volk** [comment]
It appears that the y-axis labels are also a bit strange. Is there any interest in displaying two fractional digits if the max displayed y-axis value is below 1% (or above -1%), otherwise just 1?
