### ISSUE TITLE
Increase the height of the user profile picture on the navbar to match the COMPUTE POLICY IMPACT button

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1811]
In a recent reskin, the COMPUTE POLICY IMPACT button gained a slight bit of padding, making it just slightly larger than the user profile picture. As such, the profile image should be increased (height and width) to match it.

**Comment by CallMeMaverick** [comment]
@anth-volk , I have created a pull request to address this issue. I also noticed some discrepancies with the hamburger's size, so I fixed it.

You can review the pull request here: [#1819 ](https://github.com/PolicyEngine/policyengine-app/pull/1819)

Thank you!

**Comment by anth-volk** [comment]
@CallMeMaverick Thanks for your contribution on this! Will review either Monday or Tuesday. Thanks for your patience.
