### ISSUE TITLE
Labor supply chart pages display "undefined" as part of their title

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1813]
Per the image below, when a user visits one of the labor supply chart output pages in the policy calculator, the page title looks like this:

<img width="202" alt="Screen Shot 2024-05-23 at 11 18 46 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/ac4e67c6-304a-4061-9a2f-6b53187c6d05">

**Comment by Suvid-Singhal** [comment]
So what should be displayed in the page title ideally?

**Comment by anth-volk** [comment]
If you look in `src/pages/policy/output/tree.js`, there are two items: `policyOutputs`, which defines the various titles, and `getPolicyOutputTree`, which defines the structure the pages are displayed in within the left-hand sidebar. The titles should be added to `policyOutputs`, and for any page where the output is `undefined` currently, the titles should mirror those already in `policyOutputs`; so, for example, on `policyOutput.laborSupplyImpact.byDecile.relative`, it should be `Labor supply impact by decile (relative)`. Ideally, these titles should also all be sanitized to fit regional spelling: they should be "labor" in the US and Canada and "labour" in the UK.
