### ISSUE TITLE
Restructure LSR sections

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1825]
Let's reorganize into:
* Work hours
  * Overall
  * By income decile
    * Total
    * Income effect
    * Substitution effect
* Earnings
  * Overall
  * By income decile
    * Total
    * Income effect
    * Substitution effect

**Comment by anth-volk** [comment]
Happy to do this, though we don't currently break out work hours into income deciles, and my understanding is that this also isn't present in the API. I feel that should be a separate issue, as it'll likely require API work first.
