### ISSUE TITLE
API status page has overwritten the route the API documentation page exists at

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1837]
This is a regression introduced by #1816. The API status page should have a different route, something like `/api_status`, so as to prevent this situation.

**Comment by anth-volk** [comment]
@czhou578 Would you be interested in this issue at all?

**Comment by anth-volk** [comment]
Essentially, the API documentation page, linked via the last "Explore the Documentation" button on the homepage, should be at the `/api` route, not the status page.

**Comment by czhou578** [comment]
Ok. I'll do this one!
