### ISSUE TITLE
UK Terms of Service page describes us as following US law

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1849]
If this is inaccurate (I'm assuming it is for the UK app), we should update this to say UK law. 

<img width="1440" alt="Screen Shot 2024-06-03 at 4 23 32 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/38cd2e4e-3ba0-44ac-84ee-0bfcd1f87645">

**Comment by anth-volk** [comment]
To fix this, we would need a custom hook, `useCountryId`, to define what country name to put in this spot in the text.

**Comment by KellyLyXie** [comment]
Fixes and opens the pull request #1948
