### ISSUE TITLE
Describe ECPS in prompt when used

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1856]
Something like:
>This analysis uses PolicyEngine's Enhanced CPS, constructed from the 2022 Current Population Survey and the 2015 IRS Public Use File, and calibrated to tax, benefit, income, and demographic aggregates.

**Comment by anth-volk** [comment]
To be clear for any contributor - this would involve adding a check to determine whether or not the `enhanced_cps` region is used, and if it is, displaying the text above in the AI component's output, triggered by editing the prompt

**Comment by bharateshwq** [comment]
Hey @anth-volk,
I was looking into this issue and noticed that on the AI summary page there are multiple places where the user gets to know enhanced CPS is being used. 
The Bottom info element (LowLevelDisplay)
The prompt output itself specifies that enhanced CPS is being used

Is it necessary to have more indicators

**Comment by anth-volk** [comment]
Thanks for your comment @bharateshwq. I would say that, if we already have a reference to it in the AI output, then we should expand a bit more on it, using the wording from above.
