### ISSUE TITLE
Enable Calculate Economic Impact when comparing current law (as reform) against a custom baseline

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1859]
We currently disable `Calculate Economic Impact` when the reform is the current law. Let's also enable it in the case where the reform is the current law but the baseline is not. This is the user journey for, for instance, calculating the effect of the EITC.

As a workaround, users can define the reform, calculate economic impact, then swap baseline and reform to trigger recalculation.

**Comment by anth-volk** [comment]
For anyone curious, the reason this is happening is likely that the code currently prevents simulations to be run when `Current law` is the active policy. This was created to prevent a situation where someone ran a simulation of `Current law` against `Current law`, but clearly this implementation didn't anticipate a situation where a custom baseline was input.
