### ISSUE TITLE
Move default year "onwards" in parameter editor to the next calendar year

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#1863]
I think this makes more sense and is a more common use-case- plus it's guaranteed to capture any mid-year parameter changes.

cc @MaxGhenis @anth-volk

**Comment by MaxGhenis** [comment]
Like 2025 onward today? The large majority of users in the US model changes from 2024 onward.

**Comment by anth-volk** [comment]
Yeah, this seems to me to present many drawbacks. What is the benefit? And is it specific to the UK?

**Comment by anth-volk** [comment]
I would recommend closing this, pending confirmation from others

**Comment by anth-volk** [comment]
Closing
