### ISSUE TITLE
Fix visual effect on collapsible panels

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1882]
Love the new feature but it's a bit cramped

<img width="119" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/824d4c1c-457b-440f-b938-7475f55dcdd7">

**Comment by anth-volk** [comment]
This text is actually not supposed to look like that. It's supposed to look like this:

<img width="1440" alt="Screen Shot 2024-06-17 at 8 24 31 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/8dc2c10c-6bbd-4211-9bdf-92db8bf2e824">

Which browser are you on? Safari?

**Comment by MaxGhenis** [comment]
chrome
