### ISSUE TITLE
Missing newline between hours worked subtitle and chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1884]
<img width="1470" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/53195170-b6a4-47b3-975a-34fb046979f8">

https://policyengine.org/us/policy?reform=53757&focus=policyOutput.laborSupplyImpact.hours&region=enhanced_us&timePeriod=2024&baseline=2

**Comment by anth-volk** [comment]
Note: This is browser-dependent; not visible in Firefox, but is in Safari
