### ISSUE TITLE
Shrink the increment for household charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#19]
Currently $2k, which hides cliffs

Does this go in `app` or `api`?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/6076111/205174391-4ba5ab27-f1bf-497b-9ef5-c03b3d4e8e8a.png">

**Comment by nikhilwoodruff** [comment]
Thanks - `app`

**Comment by nikhilwoodruff** [comment]
We're now at £500, that OK?
