### ISSUE TITLE
Add title for manifesto app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1916]
Currently it previews as 2024-manifestos 
<img width="601" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/8e328396-c8c2-496f-a213-9bd8d0081037">

**Comment by anth-volk** [comment]
This is likely an issue with the manifesto's social card, as the page's title is `UK 2024 Manifestos Comparison | PolicyEngine`
