### ISSUE TITLE
Add full info on Ben Gross to authors.json

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1927]

**Comment by kartikeysharma98281** [comment]
hi, @MaxGhenis  can assign this issue to me

**Comment by kartikeysharma98281** [comment]
I have added my contribution please give it a look

**Comment by anth-volk** [comment]
@MaxGhenis Does "full info" refer to a bio that Ben Gross has prepared? If not, might make sense to rope him in here?

**Comment by MaxGhenis** [comment]
Parity with other authors

**Comment by anth-volk** [comment]
It appears that Ben Gross's full info is already present. For example, he's listed as an author on the article at https://policyengine.org/us/research/niskanen-center-analysis. The only thing he doesn't have that other authors do is a GitHub.
