### ISSUE TITLE
Second set of navigation arrows present on mobile

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#1945]
See https://www.loom.com/share/93897aa39c9c4cfc8e6646e50cebf333 - the set of arrows that is present in the middle of the page should not be

**Comment by anth-volk** [comment]
This is related to #1814

**Comment by rachel-lawrie** [comment]
Deleted duplicate ticket and moving loom from that ticket here. https://www.loom.com/share/da516a7ee6b9447ca3e71f75eb18408c?sid=0cb059cc-547b-4f23-a4b3-39c54c415bbb

**Comment by rachel-lawrie** [comment]
@anth-volk can you assign me or give me access to assign myself?

**Comment by rachel-lawrie** [comment]
@anth-volk @MaxGhenis -- Is there any mobile view that we want the carousel in? I tried to explore all options on the site and I think the answer is no, so I am adding !mobile && (<Bottom Carousel> ...) logic. But I want to make sure I'm not missing any view where we actually want the carousel for mobile.

**Comment by MaxGhenis** [comment]
I think a menu would be more mobile-friendly

**Comment by anth-volk** [comment]
Agreed, and if referring to the `BottomCarousel` component specifically, I think that was accidentally added, anyway, and thus never intended to be there.

**Comment by rachel-lawrie** [comment]
PR here: https://github.com/PolicyEngine/policyengine-app/pull/1970
