### ISSUE TITLE
Remove carousel in mobile view

### ISSUE THREAD

**Issue by rachel-lawrie** [PolicyEngine/policyengine-app#1954]
Carousel looks weird in mobile view. Redundant with MobileBottomNavButtons. Creates cut-off text as well.

https://www.loom.com/share/da516a7ee6b9447ca3e71f75eb18408c?sid=0cb059cc-547b-4f23-a4b3-39c54c415bbb

**Comment by anth-volk** [comment]
Is this a duplicate of #1945?

**Comment by rachel-lawrie** [comment]
Duplicate of #1945
