### ISSUE TITLE
Require clicking to activate profile drop-down

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#1958]
The activation via hover is inconsistent with the hamburger next door, and also inconsistent with other upper-right profile UX I've seen (e.g., GitHub and Google)

**Comment by bharateshwq** [comment]
having a look at github i feel that onHover should be changed to onclick for the profile and hamburger should be left as is

**Comment by anth-volk** [comment]
@bharateshwq I believe that's exactly what Max is saying, no? Agreed, though, it makes more sense.

**Comment by bharateshwq** [comment]
Yes, that's exactly what @MaxGhenis  was suggesting. I wanted to ensure I hadn’t misunderstood Max's point and that we're all on the same page.

I’ll move forward with the update and let you know once the pull request is ready for review.
