### ISSUE TITLE
Remove "[reform] does not change your market income"

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#198]
This implies we're applying an elasticity

**Comment by Felix-Cadiz** [comment]
When searching through the codebase, I could not find "[reform] does not change your _market income._" Was this a typo that was meant to be "_marginal tax rate_" or "_net income_?"

**Comment by MaxGhenis** [comment]
Looks like this has been fixed, but see the related https://github.com/PolicyEngine/policyengine-app/issues/276
