### ISSUE TITLE
Multiple Logos show up as "undefined logo" in the US main app

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#1984]
![image](https://github.com/user-attachments/assets/075df8f8-3aad-4c99-99d6-42c6a2623ca6)

**Comment by PavelMakarchuk** [comment]
![image](https://github.com/user-attachments/assets/8d34f2c1-bf12-4185-8ea0-7383086638be)

**Comment by tawandamoyo** [comment]
The two logos are commented out, and the organizations removed, most recently as per #1979 but the quotes and headshots remain. Should I just readd them @MaxGhenis since I see you removed Gary Community Ventures?
