### ISSUE TITLE
Discrepancy between results from web app and Python package

### ISSUE THREAD

**Issue by leehengpan** [PolicyEngine/policyengine-app#1993]
I have found the following instance to have different results between the web app and the Python package.

State: Florida
Head income: 50,000
Head Not disabled
1 disabled 5 y/o child
1 not disabled 3 y/o child

Web app result: https://policyengine.org/us/household?focus=householdOutput.netIncome&household=46661
<img width="678" alt="Screenshot 2024-08-23 at 2 51 59 PM" src="https://github.com/user-attachments/assets/8b29229d-9992-4ce3-9054-71600fc06ee0">

Python package result:
```
Net Income: 49562
Benefits: 1214
Refundable credits: 2173
Tax Before Refundable Credits: 3825
```

**Comment by MaxGhenis** [comment]
Could you link a colab notebook showing this? It's straight from the reproduce in python?

**Comment by leehengpan** [comment]
Yes, it's straight from the "reproduce in Python" tab in the web app.

Here is the notebook: https://drive.google.com/file/d/168mCRJNL2ryQ0gFQgNBg6rEAVsK1EWSu/view?usp=sharing

**Comment by MaxGhenis** [comment]
Please link a Colab notebook to verify it's the same version as in the app

**Comment by leehengpan** [comment]
https://colab.research.google.com/drive/1NX-3Q51JcFs7Te9K3DSiv5fV8jbTh4gI?usp=sharing

I am getting the correct results after using the version 1.61.0.
