### ISSUE TITLE
SALT cap parameter is only displayed for 2018

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#2033]
The [salt cap parameter](https://policyengine.org/us/policy?focus=gov.irs.deductions.itemized.salt_and_real_estate.cap.HEAD_OF_HOUSEHOLD) only shows a value for 2018 but it should be continuous until 2026:
![image](https://github.com/user-attachments/assets/e4ce96b7-9c6b-4519-9faf-dd153649ef58)
 
 I suspect it is because we set the parameter to the same rate in two consecutive years in the [parameter file](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/irs/deductions/itemized/salt_and_real_estate/cap.yaml#L13)

**Comment by MaxGhenis** [comment]
May be an instance of #2051

**Comment by PavelMakarchuk** [comment]
> May be an instance of #2051 

Yes, very possible, will close issue for now
