### ISSUE TITLE
Estimated runtime has duplicate phrasing

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#2034]
Shown here:

<img width="620" alt="image" src="https://github.com/user-attachments/assets/55f21007-1999-4893-b586-4d82d786e771">

**Comment by anth-volk** [comment]
As part of this, it'd be great if we could replace our use of `momentjs` with something else, as it is deprecated (e.g., https://terodox.tech/migrating-away-from-momentjs-part1/)
