### ISSUE TITLE
Page Crashes when clicked on marginal tax rates

### ISSUE THREAD

**Issue by bharateshwq** [PolicyEngine/policyengine-app#2039]
Below video demonstrates the issue

https://github.com/user-attachments/assets/0a5bc7cf-ae4b-4721-adce-c93f105a2eca

householdData.people.you.employment_income is undefined
./src/pages/household/output/MarginalTaxRates.jsx/MarginalTaxRates/<@http://localhost:3000/static/js/src_pages_HouseholdPage_jsx.chunk.js:4373:5
commitHookEffectListMount@http://localhost:3000/static/js/bundle.js:391313:30
commitPassiveMountOnFiber@http://localhost:3000/static/js/bundle.js:392806:42

Could reproduce this in chrome and firefox

**Comment by MaxGhenis** [comment]
Thanks - we expect users to go through the questionnaire first, but should default values to zero for cases where they skip.
