### ISSUE TITLE
Add version disclaimer tag to either start or end of article

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#2068]
Ideally, this would say the version of the country package used to model the data within the article and add a disclaimer that the data was accurate at the time of publication, but subsequent model updates may have altered the data present within the app. This could be based upon metadata, and whenever an article is updated, perhaps this could be changed.

**Comment by MaxGhenis** [comment]
This is what I had in mind with #2059

**Comment by anth-volk** [comment]
Gotcha. I'll close this, but I think we should also add disclaimer text using that info.
