### ISSUE TITLE
11th decile displayed for certain reforms 

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-app#2101]
Not sure if this issue was raised previously but for some of our structural reforms we return 
Example [reform](https://policyengine.org/us/policy?reform=68397&focus=policyOutput.distributionalImpact.incomeDecile.average&region=enhanced_us&timePeriod=2026&baseline=2):
![image](https://github.com/user-attachments/assets/1a6ec2e5-3406-46f3-909f-3ac20666b654)

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk Is there any chance these reforms manipulate the household income decile variable?

I dont think so, it is the TCJA reform and it is just a parameter reform

**Comment by MaxGhenis** [comment]
See https://github.com/PolicyEngine/policyengine-uk/issues/944

**Comment by anth-volk** [comment]
Ugh, sounds like `-api`

**Comment by anth-volk** [comment]
This should be fixed following the workflow laid out in https://github.com/PSLmodels/microdf/pull/237. Basically, we need to get updates to `microdf` fully pushed onto PyPI, then update `-us` and `-uk` before this can be resolved.
