### ISSUE TITLE
Clarify current private school fee VAT policy in post

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#2131]
Currently says `raise` which implies it's a lower nonzero rate today, but they're exempt. @vahid-ahmadi fyi

https://policyengine.org/uk/research/school-vat

**Comment by vahid-ahmadi** [comment]
@anth-volk 
Yes, it is done. Thanks!

**Comment by anth-volk** [comment]
@vahid-ahmadi Thank you very much

Closed by #2134.
