### ISSUE TITLE
Let users select a year in the household calculator

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#218]
This is especially valuable now as users may want to use PolicyEngine to estimate 2022 taxes. We only allow 2023 inputs.

A campaign to help people claim the Washington Working Families Tax Credit prompted this.

**Comment by MaxGhenis** [comment]
Let's prioritize this, given more users are looking to 2024 simulations this month, and those looking for help with 2023 taxes will want it starting in January.

**Comment by anth-volk** [comment]
Looking at mocking this up early next week. Which do you think is preferable: a complete page in the household flow to select a year, or a method by which a user would opt out of the current year?

**Comment by MaxGhenis** [comment]
The latter - let's default to current year

**Comment by anth-volk** [comment]
For clarification, we're looking for this for both the household and policy reform calculators, right?

**Comment by anth-volk** [comment]
Also, as a side note, I'm looking to solve this after #1017, as solving and pushing that will make this simpler

**Comment by anth-volk** [comment]
I think one option (which fits more with these specifications) would be to do something like this, which is just roughly worked up here:
<img width="1440" alt="Screen Shot 2023-12-26 at 3 28 53 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/167bbe37-7745-4e30-bc7e-7c0e346e3999">

Another is to build a separate "year" input screen before all the other ones. The latter feels more intuitive, given the flow, but the former can be done. I just think it wouldn't be prudent to put it on the right-hand panel, akin to the policy reform calculator, as that feels unintuitive from a user perspective.

**Comment by MaxGhenis** [comment]
Either works as part of the questionnaire - let's start by only allowing 2021-2024

**Comment by MaxGhenis** [comment]
Congress is reportedly exploring retroactive reforms to 2023 tax rules, in particular the Child Tax Credit. So this just became more important, as it would allow us to show the impacts to specific households. A key policy parameter changed from 2023 to 2024 (the Additional Child Tax Credit rose from $1,600 to $1,700) so this is pretty critical--policy conversations are moving fast so let's make this a top priority.

**Comment by anth-volk** [comment]
For sure. #1145 should enable this feature, it just needs added tests, which requires the merging of a different PR that I mentioned in the comments #1145, followed by the actual test writing and fixes.
