### ISSUE TITLE
Upload 2025 IRS update press release

### ISSUE THREAD

**Issue by DTrim99** [PolicyEngine/policyengine-app#2209]
irs-2025-update

**Comment by MaxGhenis** [comment]
https://blog.policyengine.org/federal-tax-inflation-adjustments-for-tax-year-2025-6ba6ce84f0a8

Table:

| Filing Status | 2024 Value | CBO Forecast | 2025 Value | Difference |
|--------------|------------|--------------|------------|------------|
| Single and Separate | $14,600 | $14,950 | $15,000 | +$50 |
| Head of Household | $21,900 | $22,450 | $22,500 | +$50 |
| Joint and Surviving Spouse | $29,200 | $29,900 | $30,000 | +$100 |
