### ISSUE TITLE
Make subscribe button have the same styling as other buttons

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#223]

**Comment by PGrad** [comment]
Just to clarify, when you say that button should have the same styling, do you want it to be in the primary style or secondary?

**Comment by nikhilwoodruff** [comment]
Ah, to be fair I think either would work but probably secondary is best given the other call-to-actions on the page.

**Comment by anth-volk** [comment]
This is no longer present post-redesign. Closing.
