### ISSUE TITLE
Add Medium blog posts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#24]
https://towardsdatascience.com/converting-medium-posts-to-markdown-for-your-blog-5d6830408467

**Comment by nikhilwoodruff** [comment]
Made a start, added the Markdown files, now just need to add the metadata to posts.json and authors.json. Been putting off the full backdate because it's a lot of manual typing and I'd rather not if copilot/gpt3 can do it in 10 seconds :)
