### ISSUE TITLE
No OK button on Nigeria modal

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#240]
You have to hit Escape to view results

<img width="710" alt="image" src="https://user-images.githubusercontent.com/6076111/218262956-d71cc375-50cd-4d6a-a47b-638b3f6bd674.png">

**Comment by nehashinde9918** [comment]
I'll start with this

**Comment by nikhilwoodruff** [comment]
Hi @nehashinde9918 - still OK on this? LMK if you need any guidance.

**Comment by anth-volk** [comment]
This is no longer present post-redesign. Closing.
