### ISSUE TITLE
Add JavaScript formatting to `make format`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#274]

**Comment by MaxGhenis** [comment]
Can we add `npx prettier --write *` to do this @nikhilwoodruff?

**Comment by anth-volk** [comment]
Also mentioned in #865

**Comment by nikhilwoodruff** [comment]
I think `npm run fix` should work here?

**Comment by anth-volk** [comment]
Completed via #902. Closing.
