### ISSUE TITLE
API text section on homepage is misaligned on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#286]
Also maybe we should hide it on mobile, it's wide

<img width="304" alt="image" src="https://user-images.githubusercontent.com/6076111/222319235-4fbf1214-9cc7-4c50-ac09-49fa7b70a5d9.png">

**Comment by DeepthiSRao** [comment]
@MaxGhenis I can work on this.

**Comment by anth-volk** [comment]
No longer present post-redesign. Closing.
