### ISSUE TITLE
Specify that x axis on net income and MTR charts refer to household head

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#287]
Currently some users misinterpret it as household earnings, rather than household head earnings holding all else (including spousal earnings) constant

**Comment by DeepthiSRao** [comment]
@MaxGhenis I can work on this.

**Comment by MaxGhenis** [comment]
We now specify `Household head employment income`
<img width="792" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/3cdb3a4c-27b4-425e-bded-26eb11654d69">
<img width="846" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/9257ea9d-a956-4d35-ae28-ecca371ea5d6">
