### ISSUE TITLE
Mysterious extra income in household screen

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#289]
This happened creating a household yesterday

https://policyengine.org/us/household?focus=input.household.age&household=8643

<img width="855" alt="image" src="https://user-images.githubusercontent.com/6076111/222330048-47e179cc-552d-4bc4-a356-30db8ae3f2c0.png">
<img width="884" alt="image" src="https://user-images.githubusercontent.com/6076111/222330074-7101753a-f69d-4ded-8b3a-d3b3dcc96cda.png">

**Comment by anth-volk** [comment]
@nikhilwoodruff Any reports of this since the redesign?
