### ISSUE TITLE
Add Donate page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#30]

**Comment by nikhilwoodruff** [comment]
What should go on it?

**Comment by MaxGhenis** [comment]
How about this?
>You can support PolicyEngine's work by donating through our fiscal sponsor, the [PSL Foundation](https://psl-foundation.org).

>[**Donate by credit card here**](https://opencollective.com/psl-foundation) or [email the PSL Foundation for other options](mailto:jason.debacker@psl-foundation.org). Please [email us](mailto:hello@policyengine.org) or the PSL Foundation when you've donated to ensure your gift is directed to PolicyEngine.

>Your donation is tax-deductible in the US.
