### ISSUE TITLE
Use different color for tax on net income breakdown screen

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#318]
e.g. red

Thanks to @xudonglai0426 for the suggestion!

**Comment by martinyis** [comment]
Hi, I would like to work on it, where does this breakdown screen located in the files?

**Comment by MaxGhenis** [comment]
Thanks @martinyis! Here it is: https://github.com/PolicyEngine/policyengine-app/blob/master/src/pages/household/output/NetIncomeBreakdown.jsx

On second thought, we don't currently use red anywhere, so I think the more consistent scheme would be dark green for the benefits and refundable tax credits, and dark gray for taxes.

**Comment by martinyis** [comment]
Don't you already have dark_grey colors everywhere in the net income breakdown screen?

**Comment by MaxGhenis** [comment]
Yeah so just changing the positives to green then

**Comment by PGrad** [comment]
Sorry but I'm already working on this issue with PR #344 .
![PolicyEngineArrows](https://user-images.githubusercontent.com/117248915/226213071-611f8f55-e77e-4620-ba28-2ee208568c98.png)
The color scheme I'm using is dark green for benefits/tax credits and red for taxes.
