### ISSUE TITLE
Add decimal point to inequality y axis

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#323]
Until we can set them dynamically, many policy reforms have inequality impacts below 1%

**Comment by leonali030** [comment]
@nikhilwoodruff can you tell me want parameter I should select to display the inequality chart? 
When after select a random parameter and clicking on "Income inequality impact" button, I see the below error:
Comparison - Error computing baseline or reform economy.

**Comment by nikhilwoodruff** [comment]
Hmm that sounds odd- could you share a link that does that? Seems to work ok for me.
