### ISSUE TITLE
`DISABLE_ESLINT_PLUGIN` in package.json for Windows users

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#324]
A Windows user hit this issue when running the app:
```
> policyengine-app@0.1.0 start
> DISABLE_ESLINT_PLUGIN=true react-scripts start

'DISABLE_ESLINT_PLUGIN' is not recognized as an internal or external command,
operable program or batch file.
```
They found that adding the below snippet to `package.json` fixed it:
```json
"scripts": {
    "start": "set DISABLE_ESLINT_PLUGIN=true && react-scripts start",
    "build": "set DISABLE_ESLINT_PLUGIN=true && react-scripts build",
```

**Comment by Cipnuvofli** [comment]
For the sake of clarification and as the user in question, this snippet is intended as a reference. As in change the contents of start and build to match the snippet. My apologies for the confusion.
