### ISSUE TITLE
Testimonials don't properly format apostrophes

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#345]
![image](https://user-images.githubusercontent.com/35577657/226412464-5bcfeea9-ede9-45ba-83d8-8ad2b6a478d3.png)

**Comment by omernadeem1070** [comment]
Hello, I'd like to take care of this issue. Thanks.

**Comment by robgorman** [comment]
Please assign to me

**Comment by nikhilwoodruff** [comment]
Done- thanks @robgorman!
