### ISSUE TITLE
Remove cliffs from legend

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#348]
We could probably remove the whole legend in most if not all cases, but cliffs are especially unnecessary
<img width="533" alt="image" src="https://user-images.githubusercontent.com/6076111/226509771-fbabcb74-b793-4ac0-9d54-684bf6b924c3.png">

**Comment by vedantchourey** [comment]
Hey Max , I'm newbie but I think I can start from this one , can you assign me this issue .

**Comment by MaxGhenis** [comment]
Hi @vedantchourey, sure I added you to the repo so can assign you once you accept. Thanks!

**Comment by vedantchourey** [comment]
Hey Thanks , accepted the repo Max.
