### ISSUE TITLE
Include option for earnings variation in `Reproduce in Python` code

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#349]
The current household `Reproduce in Python` code only shows the net income tree.

Creating the data behind the earnings variation chart requires modifying the code to
1. Remove `employment_income` from all household members
2. Add `'axes': [[dict(name="employment_income", count=201, min=0, max=200_000)]]`

[This notebook](https://colab.research.google.com/drive/1IFRAJQRzTPGuDcKGvNeKEi_EJTlwoCXV?usp=sharing) shows an example.

A tabbed layout could show each separately, or if there's an easy way to switch between these uses in Python we can have the default include both.

**Comment by nikhilwoodruff** [comment]
@jacky5124

**Comment by jacky5124** [comment]
Was fixed by pull request #474
