### ISSUE TITLE
Update actions

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#380]
Should fix this [deploy](https://github.com/PolicyEngine/policyengine-app/actions/runs/4527910370) warning

 
--
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.Show less
 

<br class="Apple-interchange-newline">

**Comment by leonali030** [comment]
looking into this issue

**Comment by nikhilwoodruff** [comment]
Think this is now fixed.
