### ISSUE TITLE
Include in GPT prompt the baseline values of any parameters that the reform modifies

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#382]
We only show this:
>This JSON snippet describes the baseline and reform policies being compared: {"baseline":{"data":{},"label":"Current law","id":"2"},"reform":{"data":{"gov.irs.credits.eitc.eligibility.age.max":{"2023-01-01.2028-12-31":"100"},"gov.irs.credits.eitc.eligibility.age.min":{"2023-01-01.2028-12-31":"19"},"gov.irs.credits.eitc.eligibility.separate_filer":{"2023-01-01.2028-12-31":false},"gov.irs.credits.eitc.max[0].amount":{"2023-01-01.2028-12-31":"1502"},"gov.irs.credits.eitc.phase_in_rate[0].amount":{"2023-01-01.2028-12-31":0.153},"gov.irs.credits.eitc.phase_out.rate[0].amount":{"2023-01-01.2028-12-31":0.153},"gov.irs.credits.eitc.phase_out.start[0].amount":{"2023-01-01.2028-12-31":"11610"}},"label":"Restoring the ARPA EITC","id":"6524"}}

So GPT doesn't know what parameters have changed from, leading to results like this:

> The maximum age for childless Earned Income Tax Credit (EITC) eligibility is increased to 100.
> The minimum age for childless EITC eligibility is lowered to 19.
> Separate filers become ineligible for EITC.
> The maximum credit amount for childless individuals is raised to $1,502.
> The phase-in rate for childless individuals is set at 15.3%.
> The phase-out rate for childless individuals is set at 15.3%.
> The phase-out start amount for childless individuals is increased to $11,610.

**Comment by nikhilwoodruff** [comment]
Was this generated with GPT-3.5? In our original GPT integration launch post, it stated the baseline values (because we passed in the values in the policy parameters snippet.

> The “Restoring the ARPA EITC” policy reform aims to change several provisions of the Earned Income Tax Credit (EITC) for the year 2023. This analysis is based on PolicyEngine US v0.243.0 and the 2021 Current Population Survey March Supplement microdata.
> 
> First, the reform raises the maximum EITC amount for childless filers from $560 to $1,502. Second, the phase-in and phase-out rates for childless filers are set to 15.3%, up from 7.65%. The phase-in rate is the rate at which the EITC increases as a taxpayer’s earnings rise, while the phase-out rate determines how quickly the credit is reduced as income increases beyond a certain point. Third, the reform raises the income threshold at which the phase-out begins for childless filers from $9,160 to $11,610. Fourth, it lowers the minimum eligibility age for childless filers from 25 to 19 years old and removes the maximum age limit. Lastly, the reform allows separate filers to be eligible for the EITC, a provision that was not present under current law.

**Comment by MaxGhenis** [comment]
I think it just knew what the parameters were because it happened to know about current law, but it won't always so I think we should tell it. It was gpt4.

**Comment by nikhilwoodruff** [comment]
Done now but for reference it did actually have the baseline values in the prompt (they're now in both the 'default parameters' JSON and the 'relevant parameter JSON')
