### ISSUE TITLE
Bullets in GPT result are too indented and small

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#400]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/6076111/228317889-ccbb5fe8-ba44-4435-9524-627cef870a1e.png">

**Comment by martinyis** [comment]
I would like to work on this issue
Just a few clarifications
-are you talking about the bullets which are on the top of the picture or bottom
-and how can i navigate on the website to see this page (file as well)

**Comment by MaxGhenis** [comment]
Thanks @martinyis! We should reformat all the bullets to be the same font as the main text, with normal indentation (bullets aligned to main text and a bit left-indented from there).

Generating a wonk mode analysis from [this reform](https://policyengine.org/us/policy?focus=policyOutput.analysis&reform=6524&region=us&timePeriod=2023&baseline=2) will likely produce the issue.
