### ISSUE TITLE
Make policy customizations proper drop-downs

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#41]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/6076111/206267550-6c21c2e4-f27e-45b7-8e34-d3bda9df8f6d.png">

**Comment by nikhilwoodruff** [comment]
What does this mean again?

**Comment by MaxGhenis** [comment]
I think the current UI (light gray font in an open text field) typically implies a hint rather than the actual value that can be changed. Ant calls it [AutoComplete](https://ant.design/components/auto-complete):
<img width="527" alt="image" src="https://user-images.githubusercontent.com/6076111/208108031-56c87417-d37b-41ee-a77f-95b6245b9c6f.png">

I think what we want for each of these is what Ant calls a [Select component](https://ant.design/components/select) with a default value and search field upon activation:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/6076111/208108314-bf88f738-16ae-471c-87c3-ea440e94323a.png">

**Comment by nikhilwoodruff** [comment]
Should be fixed now
