### ISSUE TITLE
Continue the flow after the initial household screens

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#42]
When users enter household info (marital status, children, state, earnings), the `Enter` button currently takes them back to the initial screen.

How about this page showing them two pages: `Enter more information` or `See your net income`? Or it could even take them to the Overview (net income) page immediately.

**Comment by MaxGhenis** [comment]
Jesse suggested just showing results immediately as long as it's clear they can add more info, which the right sidebar probably implies

**Comment by nikhilwoodruff** [comment]
OK in that case I changed the right blue button to `Add more info` so that probably works here
