### ISSUE TITLE
GPT off by 100x in a percentage

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#421]
https://policyengine.org/us/policy?focus=policyOutput.analysis&household=24552&region=dc&timePeriod=2023&baseline=2&reform=6201

>The share of income held by the top 10% of households decreases marginally from 27.8% to 27.8%, while the share held by the top 1% remains practically unchanged (**0.0687% to 0.0686%**).

Prompt:
>This JSON describes three inequality metrics in the baseline and reform, the Gini coefficient of income inequality, the share of income held by the top 10% of households and the share held by the top 1% (describe the relative changes): {"gini":{"baseline":0.4424957921013576,"reform":0.44150174692851535},"top_10_pct_share":{"baseline":0.27782294682240133,"reform":0.2776797477993882},"top_1_pct_share":{**"baseline":0.06870142552468556,"reform":0.06866711794089246**}}

**Comment by leonali030** [comment]
@MaxGhenis Could you elaborate the issue? I see from the website it shows "6.85% to 6.85%"
<img width="569" alt="Screenshot 2023-04-18 at 10 55 34 AM" src="https://user-images.githubusercontent.com/128420049/232863078-1a5cbfa0-3aa8-40bd-a502-8c03a771a32e.png">

**Comment by MaxGhenis** [comment]
It's inconsistent - see the screenshot in my initial comment. So I think we'll want to test some prompts to encourage it to check the decimals, or provide clearer documentation for outcomes.

**Comment by MaxGhenis** [comment]
This hasn't recurred in a while
