### ISSUE TITLE
Move MTR chart title to right above chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#450]
Population charts have the title right above the chart, making it more screenshotable
<img width="666" alt="image" src="https://user-images.githubusercontent.com/6076111/230830694-548b8e3f-5cfa-47d9-876b-cac58f328323.png">

**Comment by nikhilwoodruff** [comment]
So just removing the description

**Comment by MaxGhenis** [comment]
yeah or moving it below
