### ISSUE TITLE
Logo overlaps with x axis at some zoom levels for earnings variation chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#456]
<img width="785" alt="image" src="https://user-images.githubusercontent.com/6076111/231611863-0d166d4b-4278-473b-a27c-0ccd5e8271a6.png">

https://policyengine.org/us/household?focus=householdOutput.earnings&household=29784

**Comment by rkaufman13** [comment]
Gonna try to take a stab at this

**Comment by nikhilwoodruff** [comment]
Thanks @rkaufman13- just going to assume this is stale but feel free to update!

**Comment by MaxGhenis** [comment]
yeah we just hide the logo at high zoom levels, which seems fine
<img width="569" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/ad27c6eb-c754-44d9-a7f8-40c68b3820a0">
