### ISSUE TITLE
Remove x axis title on poverty charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#463]
I think the categories are self-explanatory

**Comment by Abhito** [comment]
Hi @MaxGhenis , can I be assigned this as my first issue?

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it

**Comment by tarunsamanta2k20** [comment]
could you please send me the page url of the above charts?

**Comment by nikhilwoodruff** [comment]
Hey @tarunsamanta2k20 - assuming this is stale but feel free to re-assign.
