### ISSUE TITLE
Query parameter for simulation region resets on navigation

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#464]
I've noticed a few times I'll be viewing reform impacts in a State, then go back and change a parameter and then revisit, and see 'no impact'. At that point, the query parameter for `region` has reset back to `us`, but the region selector still displays the State.

@MaxGhenis I think you've run into this a few times?

**Comment by Evan-Wagner** [comment]
@nikhilwoodruff I believe I've [fixed this issue](https://github.com/PolicyEngine/policyengine-app/pull/484). Let me know if I did the right thing w/ this pull request.
