### ISSUE TITLE
Remove gray line on net income diff chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#47]
Not sure what it is

<img width="594" alt="image" src="https://user-images.githubusercontent.com/6076111/206540979-b20d3a1c-0028-498a-af6e-009032179a9a.png">

**Comment by nikhilwoodruff** [comment]
Proving very tricky to diagnose: I think it's a bug with Plotly. I've tried:
- Logging the Plotly data and showDelta, there (correctly) are only two lines in the component (but still this mystery third line from the first chart)
- Not just changing the data input on the switch change, but redrawing the actual <Plot> object
- Adding `key=` everywhere

**Comment by nikhilwoodruff** [comment]
Still no fix, but there's a workaround: clip on 'your current net income delta' once to hide it, then again to re-show it. Clears the gray line.

**Comment by MaxGhenis** [comment]
https://beta.policyengine.org/us/household?household=753&focus=householdOutput.earnings&reform=7&region=us&timePeriod=2022&baseline=2
<img width="759" alt="image" src="https://user-images.githubusercontent.com/6076111/208230748-6a2365c1-9c50-4af5-8fb6-cec11e89d3b0.png">

**Comment by MaxGhenis** [comment]
[RETVRN](https://policyengine.org/us/household?focus=householdOutput.earnings&household=3672)
<img width="840" alt="image" src="https://user-images.githubusercontent.com/6076111/218337731-f735407a-868c-45ef-9a30-8c2273cc3551.png">

**Comment by MaxGhenis** [comment]
This has been gone for a while
