### ISSUE TITLE
Analysis page cut off when printing

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#475]
For instance the below from [this](https://policyengine.org/us/policy?focus=policyOutput.analysis&reform=3345&region=or&timePeriod=2023&baseline=2)

[Reform #3345 _ Policy _ PolicyEngine US.pdf](https://github.com/PolicyEngine/policyengine-app/files/11280084/Reform.3345._.Policy._.PolicyEngine.US.pdf)

**Comment by nikhilwoodruff** [comment]
Haven't seen this in months

**Comment by abhcs** [comment]
What is the expected output here? Do you want the content in the Analysis pane to get printed? If yes, then we may want to add a print icon in the share results icon list and route the contents of the Analysis pane to it.

**Comment by anth-volk** [comment]
Additionally, I'd imagine we want some identifying logos, images, etc., but probably none of the web app container around the analysis pane? I'd have to agree with @abhcs on implementation.
