### ISSUE TITLE
Add `Subscribe` section to the bottom of blog posts

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#476]
Like how the UBI Center [website](https://www.ubicenter.org/poll-tracker) does it. Similar layout, but with the PolicyEngine-specific email sign-up form [here](https://github.com/PolicyEngine/policyengine-app/blob/7ed2daf2ac1fd947b1b4b7281ef97c22d9c52cbd/src/layout/EmailSignup.jsx).

**Comment by christinal59** [comment]
Hi @nikhilwoodruff , can you assign me this as my first issue? Thank you!

**Comment by christinal59** [comment]
Hi @MaxGhenis @nikhilwoodruff First PR Fixes #523 
Please let me know if there are any adjustments needed! 
<img width="605" alt="Screen Shot 2023-05-03 at 11 00 04 AM" src="https://user-images.githubusercontent.com/101846888/236004244-c42b839c-2bf6-4d3a-8808-46831dee21f6.png">

**Comment by MaxGhenis** [comment]
@christinal59 please do that in the PR

**Comment by christinal59** [comment]
@MaxGhenis Noted!

**Comment by nikhilwoodruff** [comment]
Closing from @christinal59's PR!
