### ISSUE TITLE
Typo in outcomes by income decile no change hovercard

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#487]
Missing something like "experience", though see #486 for alternative hover label suggestions.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/6076111/233797206-e6c04f4d-9d64-488b-93eb-3f84e185ab4b.png">

**Comment by yellohCrayon** [comment]
<img width="750" alt="Screenshot 2023-05-24 at 8 28 30 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/110482616/5facae15-ff68-40e6-bda9-8a89f4aa88f4">

Already resolved
