### ISSUE TITLE
Dates on blog post cards are too low and disappear on hover

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#497]

**Comment by giri-madhan** [comment]
Hi @nikhilwoodruff , Could I work on this issue? 

The expected result is we need to be able to see the date on hover right?

**Comment by nikhilwoodruff** [comment]
That'd be amazing, thanks! Yes, I think it's mainly just a font colour issue, but the positioning might be a bit more complex?

**Comment by giri-madhan** [comment]
I think adding a `maxHeight` value of `180` would help fix the positioning issue with the date.
```html
<img
        src={imageSrc}
        style={{
          width: width || 300,
          height: imageHeight || 180,
          maxHeight: 180,
          // Fit inside without stretching
          objectFit: "cover",
        }}
        alt="Preview"
/>
```
### Screenshot
<img width="1280" alt="Screenshot 2023-04-27 at 6 03 04 PM" src="https://user-images.githubusercontent.com/87971509/234864078-c4078cd3-eb30-41a4-833c-f0045d6cc4b4.png">


This is how the dates appear on the blog post cards. Could you please verify if this is correct? 

Thank you.
