### ISSUE TITLE
`Bad message format` in homepage Streamlit app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#503]
This just showed up after a few seconds on the homepage idle

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/6076111/235163571-cc33c6e2-7d50-4765-bff3-1e5ea8938c07.png">

**Comment by nikhilwoodruff** [comment]
Haven't seen this recently, and also the streamlit isn't on the homepage anymore
