### ISSUE TITLE
Show all scale parameters on a single screen

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#510]
We used to show it like this (FiscalSim is running off our 2022 layout): 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/35577657/235676247-6a5b5bd4-711b-47d8-b2a1-768002883026.png">
I think it'd be better to show all the rates and thresholds like this, but on click the user is take to the normal parameter screen for that particular parameter.

**Comment by MaxGhenis** [comment]
Could we generalize this, such that we always show the "sibling" set of parameter values on the screen, which is either those in the same scale, breakdown, or folder? I think we have enough screen space to show it with the trend for the specific parameter upon editing.

**Comment by nikhilwoodruff** [comment]
Closing because of the redesign
