### ISSUE TITLE
Make Twitter embeds look nicer

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#515]
My conversation with ChatGPT:

i like the way medium embeds tweets--it looks nice, with good spacing and the user avatar. how can i make it look nice like that on my react site with markdown blog files? currently im using the "embed tweet" feature to generate code like below, but its not as good

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">It&#39;s nice that my original plan to give myself my desired 70% tax rate worked out to nice round numbers, thanks again to <a href="https://twitter.com/ThePolicyEngine?ref_src=twsrc%5Etfw">@ThePolicyEngine</a> for helping me figure out how much to donate<a href="https://t.co/p9FPW45xKD">https://t.co/p9FPW45xKD</a></p>&mdash; James Medlock (@jdcmedlock) <a href="https://twitter.com/jdcmedlock/status/1653453502365196288?ref_src=twsrc%5Etfw">May 2, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

To achieve a similar look to Medium's embedded tweets in your React site with markdown blog files, you can follow these steps:

1. Install `react-twitter-embed` package:

```bash
npm install react-twitter-embed
```

2. Import the `TwitterTweetEmbed` component in the file where you want to display the embedded tweet:

```javascript
import { TwitterTweetEmbed } from 'react-twitter-embed';
```

3. Replace the "embed tweet" code with the `TwitterTweetEmbed` component, passing the tweet ID as a prop:

```jsx
<TwitterTweetEmbed tweetId="1653453502365196288" />
```

4. To ensure the embedded tweet is displayed correctly when using markdown, you can use a React library such as `react-markdown` to render the markdown content, and create a custom renderer for blockquotes to check if it's a Twitter embed.

First, install `react-markdown`:

```bash
npm install react-markdown
```

Then, import it in your component file:

```javascript
import ReactMarkdown from 'react-markdown';
```

Now, create a custom renderer for blockquotes:

```javascript
const renderers = {
  blockquote: (props) => {
    const { children } = props;
    const tweetId = children[0]?.props?.children?.[0]?.props?.href?.split("/")?.pop();

    if (tweetId) {
      return <TwitterTweetEmbed tweetId={tweetId} />;
    }

    return <blockquote>{children}</blockquote>;
  },
};
```

Finally, use the custom renderer when rendering your markdown content:

```jsx
<ReactMarkdown components={renderers} children={yourMarkdownContent} />
```

This will check if the blockquote is a Twitter embed, and if so, it will use the `TwitterTweetEmbed` component instead.

5. Customize the styles to achieve the desired look by adding CSS to your project. You can target the class `.twitter-tweet` to style the embedded tweet.

For example, add the following CSS to your project's stylesheet:

```css
.twitter-tweet {
  margin: 20px 0;
  font-family: "Helvetica Neue", "Arial", sans-serif;
  font-size: 14px;
  line-height: 1.4;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  border: 1px solid rgba(0, 0, 0, 0.1);
}
```

Feel free to modify the styles to suit your preferences. The above steps should give you a similar look to Medium's embedded tweets in your React site with markdown blog files.

**Comment by Evan-Wagner** [comment]
@MaxGhenis I implemented the code and the TwitterTweetEmbed component seems to be converting to an iframe, but nothing is displayed. See HTML below — I notice the height and width are both set to 0 in the style attribute of the iframe, but haven't figured out a way to override it in BlogPage.jsx or App.css.

```
<div style="padding: 20px;"><p style="font-size: 16px; margin-bottom: 20px; font-family: Merriweather; width: 100%;"><a href="https://policyengine-james-medlock-donation-solver.streamlit.app/" target="_blank" rel="noopener noreferrer" style="color: rgb(44, 100, 150);"><em>Jump to the tool</em></a></p>
  <p style="font-size: 16px; margin-bottom: 20px; font-family: Merriweather; width: 100%;">One week ago, Twitter user James Medlock tweeted:</p>
  <div style="width: 600px;"><div><div class="twitter-tweet twitter-tweet-rendered" style="display: flex; max-width: 550px; width: 100%; margin-top: 10px; margin-bottom: 10px;"><iframe id="twitter-widget-9" scrolling="no" frameborder="0" allowtransparency="true" allowfullscreen="true" class="" style="position: absolute; visibility: hidden; width: 0px; height: 0px; display: block; flex-grow: 1;" title="Twitter Tweet" src="https://platform.twitter.com/embed/Tweet.html?dnt=false&amp;embedId=twitter-widget-9&amp;features=eyJ0ZndfdGltZWxpbmVfbGlzdCI6eyJidWNrZXQiOltdLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X2ZvbGxvd2VyX2NvdW50X3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9iYWNrZW5kIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19yZWZzcmNfc2Vzc2lvbiI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfZm9zbnJfc29mdF9pbnRlcnZlbnRpb25zX2VuYWJsZWQiOnsiYnVja2V0Ijoib24iLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X21peGVkX21lZGlhXzE1ODk3Ijp7ImJ1Y2tldCI6InRyZWF0bWVudCIsInZlcnNpb24iOm51bGx9LCJ0ZndfZXhwZXJpbWVudHNfY29va2llX2V4cGlyYXRpb24iOnsiYnVja2V0IjoxMjA5NjAwLCJ2ZXJzaW9uIjpudWxsfSwidGZ3X3Nob3dfYmlyZHdhdGNoX3Bpdm90c19lbmFibGVkIjp7ImJ1Y2tldCI6Im9uIiwidmVyc2lvbiI6bnVsbH0sInRmd19kdXBsaWNhdGVfc2NyaWJlc190b19zZXR0aW5ncyI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdXNlX3Byb2ZpbGVfaW1hZ2Vfc2hhcGVfZW5hYmxlZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9LCJ0ZndfdmlkZW9faGxzX2R5bmFtaWNfbWFuaWZlc3RzXzE1MDgyIjp7ImJ1Y2tldCI6InRydWVfYml0cmF0ZSIsInZlcnNpb24iOm51bGx9LCJ0ZndfbGVnYWN5X3RpbWVsaW5lX3N1bnNldCI6eyJidWNrZXQiOnRydWUsInZlcnNpb24iOm51bGx9LCJ0ZndfdHdlZXRfZWRpdF9mcm9udGVuZCI6eyJidWNrZXQiOiJvbiIsInZlcnNpb24iOm51bGx9fQ%3D%3D&amp;frame=false&amp;hideCard=false&amp;hideThread=false&amp;id=1636480393007489024%3Fref_src%3Dtwsrc%255Etfw&amp;lang=en&amp;origin=http%3A%2F%2Flocalhost%3A3000%2Fus%2Fblog%2Fmedlock-donation-calculator&amp;sessionId=57aedf606983a60e8ade0f85e2d2e9f35ddf0800&amp;theme=light&amp;widgetsVersion=aaf4084522e3a%3A1674595607486&amp;width=550px" data-tweet-id="1636480393007489024?ref_src=twsrc%5Etfw"></iframe></div></div></div> <script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
...
```

**Comment by Evan-Wagner** [comment]
Fixed. My problem was the parsed tweet id included URL params.
