### ISSUE TITLE
Crashes when abolishing EITC

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#525]
In simulating EITC repeal, PolicyEngine first said that:
* [It would not cause changes to cliffs US-wide](https://policyengine.org/us/policy?focus=policyOutput.cliffImpact&reform=5859&timePeriod=2023&baseline=2)
* [It also would not cause changes to cliffs in California](https://policyengine.org/us/policy?focus=policyOutput.cliffImpact&reform=5859&region=ca&timePeriod=2023&baseline=2) (extra suspicious since CA has an EITC match)
* Then when I clicked to the [budgetary impact in California](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=5859&region=ca&timePeriod=2023&baseline=2), it started another simulation (this shouldn't be necessary) and the progress bar never progressed
<img width="899" alt="image" src="https://user-images.githubusercontent.com/6076111/236366274-eb4f277e-077e-4baa-91c1-ee3d2a01b6de.png">
* When starting from scratch in a new tab for the [US-wide impact](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=5859&region=us&timePeriod=2023&baseline=2), it created a white screen with these console errors

```
react-dom.production.min.js:189 RangeError: Invalid array length
    at K (BudgetaryImpact.jsx:51:20)
    at ko (react-dom.production.min.js:167:137)
    at xs (react-dom.production.min.js:290:337)
    at Au (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
fl @ react-dom.production.min.js:189
react-dom.production.min.js:283 Uncaught RangeError: Invalid array length
    at K (BudgetaryImpact.jsx:51:20)
    at ko (react-dom.production.min.js:167:137)
    at xs (react-dom.production.min.js:290:337)
    at Au (react-dom.production.min.js:280:389)
    at gu (react-dom.production.min.js:280:320)
    at vu (react-dom.production.min.js:280:180)
    at au (react-dom.production.min.js:271:88)
    at iu (react-dom.production.min.js:268:429)
    at w (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

**Comment by MaxGhenis** [comment]
Just re-ran after updating the API and still got the same problem with the EITC repeal. Other reforms like [CTC repeal](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=3318&region=us&timePeriod=2023&baseline=2) work fine.

**Comment by MaxGhenis** [comment]
Similar issue just now [repealing CalEITC](https://policyengine.org/us/policy?focus=policyOutput.inequalityImpact&reform=2&region=ca&timePeriod=2023&baseline=6416)

Can we prioritize this? That we're potentially displaying incorrect numbers concerns me.

**Comment by MaxGhenis** [comment]
@lswainemoore you were right - it was the absence of rental expenditures, which caused a null budgetary impact when repealing the CA renters credit and broke the chart (we recently added logic to hide null bars and didn't handle this case correctly).

**Comment by lswainemoore** [comment]
makes sense!

**Comment by MaxGhenis** [comment]
Not all the links from this issue work, but cliff impacts of EITC abolition correctly produce nonzero impacts when created fresh: [US](https://policyengine.org/us/policy?focus=policyOutput.cliffImpact&reform=5331&region=us&timePeriod=2023&baseline=2) and [California](https://policyengine.org/us/policy?focus=policyOutput.cliffImpact&reform=5331&region=ca&timePeriod=2023&baseline=2)

I filed https://github.com/PolicyEngine/policyengine-app/issues/690 for a more general endless spinner issue.
