### ISSUE TITLE
Change hover labels to "by less than 0.1%" when small but nonzero

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#529]
[For instance to fix this](https://policyengine.org/us/policy?focus=policyOutput.inequalityImpact&reform=6416&region=ca&timePeriod=2023&baseline=2):

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/6076111/236883046-ac90f557-f147-4755-a6d7-11697d819dbc.png">

**Comment by QianruZhang78** [comment]
I'll start working on this if no have has taken this.
