### ISSUE TITLE
Move logo further right on earnings variation charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#541]
<img width="761" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/1adf6115-e406-4513-b53c-4920667ca02e">

**Comment by AyuAyushi** [comment]
Hi,
I just started on by journey to open source contribution and wanted to give a try to fix this issue. 
However I was finding an issue to even install it locally:
I am using the node version 19.9.0 and my npm version is 9.6.3 
After I did 'npm install', I am getting the following error:
![image](https://github.com/PolicyEngine/policyengine-app/assets/42701224/df704925-c8ad-422e-b343-8dd0ec98ec67)
Could you please help me here?
PS: I think the npm version I am using is incorrect!

**Comment by AyuAyushi** [comment]
> Hi, I just started on my journey to open source contribution and wanted to give a try to fix this issue. However I was not able to install the project locally: I am using the node version 19.9.0 and my npm version is 9.6.3 After I did 'npm install', I am getting the following error: ![image](https://user-images.githubusercontent.com/42701224/238177361-df704925-c8ad-422e-b343-8dd0ec98ec67.png) Could you please help me here? PS: I think the npm version I am using is incorrect!

**Comment by MaxGhenis** [comment]
Could you try using nvm per our README.md?

**Comment by AyuAyushi** [comment]
> Could you try using nvm per our README.md?

Yes, I had used the same.

**Comment by nikhilwoodruff** [comment]
Think this is now handled anyway, thanks though!
