### ISSUE TITLE
Embedded charts in Analysis page are too wide

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#544]
<img width="945" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/63f85fc2-dfd9-4488-977c-38b763544f62">

https://policyengine.org/us/policy?focus=policyOutput.analysis&reform=13292&region=us&timePeriod=2023&baseline=2

**Comment by kalenluciano** [comment]
I couldn't figure out how to fix this on my own. Maybe someone else with more CSS experience can try it out?

**Comment by nikhilwoodruff** [comment]
Yeah I think it's fine now
