### ISSUE TITLE
No logo on household charts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#550]
Net income and MTRs, baseline and baseline+reform

<img width="599" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/a8a9b4fd-d4e2-4110-bc23-a8c55994e13e">

<img width="598" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/1110ae3a-4581-4057-a32e-711935b0a488">
<img width="596" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/0e8eae88-3af1-489f-af1c-d12024a8a943">
<img width="616" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/f3f2d9df-9af1-4f8a-b564-06578ceb7fd1">

**Comment by tarunsamanta2k20** [comment]
https://www.linkedin.com/in/tarun-samanta/

**Comment by tarunsamanta2k20** [comment]
which icon and where should i add that icon to the chart?

**Comment by MaxGhenis** [comment]
Same as on all other charts

**Comment by tarunsamanta2k20** [comment]
@MaxGhenis I am facing some issues from my side. could you please send me the page url of the above charts?

**Comment by MaxGhenis** [comment]
Here's an example of a chart with the logo: https://policyengine.org/us/policy?focus=policyOutput.netIncome&region=us&timePeriod=2023&baseline=2&reform=14512

<img width="898" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/bbda61bd-762a-4b44-aeab-c2616046bd85">

**Comment by tarunsamanta2k20** [comment]
> Here's an example of a chart with the logo: https://policyengine.org/us/policy?focus=policyOutput.netIncome&region=us&timePeriod=2023&baseline=2&reform=14512
> 
> <img alt="image" width="898" src="https://user-images.githubusercontent.com/6076111/249837807-bbda61bd-762a-4b44-aeab-c2616046bd85.png">

No, it's fine I saw this logo. The problem is that when I am searching for the above charts in code, I can see that those charts have chartLogo included.

**Comment by MaxGhenis** [comment]
You can test locally with `npm start`. Please look through the code to find the chartLogo info.

**Comment by MaxGhenis** [comment]
Removing your assignment @tarunsamanta2k20 in case someone else can do it. Please open a draft PR and link the issue if you're on it.

**Comment by MaxGhenis** [comment]
It has not been resolved.
<img width="822" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/b647e7ea-f7a5-419d-8d00-94c9379d959f">

https://policyengine.org/us/household?focus=householdOutput.earnings&household=32041

**Comment by MaxGhenis** [comment]
As I said, please file a draft PR if you have work on it. But given you requested to be assigned a month ago and didn't work on it, I'd like to give others the opportunity. It's a reasonably high priority and low expected effort. Thanks for your understanding.
