### ISSUE TITLE
Empty space on left side of links on home page

### ISSUE THREAD

**Issue by yellohCrayon** [PolicyEngine/policyengine-app#553]
I noticed there is some empty space on the left of these links is that intentional @MaxGhenis?
https://github.com/yellohCrayon/policyengine-app/blob/79ef9097f084efb7f426be3e169dba6c679add0f/src/pages/HomePage.jsx#L492-L494

<img width="1064" alt="Screenshot 2023-05-24 at 11 20 04 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/110482616/5272c1dc-29c8-46b6-802b-5b6183f4c63c">

**Comment by MaxGhenis** [comment]
Nope! Thanks for the catch.

**Comment by MaxGhenis** [comment]
Fixed in #554 

(fyi @yellohCrayon you can use `Fixes #553` in the PR description to link the issue so it automatically closes it upon merging)
