### ISSUE TITLE
Add hover labels to charts matching those in the current app

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#56]
For example, code starting here:
https://github.com/PolicyEngine/policyengine/blob/755fa5168caf3b7e443302db4821d22c034e1733/policyengine/impact/household/charts/budget.py#L198

One example plot in the current repo starts here:
https://github.com/PolicyEngine/policyengine-app/blob/d6355da43447dcac03ac0eb4241d3c116d38152b/src/pages/household/output/MarginalTaxRates.jsx#L123

**Comment by nikhilwoodruff** [comment]
Now fixed
