### ISSUE TITLE
Update logo for policyengine.org social share preview

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#561]
https://socialsharepreview.com/?url=https://policyengine.org

<img width="769" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/28ba79f4-3f5d-4875-a20b-80338a534f1e">

Logos here: https://github.com/PolicyEngine/policyengine-app/tree/master/src/images/logos/policyengine

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by MaxGhenis** [comment]
Doesn't seem like #727 worked. Now we have no social preview image:
<img width="557" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/871eabfa-6f40-417f-86e7-f2ec27164daa">


https://socialsharepreview.com/?url=https://policyengine.org

**Comment by MaxGhenis** [comment]
now fixed
