### ISSUE TITLE
Household screen says reform instead of baseline policy name with custom baseline

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#565]
https://policyengine.org/us/household?focus=householdOutput.netIncome&reform=13870&region=us&timePeriod=2023&baseline=13867&household=31159

The baseline policy here is named "Repealing SNAP emergency allotments"

<img width="865" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/56e35621-e939-4d08-8efc-6ac0028507ea">

**Comment by patrickhanl** [comment]
Hi @MaxGhenis @nikhilwoodruff 
I'm interested in contributing to this project, and I believe I see the issue here. Can I be added as a contributor and assign to myself?
Assuming it the order should be "reform" compared against "baseline"?

**Comment by nikhilwoodruff** [comment]
Hey @patrickhanl thanks for this! Just assigned you, please feel very free to file a PR from a fork any time you're able.

**Comment by patrickhanl** [comment]
@nikhilwoodruff @MaxGhenis 

Opened https://github.com/PolicyEngine/policyengine-app/pull/584 to address this
