### ISSUE TITLE
policyengine.org is completely blank in private or incognito windows

### ISSUE THREAD

**Issue by jacky5124** [PolicyEngine/policyengine-app#567]
The home page is completely blank when it is open in FireFox's private windows and Chrome's incognito windows. 

When debugging locally, consoles from both browsers would have the same log indicating "`useLocation()` may be used only in the context of a `<Router>` component".

<img width="1440" alt="Homepage in FireFox" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/9c506f2c-a5af-470d-8fbc-fed5c0d662ae">

<img width="1440" alt="FIreFox console" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/54eda4b3-4fd4-442e-ba24-517b1033e999">

<img width="1440" alt="Homepage in Chrome" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/179b1f49-25aa-49d3-bff7-3445d38d4981">

<img width="1440" alt="Chrome console" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/1e1b21c5-c06d-4513-9bdf-bca5d23e7816">

**Comment by nikhilwoodruff** [comment]
Thanks for catching this @jacky5124- I think I got the fix in so closing.
