### ISSUE TITLE
Cliff chart hover labels incorrectly says "falls"

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#57]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/6076111/207999316-9005ddfb-dc97-411c-80e4-13fdcc304890.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/6076111/207999358-0963eb22-1056-4fa4-9cfb-3ecdc1b6dc63.png">

**Comment by nikhilwoodruff** [comment]
Should be fixed now
