### ISSUE TITLE
Endless `Generating` spinner with GPT Analysis

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#570]
GPT Analysis is failing in both US and UK simulations

https://policyengine.org/us/policy?focus=policyOutput.analysis&household=31215&region=us&timePeriod=2023&baseline=2&reform=9356

https://policyengine.org/uk/policy?focus=policyOutput.analysis&reform=44&region=uk&timePeriod=2023&baseline=1

**Comment by nikhilwoodruff** [comment]
Now fixed after an API update

**Comment by nikhilwoodruff** [comment]
I actually can't say for sure on this, sorry. There were some intentional changes to fix it in that PR but given that we did a refresh with it, it could have been that.

**Comment by MaxGhenis** [comment]
It's back

**Comment by MaxGhenis** [comment]
No longer back
