### ISSUE TITLE
Simple sign-in

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#588]
Just so we have some initial version and have at least the capability to save user details, we should enable users to sign in to the site. This initial version doesn't need to have any actual functionality other than a sign-in ability.

**Comment by MaxGhenis** [comment]
What's the simplest thing we can start with here? A few options come to mind:
1. **Add to email list.** Seems too lightweight though - user might wonder why we don't just have an email signup (what we have today).
2. **Add to email list with countries they're interested in.** So we can target newsletters based on country.
3. **Email results.** On the household or policy side, e.g. the first page plus a link. We'll also add them to our list here.
4. **Save policies and/or households to their account.** This seems more involved but a more concrete offering.
5. **Public profile page.** This doesn't seem like a starter feature but logging to inform the future direction.

**Comment by anth-volk** [comment]
With regard to option 2, do we currently have different targeted newsletters, or only the one at the moment?

To me, options 4 and 5 seem involved enough to warrant, at the very least, ensuring they can be made easily compatible with a future front-end redesign of the policy and household calculators. If we were to move in that direction, I think it'd be vital to agree on a front-end design that melds well with the theme adopted throughout the non-calculator pages, and ideally it should be independent enough of the calculator components to allow easy uncoupling from them, given a potential future rewrite.

2 and 3 seem the most appealing to me, given their lower involvement and given the aim of this effort, which (correct me if I'm wrong) is to make it easier for more active users to engage with PolicyEngine's articles and updates, while placing that work of ours more at the forefront of the application.

**Comment by MaxGhenis** [comment]
We only have one newsletter at the moment, as we haven't collected users' country upon sign-up. At some point we should request their country.
