### ISSUE TITLE
Bug when plotting some variables on varying earnings chart

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#59]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/6076111/208035935-edea4879-12c8-4c64-a3da-ba675b8f834e.png">

https://beta.policyengine.org/us/household?household=338&focus=householdOutput.earnings

**Comment by nikhilwoodruff** [comment]
This should be fixed now - it was because self-employment income is an input, so we don't calculate the axis for it
