### ISSUE TITLE
Lowercase State variable in questionnaire and remove caveat about calculations

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#592]
https://policyengine.org/us/household?focus=input.household.state_name

<img width="624" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/11293c07-7869-451f-9f5c-e1df5d6d5017">

I don't think this is in policyengine-us

**Comment by marcadrian-it** [comment]
#593
