### ISSUE TITLE
Console warning regarding bolding when hovering over interactive elements

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#597]
When hovering over various different interactive elements, I receive the following console warning:

`You are trying to animate fontWeight from "500" to "bold". 500 is not an animatable value - to enable this animation set 500 to a value animatable to bold via the `style` property.`

Perhaps there's a shared Styled-Component raw CSS setting creating this?

**Comment by dotslashbit** [comment]
I'm looking into this, opening a draft Pr for now
