### ISSUE TITLE
Subscribe button on homepage

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-app#598]
Just below the blog carousel

**Comment by MaxGhenis** [comment]
For example, how we show it on individual blog posts

<img width="960" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/f3d1a283-7670-4068-b7d1-c8865fd7e12e">

https://policyengine.org/us/blog/poverty-race-ethnicity

**Comment by sohaibaumer** [comment]
can i get assigned?
