### ISSUE TITLE
Make `you are here` on household charts a point instead of line

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#611]
This third vertical line repeatedly confuses users. We should instead make a `you are here` semi-transparent point on the baseline graph, and a second (blue) point on the reform graph. They probably don't need to be in the legend.

https://policyengine.org/us/household?focus=householdOutput.earnings&household=32121&region=us&timePeriod=2023&baseline=2&reform=17331

<img width="757" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/cc599769-cf97-454c-a550-0145c36f6d8e">

**Comment by patrickhanl** [comment]
@MaxGhenis @nikhilwoodruff I can take this one if you can assign it to me.

**Comment by patrickhanl** [comment]
@MaxGhenis @nikhilwoodruff 

Opened https://github.com/PolicyEngine/policyengine-app/pull/652 to address this, please take a look and let me know if any changes are needed, thanks!
