### ISSUE TITLE
Replace carousel of reformed parameters with a full-page overview defining the reform

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#616]
The carousel currently implies that changing the selected parameter affects the main page (which it doesn't) and users don't currently have a way to see all the reformed parameters. A full page defining the reform could also make it easier to accomplish other important tasks like clearing a provision.

**Comment by nikhilwoodruff** [comment]
Not sure we'll take this in the redesign so closing!
