### ISSUE TITLE
Variable titles in calculator component pages aren't vertically centered

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#629]
Extremely minor formatting issue - the `h6` elements inside of the calculator pages (e.g., if you navigate to 'Compute my household income...'->Geography) are not centered vertically. It appears that the `h6` tag adds bottom padding, pushing the text slightly above center.

**Comment by nikhilwoodruff** [comment]
Thanks- think we can close though because it's not really noticeable, but we'll keep in mind in the redesign!
