### ISSUE TITLE
AI report writing nonsense

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#630]
This occurred when generating the AI report for this reform: https://policyengine.org/us/policy?focus=policyOutput.analysis&reform=20280&region=us&timePeriod=2023&baseline=2&household=32809

Buggy sectioned bolded. Could this be a bug with how we're presenting the words as they come from GPT-4?

> The proposed hypothetical reform "Gisele" aims to introduce several changes to the current public policy in the United States. For the years from 2023 through 2028, it proposes a flat basic income amount per person of $5,000. Unlike the current law that phases out basic income above a threshold as a rate, this reform proposes not to phase out basic income as a rate. The phase-out thresholds for various tax filers such as head of household, joint, separate, single, and widow are proposed to be set at $100,000, up from the current value in of the $0. **basic Similarly, income the phase-out phase-out rate, ends which for is various currently tax at filers 0, are to set 1,500. at**
> **According $150,000. to Furthermore, a the microsimulation reform model proposes from a PolicyEngine substantial US increase v0.401.0** based on the 2021 Current Population Survey March Supplement microdata, this proposal is estimated to have a notable budgetary impact. It's projected to increase benefit spending by approximately $1.2 trillion, thus resulting in a budgetary deficit of about $1.2 trillion. No substantial change is predicted in state tax revenue.
> When viewed by income decile, over 80% of households stand to gain more than 5% in income. The remaining households either **are report anticipated no to change see or an a average gain increase less of than nearly 5% $7,200 in representing income. a
> The 49.7% income relative increase increase, among while deciles the varies. tenth Low-income decile groups is in only the projected first to decile gain around $2,500 or about 0.8%.**
>

**Comment by nikhilwoodruff** [comment]
This happened once last week

**Comment by nikhilwoodruff** [comment]
But not sure of the solution here...

**Comment by MaxGhenis** [comment]
Is this GPT-4, or something about our writing the stream? Could we log the full GPT-4 result to check? I haven't seen anything like this from ChatGPT.

**Comment by MaxGhenis** [comment]
This is becoming more common, maybe universal. It often starts off OK and then bugs out by the end. [For example](https://docs.google.com/document/d/1eatxHmZjDCqLNqpaf_PHJ8sBsPXOI1CDcSGiVY1LReY/edit):
>In summary, this hypothetical reform centered on the introduction of a child basic income and the elimination of the California dependent exemption amount would bring about a modest reduction in overall and child poverty rates and a slight contraction in income inequality, primarily benefiting lower-income deciles while leading to marginal income reductions for higher-income deciles. of and nearly $139. -$51.4 Meanwhile, million.
According higher to deciles the exhibit available a distributional decrease data, in at income, various with income the deciles, most the substantial outcomes reduction, under an the average reform of are roughly as -$134, follows:
occurring A in share the of ninth households decile.
When gains it less comes than to 5% poverty of impacts, their the income, reform most effects notably a in slight the decrease second in and the third overall deciles.
poverty A rate, as measured by the Supplemental Poverty Measure, with the rate dropping from 17.0% to 16.8%. There is a more pronounced reduction in the child poverty rate, decreasing from 15.8% to 15.1%.

**Comment by MaxGhenis** [comment]
No longer an issue with Claude
