### ISSUE TITLE
Bug with plot of CTC intermediate variables by earnings

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#64]
Here's a [standard single parent of a 10-year-old child](https://beta.policyengine.org/us/household?household=749&focus=input.household.age):
<img width="760" alt="image" src="https://user-images.githubusercontent.com/6076111/208229926-1cafd878-56e3-49d0-877b-1f393db36893.png">

The `Your current CTC maximum amount (child)` is correctly at $2,000, but the line is 0.5% of employment income, and I don't know where that comes from.

The maximum amount should just be a flat amount ([variable](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum.py)), since it's based on the [age-based `single_amount` scale parameter](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/irs/credits/ctc/amount/base.yaml). Might this have something to do with it being a person-level variable?

**Comment by nikhilwoodruff** [comment]
Yeah I've seen this a few times: I think the significance is actually that it's 1, 2, 3, 4, 5, .... I think this means the variable failed to load, but Plotly automatically put it as a natural number sequence instead(?)

**Comment by nikhilwoodruff** [comment]
Link now works btw
