### ISSUE TITLE
"Your current net income" bug

### ISSUE THREAD

**Issue by jacky5124** [PolicyEngine/policyengine-app#656]
In earnings variation of household output, "your current net income" has two data points, where one says your net income will be 0, but in reality this point should not exist. I assume this 0 net income point is solely used for connecting with the current net income point so that there is a line appearing on the plot. Can we fix this? I guess we can take a look at how the cliff is rendered.

<img width="1440" alt="Screenshot 2023-08-05 at 4 11 47 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/8edf2ea3-26ca-463c-9028-2a1ae0a63c4f">

<img width="531" alt="Screenshot 2023-08-05 at 4 11 11 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/16cc51cf-9d8e-40b7-8b57-0ec70e6ea2a3">

**Comment by MaxGhenis** [comment]
Will https://github.com/PolicyEngine/policyengine-app/pull/652 fix this? @patrickhanl

**Comment by patrickhanl** [comment]
@MaxGhenis yes #652 will resolve the issue as it will remove the line an extra point
