### ISSUE TITLE
Restrict MTR y axis at 100%

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#66]

**Comment by abhcs** [comment]
@MaxGhenis Given that the axis bounds logic has changed recently (#939), is this issue still valid -- can you find a case where the y-axis for MTR needs correction? After the changes introduced in #939, there should be only a few cases when the upper bound on the axis exceeds `100%`.

**Comment by MaxGhenis** [comment]
[Yes](https://policyengine.org/us/household?focus=householdOutput.mtr&household=38027)

<img width="775" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/533eea0e-9ef4-470e-9839-2329264fb8a4">

(Misaligned dot is a separate issue)

**Comment by abhcs** [comment]
In this case, two peaks are greater than `100`. If we fix the bounds at `100`, the user cannot tell where the peaks are.

The current logic tries to find the range of relevant values: here it is roughly `[-150, 700]` and it adds a padding of `10%` of the length of the range, i.e., `0.1 * 850 ~ 85`. This logic is fixed across most charts now. I can make a change specific to MTR. Please let me know if you are ok with the peaks getting clipped.

**Comment by MaxGhenis** [comment]
Let's actually clip at 200%. In this case, they're MTR at the bottom goes as low as -136%, which is a "true" MTR over a sustained earnings range. Some earners face similar true MTRs over 100%. What we're trying to avoid distorting the chart is cliffs; e.g., that 700% is really infinite, since they lose $7,000 in TANF benefits when their earnings rise by $1 above the threshold. We estimate 700% because we do so discretely, but 700% itself isn't a helpful number.

**Comment by abhcs** [comment]
Ok, one more question: are the grey cliff bars for the same data displayed correctly?

<img width="719" alt="Screenshot 2023-12-16 at 3 07 58 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/8b703e53-a69a-4bf6-a179-fb8066c19cfe">

Or should they extend to the edge of the chart?

**Comment by abhcs** [comment]
Also, I am not sure the dot is misaligned in your image. The entire line is shifted downwards for some reason. This is the image I see:

<img width="743" alt="Screenshot 2023-12-16 at 3 42 26 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/31144719/4da182e2-90ac-4039-bbaf-43648cacb052">

So, the range is `[-90, 750]` and the second peak is really at `207%`. Do you think we should clip between `[-300, 300]` so that the second peak is visible?

**Comment by MaxGhenis** [comment]
The second peak at 207% is another cliff, so we don't need to extend to it.

>Ok, one more question: are the grey cliff bars for the same data displayed correctly? Or should they extend to the edge of the chart?

Are you asking whether they should go all the way to the top, rather than up to $150k? Yes I think they should cover the full height.

Separately we should set the x and y axis minima to zero if we don't have negative data.
