### ISSUE TITLE
Round MTR to one decimal

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#67]
Round marginal tax rates to 1 (instead of 0) decimals in the sidebar and graph

**Comment by anth-volk** [comment]
@nikhilwoodruff I'd love to take this on as an easy first issue. Would you mind assigning me?

**Comment by anth-volk** [comment]
@MaxGhenis Should this also be reflected in the title of the marginal tax rate page? I've attached an image highlighting the area I'm referring to.
<img width="1440" alt="Screen Shot 2023-04-13 at 3 34 28 PM" src="https://user-images.githubusercontent.com/14987227/231877013-9be1c8a2-7dc7-4bdf-8093-548e4d73a1db.png">

**Comment by MaxGhenis** [comment]
yes please

**Comment by MaxGhenis** [comment]
Fixed in #461
