### ISSUE TITLE
Donate Page, Donate Online section

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#670]
<img width="664" alt="Screen Shot 2023-08-08 at 9 02 11 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/f0e7bc74-0fd8-49a4-9d0c-9b2c7e45d865">

**Comment by QianruZhang78** [comment]
I can start working on this one if no one else is currently working on it:)

**Comment by anth-volk** [comment]
Perfect! Happy to assign. Also, feel free to reach out to me via Slack if you have any questions or anything. I'll be sending around a document that lays out some of the background to the redesign tomorrow during the app meeting.

**Comment by anth-volk** [comment]
Oh, I see you self-assigned haha
