### ISSUE TITLE
Individual blog posts: author section

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#687]
<img width="548" alt="Screen Shot 2023-08-10 at 2 53 21 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/73866a9c-53d1-4fbb-893c-725c0c3561dc">

May be useful for whoever's taking the rest of the blog post page to take this, as well

**Comment by nikhilwoodruff** [comment]
@nung22
