### ISSUE TITLE
Research Page, Filters and Blog Post Layout

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#689]
If this is too large of a component, this could be broken down later into separate subcomponent issues, one for the left-side filter bar, one for the blog post layouts, and one for a component to iterate over the posts and convert them to JSX.

For the time being, only the Date, Author, and (potentially) Region filters from the design will be included. Later, the underlying JSON structure will be changed to include topics to allow further filtering.

As an implementation detail, the filters should select be inclusive and select a union of articles, akin to a SQL OUTER JOIN, and not exclusive (i.e., INNER JOIN). The title element of the component could change based upon those filters.

Additionally, at the moment, the existing Research page contains a hidden automatic filter that only displays articles from the user's selected country (e.g., US) and anything tagged "global." Ideally, this should become more explicit, with a region filter automatically applied for the user's country, but also displayed and allowing the user to select other countries.

<img width="643" alt="Screen Shot 2023-08-11 at 2 31 19 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/6261ef81-8c0c-474d-bb5d-fa27e81c336e">

**Comment by nikhilwoodruff** [comment]
Let's just recap this in the meeting
