### ISSUE TITLE
Policy reform simulation stuck

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#69]
Endless spinner on [this one](https://beta.policyengine.org/us/policy?household=767&focus=policyOutput.netIncome&reform=146&region=us&timePeriod=2022&baseline=2)

**Comment by MaxGhenis** [comment]
[This other one](https://beta.policyengine.org/us/policy?reform=147&focus=policyOutput.netIncome&region=us&timePeriod=2022&baseline=2) showed this:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/6076111/208251411-fc38705b-7e81-46b9-8b4d-fd678dd857a6.png">

**Comment by nikhilwoodruff** [comment]
Seems to be inconsistent http://localhost:3000/us/policy?reform=119&focus=policyOutput.netIncome&region=us&timePeriod=2022&baseline=2

**Comment by MaxGhenis** [comment]
Yeah and just now I ran a $1k UBI, the main set of outputs worked but it got stuck on the cliff impact

**Comment by MaxGhenis** [comment]
Fixed
