### ISSUE TITLE
Clear out policies that break

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#692]
For example https://policyengine.org/us/policy?focus=gov&reform=10414&region=us&timePeriod=2023&baseline=2 per #549, but also probably quite a few more based on changed parameters and so on. We should automate finding, reporting, and clearing them.

**Comment by anth-volk** [comment]
@MaxGhenis Just ran this and got the deprecated policies modal. Would nominate closing.
