### ISSUE TITLE
The download button is blocking Plotly's built-in hover info

### ISSUE THREAD

**Issue by jacky5124** [PolicyEngine/policyengine-app#694]
While adding `hovertemplate` to Plotly's plot objects, I discovered that the hover info would be blocked by the download button, as shown below. Can we fix this?

<img width="1440" alt="download button bug 1" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/9de3c813-149c-45d8-b530-4067f9a99a44">

<img width="1440" alt="download button bug 2" src="https://github.com/PolicyEngine/policyengine-app/assets/17683171/182de22a-07e8-4dcb-b377-88efe57b42e1">

**Comment by Aurora-zyy** [comment]
Hey I hope to claim this issue for first task.

**Comment by MaxGhenis** [comment]
What if we move it to the top with the share icons, ie a download icon?

**Comment by nikhilwoodruff** [comment]
No longer an issue (though still in the wrong place)
