### ISSUE TITLE
Editing one policy parameter affects other displayed parameters

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#695]
Steps to reproduce:
1. Go to some policy parameter, e.g. the [head of household standard deduction](https://policyengine.org/us/policy?reform=2&focus=gov.irs.deductions.standard.amount.HEAD_OF_HOUSEHOLD)
2. Change the value, e.g. to [zero](https://policyengine.org/us/policy?reform=20665&focus=gov.irs.deductions.standard.amount.HEAD_OF_HOUSEHOLD&region=us&timePeriod=2023&baseline=2)
3. Visit another policy parameter, e.g. the [joint standard deduction](https://policyengine.org/us/policy?reform=20665&focus=gov.irs.deductions.standard.amount.JOINT&region=us&timePeriod=2023&baseline=2)

Result: The parameter value "sticks" in the text box

<img width="638" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/0bda9a39-3816-46ba-9e57-a75a943605dc">

https://www.loom.com/share/57594f0211a4485788c7e5af6b63d559

**Comment by patrickhanl** [comment]
@MaxGhenis @nikhilwoodruff if you can assign this to me I can fix & reconcile with https://github.com/PolicyEngine/policyengine-app/issues/526
