### ISSUE TITLE
Respect capitalization of parameter labels

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#704]
We shouldn't force them into proper case ([example](https://policyengine.org/us/policy?focus=gov.irs.credits.eitc.eligibility.age.max))

<img width="1315" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/e8b7b233-24a3-4cd7-a62a-41a953ef2936">

**Comment by CalebABeck** [comment]
Hello @MaxGhenis and @nikhilwoodruff, I'd like to make contributions to this project and would appreciate being added as a collaborator.

I was planning on tackling this as my first issue, but after some quick investigation realized that would mean simply reverting the second commit in this recent PR: #699. May I proceed with that regardless?

Thanks!

**Comment by MaxGhenis** [comment]
yep sounds good thanks caleb!
