### ISSUE TITLE
The anchor on the homepage Twitter button extends all the way to the flag dropdown arrow, making it easy to accidentally click on the Twitter link by mistake

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#713]
A very minor issue, but it seems that perhaps the container containing the Twitter button, instead of the Twitter button itself, contains the anchor tag, making it very easy to accidentally click just to the right of the country selector arrow and accidentally be sent to Twitter. It appears the other buttons also possess an anchor on the container behind them, but these are less noticeable due to their being in the middle of a string of buttons.

**Comment by dhanasekaranc** [comment]
@anth-volk can you assign this issue to me?
