### ISSUE TITLE
Make household input handling resilient

### ISSUE THREAD

**Issue by Aurora-zyy** [PolicyEngine/policyengine-app#722]
**Issue:**
In current "Compute my household income, tax, benefit" portal, every input text box pertinent to money has a "$1000" or "$0" default text, leading to intuitive input of money number with $ unit. 
<img width="589" alt="Screen Shot 2023-09-26 at 17 29 34" src="https://github.com/PolicyEngine/policyengine-app/assets/51138859/78cfe854-094c-4cea-891a-58f800b23d67">

This leads to crash: 
{"status": "error", "message": "Error calculating household #34547 under policy #2: {'people': {'you': {'employment_income': [None, None, None, None, None, None, None, None, ..... None, None, None, \"I couldn't understand '$70000' as a value for 'employment_income'\"]}}}"}
<img width="1061" alt="Screen Shot 2023-09-26 at 17 25 38" src="https://github.com/PolicyEngine/policyengine-app/assets/51138859/582b026a-ec7d-4625-b90b-cb384062410c">
<img width="1275" alt="Screen Shot 2023-09-26 at 17 26 33" src="https://github.com/PolicyEngine/policyengine-app/assets/51138859/abbdd084-b6d8-4699-8ad2-1774ec890a88">

**Proposed Action:** 
-Put the $ unit in front of input text box, delete it in default font
-return red error message near input box for invalid input

**Comment by anth-volk** [comment]
Alternatively, just a proposal: we could have it always append itself to the beginning of the currency input, then sanitize it from the transmitted data

**Comment by nikhilwoodruff** [comment]
Most likely solution: strip out dollar and comma signs after submission
