### ISSUE TITLE
Add Colorado Fiscal Institute logo to homepage

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#724]
https://www.coloradofiscal.org/

![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/a36d8137-3ec2-4c15-a061-3dd03a23993f)

**Comment by dhanasekaranc** [comment]
@MaxGhenis @nikhilwoodruff can I know to which country should I add this too?
also can you assign this issue to me?

**Comment by MaxGhenis** [comment]
US
