### ISSUE TITLE
Breakpoint issue with buttons in the HomeLanding component on the re-design Home page

### ISSUE THREAD

**Issue by nung22** [PolicyEngine/policyengine-app#735]
Action buttons jut out of the component between the _1325px_ and _1880px_ breakpoints.

![Screenshot 2023-10-12 124933](https://github.com/PolicyEngine/policyengine-app/assets/37952714/717a8c34-9585-4f3d-a7a1-a37e5759aeb1)

**Comment by tmatheas** [comment]
@nung22 Can you assign me this issue ? Also can you add `Hacktoberfest` label to this issue ?

**Comment by dhanasekaranc** [comment]
@nung22 can you assign me this issue?

**Comment by dhanasekaranc** [comment]
@nung22 UI is different from what is shown in issue, I am not able to see the buttons. can you please provide clarification on that?

**Comment by nung22** [comment]
@dhanasekaranc @tmatheas Sorry for the confusion, I mislabeled this issue. It's for a redesign project happening off the main branch.

**Comment by anth-volk** [comment]
I had been under the impression that this was a design choice. Is that not the case?

**Comment by nung22** [comment]
> I had been under the impression that this was a design choice. Is that not the case?

I took a look at the Figma file and you're correct, the buttons do protrude on the design guide. 

I just noticed that at certain breakpoints they're encompassed by the component, then protrude as the screen shrinks. Thought it might help with consistency if we changed them to stay within the component the whole time or start out protruding.

![PolicyEngine_issue_735_gif](https://github.com/PolicyEngine/policyengine-app/assets/37952714/77871836-2997-4f8d-9f16-a43ae07e45c9)

**Comment by anth-volk** [comment]
That, or if we at least increased the lowest pixel width for breakpoint number two so that the buttons move to the bottom of the "Computing Public Policy for Everyone" box instead of expanding outside of it - doing so may also improve readability

**Comment by nikhilwoodruff** [comment]
Thanks all- I think it's actually fine and in line with the Figma, but feel free to open if anyone disagrees
