### ISSUE TITLE
Blank screen when loading a reform

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#737]
I created this reform an hour or so again, and when reloading it just now it gave an empty screen. Starting from a fresh session it works again. Logging here as I'm not sure if it's an API or package issue, but regardless it would be good to show an error message instead of a blank screen.
https://policyengine.org/us/policy?reform=32061&focus=policyOutput.netIncome&region=co&timePeriod=2023&baseline=2

<img width="1470" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/34d6366d-95bb-4e2c-b217-6acdefc8fd67">

**Comment by anth-volk** [comment]
Strangely enough, when I clicked the link, then refreshed the browser, it still displayed for me. When you say “reloaded,” do you mean refreshed the browser? Or something else?

**Comment by MaxGhenis** [comment]
Yeah I doubt it's immediately reproducible, and I didn't grab the console log before navigating away. I think I started by [swapping baseline and reform](https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=2&region=co&timePeriod=2023&baseline=32063), and/or refreshing the browser.
