### ISSUE TITLE
Hide variable description on net income (overview) page

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#74]
Maybe show it when expanded, but these descriptions generally aren't informative enough to justify so much real estate imo
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6076111/208252459-e4e57066-dc70-465d-90c2-554d1a0ece61.png">

**Comment by nikhilwoodruff** [comment]
Agree on lack of conciseness, but what about:
`Total income from non-government sources`
`Total income from government benefits`
`Total taxes paid by all individuals`

**Comment by anth-volk** [comment]
These descriptions are no longer present. Closing.
