### ISSUE TITLE
Reduce contrast between inactive and active buttons

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#746]
Most buttons I see online have more subtle highlighting than we do: Slack does a slight shrink or thicker border, GitHub makes the green a tiny shade darker, Google adds a shadow, etc. 

I think we could adopt some of those, or make the current highlight color closer to the inactive color:
<img width="1025" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/36c61397-bdd7-4952-9f51-c8c7d6baad7e">

<img width="1029" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/95e0f079-1539-4cef-9798-8b36a06d4012">

**Comment by dotslashbit** [comment]
Is there any final decision on what should be done? If yes, then I'll be happy to take it

**Comment by MaxGhenis** [comment]
Lightening the dark teal shade would be the simplest. More broadly though I think we should move to a standard React UI framework.
