### ISSUE TITLE
Replace `No data` with `No variables` when no results in `Varying your earnings` search box

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#748]
<img width="583" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/80bbe16e-e7fb-433f-b1ff-bb9f41467e90">

**Comment by thevishvammoliya** [comment]
The "No data" icon that is being displayed here, is most probably defined inside the Ant design library, I doubt it can be modified as we can not access the actual code that implements the component.

We might need to create a custom component for Variable Search if we wish to change "No Data" icon to a "No Variable" icon.

**Comment by amar9312** [comment]
Hi @anth-volk, that prop for Antd select is  `notFoundContent="No variables"`. 
![image](https://github.com/PolicyEngine/policyengine-app/assets/8081089/ddd28612-9f1a-4421-87e5-eb6ba30f0858)
This is how it it going to look like without the icon.

**Comment by anth-volk** [comment]
Exactly, that's the issue, right? In searching, I couldn't find any way of changing the text without removing the icon, but you've been far more in the weeds on this; have you found one?

**Comment by amar9312** [comment]
> Exactly, that's the issue, right? In searching, I couldn't find any way of changing the text without removing the icon, but you've been far more in the weeds on this; have you found one?

We can achieve similar results by using [Empty](https://ant.design/components/empty) component.

code:
![image](https://github.com/PolicyEngine/policyengine-app/assets/8081089/f54a0574-a8bd-4444-b4a7-9f5cc62c9d2c)

results:
![image](https://github.com/PolicyEngine/policyengine-app/assets/8081089/a4302b25-1d50-4adc-982b-2cca1dff4a60)

**Comment by amar9312** [comment]
Hi @anth-volk, kindly check this at your convenience.

**Comment by anth-volk** [comment]
Will do. This is super nitpicky, and I can't review yet, but in the meantime, could you change the "v" in "variables" to lowercase? I feel that better matches the text styling we've used throughout. Thanks for the contribution!

**Comment by anth-volk** [comment]
Hey @amar9312 did you happen to open a PR on this? I'm not finding it now.

**Comment by amar9312** [comment]
Hi @anth-volk, kindly check the [PR](https://github.com/PolicyEngine/policyengine-app/pull/1027). 

Please be known that this change will reflect where the component `SearchOptions` is used across the app. Kindly suggest if we should change this behaviour.

**Comment by anth-volk** [comment]
Thanks @amar9312, will do
