### ISSUE TITLE
Restore policyengine.org/{country}/docs variable+parameter list

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#749]
The update removed these, e.g. https://policyengine.org/us/docs

**Comment by nikhilwoodruff** [comment]
Needs a design specification first

**Comment by MaxGhenis** [comment]
I think what we had before looked pretty good?

Can we unify this with the Streamlit app as a broader API Explorer?

**Comment by anth-volk** [comment]
At the very least, can we make a more obvious link to them on the site? I actually didn't realize these docs pages existed previously.
