### ISSUE TITLE
Restore API Explorer Streamlit app showing how to use the REST API

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#750]
This used to be at the bottom of the homepage

**Comment by nikhilwoodruff** [comment]
Do we still want it on the homepage? Feel like it deserves its own page.

**Comment by MaxGhenis** [comment]
Agreed - let's link it here on the homepage (the link currently goes to the Python package documentation)
<img width="1276" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/a08a888f-f757-4990-b8c1-ca163bc4284d">

**Comment by MaxGhenis** [comment]
Fixed in #842 

e.g. https://policyengine.org/us/api
