### ISSUE TITLE
Remove space after hyperlinked text in blog posts

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#752]
<img width="840" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/4b7c14ba-4227-48fd-8fd8-88ce79760c4c">

**Comment by anth-volk** [comment]
This issue is driven by the fact that when hovering over a link, a blue background pops to the right and the text moves slightly to the right, as well, filling the 10px of padding that is adding the extra space. It seems to me that to solve this, we'd have to remove the right movement of the text, as without the padding, all of the remaining text in the line pops to the right with the transition on hover.

**Comment by anth-volk** [comment]
I'd be curious to hear what @nikhilwoodruff thinks, as well

**Comment by nikhilwoodruff** [comment]
Yes that's exactly it @anth-volk. I didn't want the rest of the text to move about when you highlight one link

**Comment by anth-volk** [comment]
@nikhilwoodruff How would you like us to proceed in fixing this? The most logical method I could see would be changing how the highlighting works (perhaps by removing the space around the word and removing the text's rightward movement).

**Comment by nikhilwoodruff** [comment]
OK in my defense I don't really see this as an issue (the space on the right doesn't overly look strange IMO). But @MaxGhenis feel free to veto that opinion. If so, then I think the solution is to remove the rightward movement and the space together.

**Comment by anth-volk** [comment]
Fair enough. Curious to hear Max's thoughts.

**Comment by MaxGhenis** [comment]
It does look wrong to me. I think we should align with other sites, not aware of other online content frameworks that show links this way

**Comment by nikhilwoodruff** [comment]
OK lets remove the rightward animation and the space

**Comment by MaxGhenis** [comment]
https://www.loom.com/share/52d87100f20a428c8c1b59a4c885b5f3

**Comment by amar9312** [comment]
Hi @MaxGhenis, is [this](https://www.loom.com/share/f966d9354c2445a7a1b51dcdd0640294) what the hyperlinked text should look like (Never mind, the video recording has lags in the start).

**Comment by MaxGhenis** [comment]
Yes thanks! I think we'll otherwise want to move to a more standard link UI (without the fill) but this would be great to start
