### ISSUE TITLE
Spacing issue on homepage action buttons

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#753]
<img width="1242" alt="Screen Shot 2023-10-19 at 11 36 33 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/00de91bd-8448-4f4f-9d84-e9e30980c700">

Action buttons on the homepage in the 768-1365px breakpoint range have spacing errors above and to the side. Additionally, when minimizing to around 800 or 900px, the buttons extend outside the background box.

**Comment by nikhilwoodruff** [comment]
Yes, this is the part of @nung22's original issue I think is still relevant (thanks again)

**Comment by sash9696** [comment]
Hello @nikhilwoodruff and @MaxGhenis MaxGhenis could you please assign this issue to me? :)

**Comment by MaxGhenis** [comment]
Please file a pr from your fork, no need to be assigned. Thanks!

**Comment by ductbuix** [comment]
Looks like this issue duplicated by #757

**Comment by MaxGhenis** [comment]
#757 is about the headline not the buttons

**Comment by anth-volk** [comment]
Solved by #849. Closing.
