### ISSUE TITLE
Right sidebar label text is covered by main panel at smaller breakpoints

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#754]
<img width="1211" alt="Screen Shot 2023-10-19 at 11 49 03 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/ee7e3de4-91d3-4b2a-af84-cdf20695572c">

**Comment by dotslashbit** [comment]
I don't think this is an issue anymore, if yes then please close this, thanks

**Comment by anth-volk** [comment]
Shoot, you're right, this was fixed in #899. Thanks for noting.
