### ISSUE TITLE
Homepage headline doesn't fit in box on mobile

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#757]
![Screenshot_20231020-085645.png](https://github.com/PolicyEngine/policyengine-app/assets/6076111/df9c08e9-9dfe-45e8-a627-38799d619cc6)

**Comment by ductbuix** [comment]
Hi @MaxGhenis @nikhilwoodruff , I'm a new contributor, hope I can help.

I've read the issue and check the source code, and I have a question, how the text displays on mobile? Does it have a specific font size or just best fit?

**Comment by MaxGhenis** [comment]
Thanks @ductbuix! Either a smaller font size or best fit, whichever gets it to look OK and similar to web.

**Comment by ductbuix** [comment]
@MaxGhenis  So can you assign it to me, I can handle it. And I found that there is a problem with the outer container, should I fix it in this issue or create another one?

Before
<img width="363" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/89175427/d1ec48a2-34b4-4a74-80c2-03cbe694ab3b">

After
<img width="371" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/89175427/77887073-5a44-44f1-bb46-75b021e44de9">

**Comment by MaxGhenis** [comment]
Yeah I think the container fix looks good. Please go ahead and file a PR from your fork connecting to this issue, and include the container fix, no need to be assigned.
