### ISSUE TITLE
Chart `Download` button/dropdown is in the left pane

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#759]
Instead of by the chart
![image](https://github.com/PolicyEngine/policyengine-app/assets/6076111/8ec701fa-cf1b-4a67-a9b2-fcb69aa13bed)

**Comment by abhcs** [comment]
@nikhilwoodruff @MaxGhenis I can move the button closer to the chart, but is there a specific position that you would like it to appear at, e.g., after "share this result ... ", under the caption, etc.?

**Comment by MaxGhenis** [comment]
So it used to be below the chart on the left. But I think we should reorganize it to be with the share links: all go in a row below the chart, this one with a download icon, and we remove the "Share this chart" text.

**Comment by abhcs** [comment]
Sounds good. I will need to add two icons, one for the 'download img' and the other for 'download csv'.
