### ISSUE TITLE
Organization logos are hard to read on US site

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#760]
The logos included in the "Trusted Across the US" bar are quite a bit smaller on the US site than the UK site; perhaps they're each longer on the US version? Additionally, it appears the width of the bar is fixed to only be about 50% of the entire page at desktop breakpoints. It may be better to widen that, especially if we add more organizations to it.

**Comment by dotslashbit** [comment]
@anth-volk Is this still open? Asking as the current PR hasn't been updated since 3 weeks

**Comment by anth-volk** [comment]
I'd say that at this point, yeah, it is. Thanks for looking to take this on, @dotslashbit! I'll get around to your other PRs either late today or early next week, as I have to finish something else first.
