### ISSUE TITLE
Navbar links extend beyond the visible link area

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#761]
Minor issue, but the anchor tags on the navbar links extend outside of the visible link area (the area that turns lighter when hovered) into the buffer area between the nav options

**Comment by dotslashbit** [comment]
@anth-volk can you share a video of this issue?

**Comment by anth-volk** [comment]
Sure, a video is available [here](https://www.loom.com/share/95dbfb1416f243d98504a50ffe844383?sid=5a34b5af-3e5e-4d15-890c-ac618d427ea4). Basically, when the cursor goes outside the light blue hover part, you'll notice that the cursor remains `pointer` and you'll see in the bottom-left corner that it still wants to direct you to an address.
