### ISSUE TITLE
US household input doesn't appear to provide default state, but then defaults to California

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#765]
<img width="1440" alt="Screen Shot 2023-10-20 at 11 15 22 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/d6050e97-0bb0-4d7c-aaf0-4624323f90f5">
On the above screen, it's possible to click `Enter` without actually choosing a state, making it appear that the user hasn't selected a state. However, if the user does so, they progress to the output screens without issue, and if the user selects the `state` option under `geography` on the left-side variable editor, it displays `California` as the selected state.

**Comment by nikhilwoodruff** [comment]
Yeah we should disable the enter button until the state is provided
