### ISSUE TITLE
Site no longer displays the interstitial message indicating what the household calculator does and doesn't calculate

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#766]
Was removing this a design choice?

**Comment by MaxGhenis** [comment]
Let's restore it

**Comment by anth-volk** [comment]
Think I cracked the problem on why this isn't displaying. See my commentary on #762.

**Comment by nikhilwoodruff** [comment]
Thanks, blocked til that's resolved

**Comment by anth-volk** [comment]
Solved by #867. Closing.
