### ISSUE TITLE
Calculator button in the header doesn't work on mobile 

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#767]
Doesn't do anything

**Comment by nikhilwoodruff** [comment]
Needs to link to the /calculator page

**Comment by amar9312** [comment]
This [commit](https://github.com/PolicyEngine/policyengine-app/commit/5bb4f530f4dcb5aa81e9b5872fea50d6f9798d17) intends to fix this issue.
