### ISSUE TITLE
`VariableEditor` component's disabled button no longer has distinct styling

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#774]
The optionally disabled button on [line 101 of VariableEditor](https://github.com/PolicyEngine/policyengine-app/blob/25fa829fd9ceae011e1a3d3c62a9aec4ff8ce843/src/pages/household/input/VariableEditor.jsx#L101) is no longer styled any differently from the primary-style button

**Comment by nikhilwoodruff** [comment]
Think this is fine and by design!
