### ISSUE TITLE
On the Reproduce in Python page, the left arrow button is slightly further right

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#775]
A minor issue, but on the Reproduce in Python page, where there's no arrow to move right, the left arrow moves a bit to the right of where it is for the other pages. I'm not sure if this is an error or more a design choice, but if it is meant to move over, it might be better to have it sit in the same spot as where the right button would usually be. I'll upload a clip later to demonstrate what I mean.

**Comment by amar9312** [comment]
Hi @anth-volk, if we change the blank <div> width to 80, it seems to fix this issue but I wonder if it will be good for all screen sizes. I can create a PR if you approve this. 

Thanks, Amar

![image](https://github.com/PolicyEngine/policyengine-app/assets/8081089/175e6366-5b2e-4461-82ea-49ba77de9f68)

**Comment by anth-volk** [comment]
Shoot, this may actually be solved by #867, though I forgot to mention it in the PR. Also, I probably should've separated that into multiple PRs in hindsight.

Also, so as to not step on any toes, I'm going to mention @nikhilwoodruff here. The buck ultimately stops with him and @MaxGhenis on these sorts of decisions, so anything I'm saying in any of these comments is merely my opinion.

**Comment by MaxGhenis** [comment]
Just for posterity the issue is that the pair of buttons is centered, which makes the left one more rightward when the right one vanishes
<img width="1388" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/db3625bc-4f60-42ba-95ed-8fe84b7ce868">

<img width="692" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/8a885d06-195f-4913-b941-e796020ce949">

**Comment by anth-volk** [comment]
It looks like part of the problem, too, is that the button itself is built as two `div`s: the outer applies the hover effect (since inline styling prevents using CSS pseudo-elements to do it) and the inner contains the content. The outer allows for custom styling, if I remember correctly, but the inner requires a fixed width of 60px, so even though the code @amar9312 shared creates a button of 50px square, the inner overflows and makes the button 60x60 or 60x54, I can't remember which.

To proceed, I'm thinking after #867, we could make a few more fundamental edits to the button class that controls this so that it can be resized without having to manually specify sizing.

**Comment by Zouziszzm** [comment]
Hello Is this issue solved ? I couldn't find the page. @MaxGhenis @anth-volk

**Comment by MaxGhenis** [comment]
It got fixed

Sample link for posterity https://policyengine.org/us/household?focus=householdOutput.pythonReproducibility&household=35108
