### ISSUE TITLE
Link to Open Collective is not a true link, disabling right-click options

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#776]
For accessibility and convenience reasons, it'd be good to re-engineer this so that it's a true link

**Comment by zedgamer9128** [comment]
I would like to try this and also where is this link

**Comment by sash9696** [comment]
Hello @nikhilwoodruff and @MaxGhenis MaxGhenis Can I be added as a collaborator so I can create a PR for this issue? :)

**Comment by MaxGhenis** [comment]
no need to be assigned just file a pr from your fork, thanks

**Comment by MaxGhenis** [comment]
it's on https://policyengine.org/us/donate

**Comment by anth-volk** [comment]
If you wouldn't mind holding off on this, I have an open PR (#867) that more fundamentally re-engineers buttons and would likely conflict with this change

**Comment by amar9312** [comment]
Hi @anth-volk, kindly check this new [PR](https://github.com/PolicyEngine/policyengine-app/pull/958) at your convenience.

**Comment by anth-volk** [comment]
Thanks, will do tomorrow

**Comment by MaxGhenis** [comment]
Closed in #958
