### ISSUE TITLE
Subscribe button hover effect doesn't work at particular breakpoint

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#814]
When using the website on the wider end of the mobile breakpoint, the subscribe button's hover effect only fills about 80% of the button. This applies to both the button inside the footer and the button inside the subscribe component.

https://github.com/PolicyEngine/policyengine-app/assets/14987227/dd502c8b-0fd2-46f8-aac5-8265725e3ad6

**Comment by ajpage** [comment]
Hello @nikhilwoodruff and @MaxGhenis. Can I be added as a collaborator so I can create a PR for this issue? :)

**Comment by MaxGhenis** [comment]
Thanks @ajpage - you can actually just create a PR from your fork. Thanks!

**Comment by anth-volk** [comment]
Fixed by changes made by @dotslashbit. Closing.
