### ISSUE TITLE
Endless spinner for households outside California in net income computation

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#82]
I've run several scenarios in California, where the net income computations work fine. But any scenario for households outside California create an endless spinner when computing net income, e.g. https://beta.policyengine.org/us/household?household=820&focus=householdOutput.netIncome

This isn't just a problem with non-cached households, e.g. [this new California household](https://beta.policyengine.org/us/household?household=844&focus=householdOutput.netIncome) computed fine

**Comment by nikhilwoodruff** [comment]
Due to HHS SMI
