### ISSUE TITLE
UBI only benefits 99.98% of the population

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#84]
I don't think it's a % threshold thing, since the loser sliver is in the bottom decile:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/6076111/208309377-dfa998a0-3178-446d-be18-0e12086bebae.png">

https://beta.policyengine.org/us/policy?reform=168&focus=policyOutput.intraDecileImpact&region=us&timePeriod=2022&baseline=2

**Comment by nikhilwoodruff** [comment]
Ah, I think it's probably a record with negative income

**Comment by MaxGhenis** [comment]
Yeah also the [current app](https://policyengine.org/us/population-impact?bi_amount=1000) shows 100% of the bottom decile benefiting. Could that be negative income too?
<img width="902" alt="image" src="https://user-images.githubusercontent.com/6076111/208970088-d3de180e-ebaf-46c4-93b7-5ffb1ccf2d79.png">

**Comment by MaxGhenis** [comment]
Back below 100% https://beta.policyengine.org/us/policy?focus=policyOutput.intraDecileImpact&reform=168&region=us&timePeriod=2022&baseline=2

<img width="844" alt="image" src="https://user-images.githubusercontent.com/6076111/209761356-26486531-6688-4cfe-bd9a-16cc626874fa.png">

**Comment by nikhilwoodruff** [comment]
Yeah I think I found the issue (was a bit lazy and pushed straight to master just now). Reform income wasn't capped at 1, like baseline income, when calculating the income change.

**Comment by MaxGhenis** [comment]
🎉 
<img width="852" alt="image" src="https://user-images.githubusercontent.com/6076111/210129260-d0df8ae6-2a84-4168-b5f8-6e3bbf843626.png">
