### ISSUE TITLE
Add a command to handle both linting and formatting with Prettier

### ISSUE THREAD

**Issue by avelynhc** [PolicyEngine/policyengine-app#865]
When running `npm run lint`, it prompts me to execute Prettier separately for formatting. It would be convenient if `npm run lint` could handle both linting and formatting without the need for an additional Prettier command.

<img width="568" alt="Screenshot 2023-11-22 at 6 11 27 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/75185537/3be82871-dab2-4f5e-b5f5-b09eed3e1a33">

**Comment by anth-volk** [comment]
Perhaps as part of this or separately, it's probably best to change the `make format` rule to not use Black, as that seems non-standard

**Comment by avelynhc** [comment]
@anth-volk Can I work on this issue first, and then tackle the next one?"

**Comment by anth-volk** [comment]
Hey, seems like a plan to me

**Comment by MaxGhenis** [comment]
Removing `black` here sounds fine since there's not much Python, but just as context we use it in all the PolicyEngine Python packages (and I do like how directive it is)

**Comment by anth-volk** [comment]
Completed via #902. Closing.
