### ISSUE TITLE
Align API documentation `Example input` and `Output format`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#869]
<img width="1131" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/fde00c8d-03b9-43ca-9217-27bf160acdd5">

https://policyengine.org/us/api

**Comment by pkvijay65** [comment]
Hi @MaxGhenis, I have raised MR for this issue. This is my first step towards open source contribution. Let me know if you any feedback on this.

Thanks so much.
