### ISSUE TITLE
Make `CHOOSE A CALCULATOR` page mobile-friendly

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#877]
https://policyengine.org/us/calculator

<img width="386" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/29bea44a-b4d7-4d9f-a10e-5a918fbc69b4">

**Comment by anth-volk** [comment]
I'll be working on this today as part of a more comprehensive set of mobile optimizations

**Comment by anth-volk** [comment]
Fixed in #899. Closing.
