### ISSUE TITLE
Make each policy provision a sentence

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#88]
How about replacing the current with this in the right panel (soon to be carousel thanks to @DeepthiSRao)?
>Raise the Ofgem Energy Price Cap from **£70** to **£80**
_2022-01-01 to 2027-12-31_

Where £70 could be gray and £80 could be blue

**Comment by DeepthiSRao** [comment]
@nikhilwoodruff  Do you know where the old reform value is saved?

**Comment by nikhilwoodruff** [comment]
In `parameters.js`, there's a `getParameterAtInstant(parameter, instant)` that will take the parameter object (from `metadata.parameters` and return the value at a given instant. I think we want to compare against the value at the start instant, 2022-01-01 here.
