### ISSUE TITLE
Accessibility: consider adding features to the Research page's search box

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#882]
We may want to add a magnifying glass icon to the box and/or a button that says "search" after someone has typed into the box to make it even clearer what its purpose is and to enable easier use with screen readers, assistive devices, etc.

**Comment by dotslashbit** [comment]
I think this has been resolved, please close this if that's the case

**Comment by anth-volk** [comment]
Huh, so it has been. Thanks for mentioning this.
