### ISSUE TITLE
Mobile breadcrumbs lack bold or underline on hover

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#896]
E.g., if I hover over "Social Security Administration (SSA)", nothing happens, even though the breadcrumb trail is a trail of links

<img width="720" alt="Screen Shot 2023-11-25 at 7 49 44 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/9ca5f9bd-d4bd-47c1-80d8-1181e2eeef4e">

**Comment by dotslashbit** [comment]
I think this is fixed, currently its showing the link in bold. If you want any modification then please let me know I would love to work on it
<img width="461" alt="Screenshot 2024-01-05 at 5 09 10 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/46224156/e241b092-3082-4fd6-9cfc-a23267f98ca2">

**Comment by anth-volk** [comment]
Good point, thanks, quite a few things were solved within the mobile redesign. Closing.
