### ISSUE TITLE
Too much padding on Reproduce in Python page

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#897]
In the area between the "COPY" button and the text below it

<img width="1440" alt="Screen Shot 2023-11-25 at 10 10 22 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/12464931-44c5-4395-b422-9544b2244d6b">

**Comment by lchauha** [comment]
Hi @anth-volk  I would like to work on this issue. Please assign

**Comment by maurobusso** [comment]
Hi, I have opened a pr for this issue.
