### ISSUE TITLE
`EmphasizedLink` arrow is slightly lower than text on blog articles

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#903]
Visible in the image below:

<img width="445" alt="Screen Shot 2023-11-26 at 5 55 03 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/9c6f4a53-a0a8-445f-949d-769fcfe3b03f">

**Comment by anth-volk** [comment]
This may altering fixing line height to ensure it's only the height of the font of "READ"? Unsure

**Comment by MaxGhenis** [comment]
I'd suggest we skip this in favor of https://github.com/PolicyEngine/policyengine-app/issues/904
