### ISSUE TITLE
Remove "i" icon and better center info on the calculator interstitial

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#916]
<img width="501" alt="Screen Shot 2023-11-28 at 5 58 24 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/cdbbab88-8b5a-4eb7-9e9d-cfdd1fa967f1">

**Comment by dotslashbit** [comment]
I have modified the popup as required, let me know if there's any changes needed to be done, thanks
