### ISSUE TITLE
Remove decimals from age input box

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#928]
example https://policyengine.org/us/household?focus=input.household.age

<img width="674" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/d7787cfe-c674-4dec-806c-0524e2feae01">

**Comment by abhcs** [comment]
@MaxGhenis I am not sure that age is an int. The backend reports to the front end that it is a float, and its float-ness is used in variables such as ccdf_age_group.

**Comment by MaxGhenis** [comment]
You're right my mistake! Will check after updating -us
