### ISSUE TITLE
Specify in household right sidebar whether numbers concern baseline or reform, or show diffs instead

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#93]
I think diffs probably make more sense but unsure

![Image](https://user-images.githubusercontent.com/6076111/209459509-59bb66aa-3b60-467b-ac3b-abd9108a6a35.png)

**Comment by nikhilwoodruff** [comment]
Now baseline-only, feel free to reopen if we should show diffs though
