### ISSUE TITLE
Restore the `InputNumber` component in `VariableEditor` and create new households less frequently when the user is editing a household

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#946]
This issue is the household counterpart to issue #691. It is less severe than #691 since duplicates are not created, but more severe since we use more interactive input components like InputNumber.

## Steps to reproduce:

1. Create a household with income `x`.
2. Note the household id in the URL as `i`.
3. Edit the income using the up arrow key till it reaches `y`.
5. Note the household id in the URL as `j`.

The number of new households is `j-i` (assuming no one else is using the app). Observe that `j-i` is close to `y-x` in most cases.

## Expected output

We should see `j = i`, i.e., the household id should not change while the user is editing the current household. A new household should be created only when the user explicitly instructs the app to do so.

When the user asks the app to create a new household, the app should:
1. Show them the current household id asking them to note it down for future reference.
2. Ask them to confirm if they want to create a new household, warning that they may lose access to their previous work.
2. Allow them to back to editing the current household.

**Comment by anth-volk** [comment]
This is a great catch, @abhcs, if we had noticed the connection between this and the weirdness of #952, perhaps we could've fixed it faster. This is definitely going to require changing how the `submitValue` function, which is passed as an arg to the antd `InputValue` component's `onChange` param, operates so that we ensure it only fires on submission, blur, or keyup - in fact, it may be as simple a fix as that.

**Comment by abhcs** [comment]
This is a deeper issue than just delaying the household creation to 'on blur'. The issue is present even now with `Input`. Why should clicking outside the input box after playing with it for a while create a new household? It should not. The slightly naive `InputNumber` addition made this weakness in the design even more apparent.

I agree that a temporary fix would be to at least decrease the frequency of new household creation, as you suggest in your comment.

In the long run, however, it would be better to design a workflow/UI experience in which households are explicitly created, as mentioned in the description of the issue.

**Comment by anth-volk** [comment]
I agree with your proposal above, to an extent - in particular, if the application lacks any sort of authentication and/or user account structure, I don't feel this is as necessary. 

That said, I think many contributors have noted a desire to redesign the calculator component to integrate authentication, structure the household creation process more akin to what you've described, and create an easier-to-understand user interface. There were some planning and discussion sessions toward doing so earlier in the year, but they fell by the wayside in favor of more pressing issues.

I suppose what I'm trying to say is there is some desire to rip the whole thing out and implement better logic, but it seems best to do it all at once, within a comprehensive build phase that would see us rebuilding and improving more than just the household creation logic. When we're able to return to this initiative, it'd be great to have your input.

**Comment by abhcs** [comment]
I have renamed the issue so that we can close it with PR #975. The stronger requirement of eliminating the spurious creation of households has been reopened as #998.
