### ISSUE TITLE
Button components should be rewritten against Ant Design

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#950]
This has implications for form submission actions, event firing, and accessibility

**Comment by anth-volk** [comment]
Hey @dotslashbit, in response to what you said, here's what we're looking for for the button:

1. Ideally, there should be a base component that is extendable into the various other types of buttons we have, much like what already exists (for example, how we have a `LinkButton`, I believe it is, that is just the `Button`, but handling internal and external links
2. The button should be based upon the Ant Design [button](https://ant.design/components/button), but with a few changes:
    1. The edges should be squared off, like the rest of the application
    2. The color of the button should match what we currently use for a color
    3. The text should be capitalized by default, like what's currently in use on the website
3. Like normal buttons, the button should allow for the right-click context menu that's default on Windows (or the Control-Click menu on Mac)
4. There should be some sort of effect applied that indicates to the user that the button is hovered upon, but that effect should be instantaneous; ideally, the color of this effect should be what we currently use on the site

That's probably all of the specifications I can think of at the moment. If you'd be willing, it'd be great if you could implement, then we could revisit any additional edits afterward to ensure continuity with the current UX. Thanks so much.

**Comment by dotslashbit** [comment]
@anth-volk Okay, I will work on it, and currently keep it as a draft PR, but would ping you if there's any help needed. I hope you can assist me, if needed.

**Comment by anth-volk** [comment]
@dotslashbit This all looks good so far, thanks for this, and it's a shame that there isn't a better way to set the hover styling, short of fully implementing Ant Design's `ConfigProvider` feature (as mentioned in #1181). All of your changes look good, though I'd ask that moving forward, you replace the existing `Button` component with this new one instead of creating `NewButton` and that you move this into the standard file directory, instead of `redesign`.

**Comment by dotslashbit** [comment]
@anth-volk Will do that. I created a new button component, just to try it out and see if it's replicating the button component or not. Sure, I'll move this to standard directory.
