### ISSUE TITLE
Unable to type to search in the household calculator state dropdown box

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#954]
<img width="1440" alt="Screen Shot 2023-12-11 at 6 09 23 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/acd175d8-a0cf-4241-9f59-e15596a2d824">

For this one here, there's no way to type and filter what state you want to choose. I wouldn't be surprised if this were also true for other dropdowns in the calculator interfaces.

**Comment by abhcs** [comment]
Was introduced in #892. Will fix.
