### ISSUE TITLE
Mobile header calculator button seems weirdly far left of the menu dropdown

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#963]
<img width="400" alt="Screen Shot 2023-12-14 at 12 07 17 AM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/606ee561-cf13-4209-b582-d6e131aa0e7c">

I think it would be best to move it further right and make the spacing more consistent

**Comment by dotslashbit** [comment]
Is this still available?

**Comment by anth-volk** [comment]
Sure, anything we have open without a linked PR (usually it'll show up in the issue feed) is available!

**Comment by dotslashbit** [comment]
OK, thanks

**Comment by dotslashbit** [comment]
@anth-volk I have made the required changes, let me know if there's any modification needed, thanks

**Comment by anth-volk** [comment]
Thanks, will check into this early next week
