### ISSUE TITLE
The parameter input box does not parse strings with commas or currency symbols

### ISSUE THREAD

**Issue by abhcs** [PolicyEngine/policyengine-app#967]
Try changing the parameter in

https://policyengine.org/us/policy?focus=gov.contrib.ubi_center.basic_income.amount.person.flat&reform=40063&region=us&timePeriod=2023&baseline=2

to `1,100`. The string is parsed by the app as `1`. Now try `$11`. This is parsed as `0`.

Suggestion: We should use `InputNumber` here, like we do in `VariableEditor` for households.

**Comment by anth-volk** [comment]
We should probably wait to work on this until solving #1001.
