### ISSUE TITLE
Direct donation page to opencollective.com/policyengine

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#970]
We now have our own OpenCollective page: https://opencollective.com/policyengine

**Comment by dotslashbit** [comment]
What's this issue is about?

**Comment by MaxGhenis** [comment]
https://policyengine.org/us/donate

**Comment by anth-volk** [comment]
In the web app’s `Donation` page, we link to an older donation address that we’re hoping to update to the one Max provided above.

**Comment by dotslashbit** [comment]
ok got it, working on it

**Comment by dotslashbit** [comment]
I have made the required changes, please let me know if there's any modification needed, thanks
