### ISSUE TITLE
Direct `Enter your household` from the policy reform screens to the household questionnaire

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-app#98]
Steps:
1. Click `Compute the impact of policy reforms` from beta.policyengine.org
2. Make any reform
3. Click `Enter your household`

This goes to the computation page for an empty household. If you do the above but skip step 2 (no reform), it goes to the intro household questionnaire, which should be the behavior any time a household hasn't gone through the questionnaire.
<img width="1907" alt="image" src="https://user-images.githubusercontent.com/6076111/209565866-399a1bae-7852-4588-8a2c-80ca304a64e6.png">

**Comment by MaxGhenis** [comment]
Now this sequence produces a blank screen:

https://www.loom.com/share/e243e13ce7da4073944375ec4b5471ad

**Comment by nikhilwoodruff** [comment]
Ran through the same steps in that Loom and works now as it should (direct to net income screen)
