### ISSUE TITLE
Padding above and below policy variable editor title is quite large on mobile

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#986]
Would be helpful to cut this down; in this image, it's the spacing above and below the "2"

<img width="451" alt="Screen Shot 2023-12-18 at 11 52 50 PM" src="https://github.com/PolicyEngine/policyengine-app/assets/14987227/28ac2d80-06b1-4d33-964b-f1ac555ef725">

**Comment by dotslashbit** [comment]
Is this available?

**Comment by anth-volk** [comment]
Yes, but it would be preferable if you waited to do this until we've finished with PR #899.

**Comment by dotslashbit** [comment]
Is this still an issue? If not, then please close this

**Comment by anth-volk** [comment]
Thanks, I did forget to update. I would say this isn't an issue.
