### ISSUE TITLE
Button positioning on policy calculator "Analysis" page is misaligned

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-app#993]
The two buttons are aligned in quite a strange way

**Comment by MaxGhenis** [comment]
This?
<img width="315" alt="image" src="https://github.com/PolicyEngine/policyengine-app/assets/6076111/eb5bce32-7905-4a31-aace-18c7dc55cfe2">


Equalizing the widths makes sense, though I wonder if some other UI element conveys hide/show more intuitively than a button

**Comment by anth-volk** [comment]
Fair point. I had meant the very large vertical gap between them.

**Comment by dotslashbit** [comment]
I want to work on this, please clarify on what kind of fix you are expecting:
- Width of both the elements should be same
- Vertical spacing between the two elements

**Comment by anth-volk** [comment]
Hey @dotslashbit, thanks for your interest in contributing! To be honest, that's something we're still working out - we'd be curious to hear your thoughts on this, as well.

@MaxGhenis Perhaps a drop-down carat button would serve this better? Also, does it make sense to put the COPY button all the way at the bottom?

**Comment by anth-volk** [comment]
Also @dotslashbit, as we work this out, would you mind contributing to #970? It's super high-impact, low-time requirement. To contribute, please feel free just to fork the app repo, then open a PR off of that.

**Comment by MaxGhenis** [comment]
Drop-down carat sounds good

Could also use a standard copy icon instead of a big button

**Comment by dotslashbit** [comment]
@anth-volk Can this be closed?

**Comment by anth-volk** [comment]
@dotslashbit Good point, the button no longer exists. Thanks for the heads-up, closing.
